In [103]:
# api call
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/live"

headers = {
	"x-rapidapi-key": "cfdf9c6205msh90e2dbc4b627d8cp118b91jsn3cd37e7c3174",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'typeMatches': [{'matchType': 'International', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matches': [{'matchInfo': {'matchId': 139252, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '31st Match, Group D', 'matchFormat': 'T20', 'startDate': '1771306200000', 'endDate': '1771318800000', 'state': 'In Progress', 'status': 'New Zealand need 124 runs in 90 balls', 'team1': {'teamId': 26, 'teamName': 'Canada', 'teamSName': 'CAN', 'imageId': 776227}, 'team2': {'teamId': 13, 'teamName': 'New Zealand', 'teamSName': 'NZ', 'imageId': 776333}, 'venueInfo': {'id': 11, 'ground': 'MA Chidambaram Stadium', 'city': 'Chennai', 'timezone': '+05:30', 'latitude': '13.06282', 'longitude': '80.279274'}, 'currBatTeamId': 13, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'In Progress', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 173, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 50, 'wickets': 2, 'overs': 4.6}}}}]}}]}, {'matchType': 'Domestic', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26', 'matches': [{'matchInfo': {'matchId': 125074, 'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26', 'matchDesc': '2nd Semi Final', 'matchFormat': 'TEST', 'startDate': '1771126200000', 'endDate': '1771497000000', 'state': 'In Progress', 'status': 'Day 3: 2nd Session - Bengal lead by 53 runs', 'team1': {'teamId': 232, 'teamName': 'Bengal', 'teamSName': 'BEN', 'imageId': 172285}, 'team2': {'teamId': 252, 'teamName': 'Jammu and Kashmir', 'teamSName': 'JK', 'imageId': 172305}, 'venueInfo': {'id': 437, 'ground': 'Bengal Cricket Academy Ground', 'city': 'Kalyani', 'timezone': '+05:30', 'latitude': '22.9792675', 'longitude': '88.4416824'}, 'currBatTeamId': 232, 'seriesStartDt': '1760486400000', 'seriesEndDt': '1772409600000', 'isTimeAnnounced': True, 'stateTitle': 'In Progress'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 328, 'wickets': 10, 'overs': 97.1}, 'inngs2': {'inningsId': 3, 'runs': 27, 'wickets': 4, 'overs': 9.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 302, 'wickets': 10, 'overs': 76.1}}}}, {'matchInfo': {'matchId': 125069, 'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26', 'matchDesc': '1st Semi Final', 'matchFormat': 'TEST', 'startDate': '1771128000000', 'endDate': '1771498800000', 'state': 'In Progress', 'status': 'Day 3: 2nd Session - Uttarakhand trail by 699 runs', 'team1': {'teamId': 128, 'teamName': 'Karnataka', 'teamSName': 'KAR', 'imageId': 776345}, 'team2': {'teamId': 467, 'teamName': 'Uttarakhand', 'teamSName': 'UTK', 'imageId': 172515}, 'venueInfo': {'id': 485, 'ground': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'city': 'Lucknow', 'timezone': '+05:30', 'latitude': '26.846694', 'longitude': '80.946166'}, 'currBatTeamId': 467, 'seriesStartDt': '1760486400000', 'seriesEndDt': '1772409600000', 'isTimeAnnounced': True, 'stateTitle': 'In Progress'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 736, 'wickets': 10, 'overs': 194.4}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 37, 'wickets': 2, 'overs': 17.6}}}}]}}, {'seriesAdWrapper': {'seriesId': 10724, 'seriesName': 'The Ford Trophy 2025-26', 'matches': [{'matchInfo': {'matchId': 132131, 'seriesId': 10724, 'seriesName': 'The Ford Trophy 2025-26', 'matchDesc': '29th Match', 'matchFormat': 'ODI', 'startDate': '1771277400000', 'endDate': '1771306200000', 'state': 'Complete', 'status': 'Central Districts won by 22 runs', 'team1': {'teamId': 313, 'teamName': 'Central Districts', 'teamSName': 'CD', 'imageId': 172363}, 'team2': {'teamId': 312, 'teamName': 'Canterbury', 'teamSName': 'CNTBRY', 'imageId': 172362}, 'venueInfo': {'id': 372, 'ground': 'Saxton Oval', 'city': 'Nelson', 'timezone': '+13:00', 'latitude': '-41.322788', 'longitude': '173.213882'}, 'currBatTeamId': 313, 'seriesStartDt': '1761350400000', 'seriesEndDt': '1771891200000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 276, 'wickets': 8, 'overs': 49.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 254, 'wickets': 10, 'overs': 48.6}}}}, {'matchInfo': {'matchId': 132120, 'seriesId': 10724, 'seriesName': 'The Ford Trophy 2025-26', 'matchDesc': '28th Match', 'matchFormat': 'ODI', 'startDate': '1771277400000', 'endDate': '1771306200000', 'state': 'Complete', 'status': 'Auckland won by 6 wkts', 'team1': {'teamId': 105, 'teamName': 'Otago', 'teamSName': 'OTG', 'imageId': 172197}, 'team2': {'teamId': 186, 'teamName': 'Auckland', 'teamSName': 'AKL', 'imageId': 172246}, 'venueInfo': {'id': 82, 'ground': 'John Davies Oval', 'city': 'Queenstown', 'timezone': '+13:00', 'latitude': '-45.016205', 'longitude': '168.738638'}, 'currBatTeamId': 186, 'seriesStartDt': '1761350400000', 'seriesEndDt': '1771891200000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 158, 'wickets': 10, 'overs': 43.3}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 161, 'wickets': 4, 'overs': 23.4}}}}]}}, {'ad': {'name': 'native_matches', 'layout': 'native_large', 'position': 3}}, {'seriesAdWrapper': {'seriesId': 10823, 'seriesName': 'Sheffield Shield 2025-26', 'matches': [{'matchInfo': {'matchId': 133363, 'seriesId': 10823, 'seriesName': 'Sheffield Shield 2025-26', 'matchDesc': '22nd Match', 'matchFormat': 'TEST', 'startDate': '1771200000000', 'endDate': '1771484400000', 'state': 'Stumps', 'status': 'Day 2: Stumps - Queensland lead by 81 runs', 'team1': {'teamId': 164, 'teamName': 'Queensland', 'teamSName': 'QL', 'imageId': 172233}, 'team2': {'teamId': 158, 'teamName': 'South Australia', 'teamSName': 'SAUS', 'imageId': 172225}, 'venueInfo': {'id': 35, 'ground': 'The Gabba', 'city': 'Brisbane', 'timezone': '+10:00', 'latitude': '-27.485829', 'longitude': '153.038055'}, 'currBatTeamId': 164, 'seriesStartDt': '1759536000000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'Stumps'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 185, 'wickets': 10, 'overs': 66.5}, 'inngs2': {'inningsId': 3, 'runs': 110, 'wickets': 4, 'overs': 38.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 214, 'wickets': 10, 'overs': 72.1}}}}, {'matchInfo': {'matchId': 133369, 'seriesId': 10823, 'seriesName': 'Sheffield Shield 2025-26', 'matchDesc': '23rd Match', 'matchFormat': 'TEST', 'startDate': '1771209000000', 'endDate': '1771493400000', 'state': 'Tea', 'status': 'Day 2: Tea Break - Western Australia trail by 349 runs', 'team1': {'teamId': 52, 'teamName': 'Victoria', 'teamSName': 'VIC', 'imageId': 172153}, 'team2': {'teamId': 87, 'teamName': 'Western Australia', 'teamSName': 'WA', 'imageId': 172180}, 'venueInfo': {'id': 38, 'ground': 'W.A.C.A. Ground', 'city': 'Perth', 'timezone': '+08:00', 'latitude': '-31.959806', 'longitude': '115.879585'}, 'currBatTeamId': 87, 'seriesStartDt': '1759536000000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'Tea'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 431, 'wickets': 9, 'overs': 116.5, 'isDeclared': True}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 82, 'wickets': 1, 'overs': 31.6}}}}, {'matchInfo': {'matchId': 133380, 'seriesId': 10823, 'seriesName': 'Sheffield Shield 2025-26', 'matchDesc': '24th Match', 'matchFormat': 'TEST', 'startDate': '1771212600000', 'endDate': '1771497000000', 'state': 'Rain', 'status': 'Day 2: Rain stops play - New South Wales lead by 158 runs', 'team1': {'teamId': 166, 'teamName': 'Tasmania', 'teamSName': 'TAS', 'imageId': 172235}, 'team2': {'teamId': 104, 'teamName': 'New South Wales', 'teamSName': 'NSW', 'imageId': 172196}, 'venueInfo': {'id': 39, 'ground': 'Bellerive Oval', 'city': 'Hobart', 'timezone': '+11:00', 'latitude': '-42.877296', 'longitude': '147.374013'}, 'currBatTeamId': 104, 'seriesStartDt': '1759536000000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 136, 'wickets': 10, 'overs': 41.3}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 294, 'wickets': 4, 'overs': 87.2}}}}]}}]}, {'matchType': 'Women', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11452, 'seriesName': "ACC Women's Asia Cup Rising Stars 2026", 'matches': [{'matchInfo': {'matchId': 144329, 'seriesId': 11452, 'seriesName': "ACC Women's Asia Cup Rising Stars 2026", 'matchDesc': '10th Match, Group A', 'matchFormat': 'T20', 'startDate': '1771311600000', 'endDate': '1771324200000', 'state': 'In Progress', 'status': 'Pakistan A Women opt to bowl', 'team1': {'teamId': 449, 'teamName': 'United Arab Emirates Women', 'teamSName': 'UAEW', 'imageId': 776246}, 'team2': {'teamId': 1552, 'teamName': 'Pakistan A Women', 'teamSName': 'PAKWA', 'imageId': 776324}, 'venueInfo': {'id': 474, 'ground': 'Terdthai Cricket Ground', 'city': 'Bangkok', 'timezone': '+07:00', 'latitude': '13.756331', 'longitude': '100.501765'}, 'currBatTeamId': 449, 'seriesStartDt': '1770940800000', 'seriesEndDt': '1771891200000', 'isTimeAnnounced': True, 'stateTitle': 'In Progress'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 53, 'wickets': 2, 'overs': 8.2}}}}, {'matchInfo': {'matchId': 144321, 'seriesId': 11452, 'seriesName': "ACC Women's Asia Cup Rising Stars 2026", 'matchDesc': '9th Match, Group A', 'matchFormat': 'T20', 'startDate': '1771295400000', 'endDate': '1771308000000', 'state': 'Complete', 'status': 'India A Women won by 7 wkts', 'team1': {'teamId': 383, 'teamName': 'Nepal Women', 'teamSName': 'NEPW', 'imageId': 776189}, 'team2': {'teamId': 440, 'teamName': 'India A Women', 'teamSName': 'INDWA', 'imageId': 776184}, 'venueInfo': {'id': 474, 'ground': 'Terdthai Cricket Ground', 'city': 'Bangkok', 'timezone': '+07:00', 'latitude': '13.756331', 'longitude': '100.501765'}, 'currBatTeamId': 440, 'seriesStartDt': '1770940800000', 'seriesEndDt': '1771891200000', 'isTimeAnnounced': True, 'stateTitle': 'INDWA Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 78, 'wickets': 10, 'overs': 17.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 82, 'wickets': 3, 'overs': 7.5}}}}]}}]}], 'filters': {'matchType': ['International', 'League', 'Domestic', 'Women']}, 'appIndex': {'seoTitle': 'Live Cricket Score - Scorecard and Match Results', 'webURL': 'www.cricbuzz.com/live-cricket-scores/'}, 'responseLastUpdated': '1771314301'}

In [106]:
live_data = response.json()
live_data['typeMatches'][1]['seriesMatches'][0]['seriesAdWrapper']['matches'][0]

{'matchInfo': {'matchId': 125074,
  'seriesId': 10317,
  'seriesName': 'Ranji Trophy Elite 2025-26',
  'matchDesc': '2nd Semi Final',
  'matchFormat': 'TEST',
  'startDate': '1771126200000',
  'endDate': '1771497000000',
  'state': 'In Progress',
  'status': 'Day 3: 2nd Session - Bengal lead by 53 runs',
  'team1': {'teamId': 232,
   'teamName': 'Bengal',
   'teamSName': 'BEN',
   'imageId': 172285},
  'team2': {'teamId': 252,
   'teamName': 'Jammu and Kashmir',
   'teamSName': 'JK',
   'imageId': 172305},
  'venueInfo': {'id': 437,
   'ground': 'Bengal Cricket Academy Ground',
   'city': 'Kalyani',
   'timezone': '+05:30',
   'latitude': '22.9792675',
   'longitude': '88.4416824'},
  'currBatTeamId': 232,
  'seriesStartDt': '1760486400000',
  'seriesEndDt': '1772409600000',
  'isTimeAnnounced': True,
  'stateTitle': 'In Progress'},
 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
    'runs': 328,
    'wickets': 10,
    'overs': 97.1},
   'inngs2': {'inningsId': 3, 'runs': 27, 'wickets': 4, 'overs': 9.6}},
  'team2Score': {'inngs1': {'inningsId': 2,
    'runs': 302,
    'wickets': 10,
    'overs': 76.1}}}}

In [7]:
# teams, scores, wickets, seriesname, matchdate, overs, status, start date,

In [ ]:
# getting final information in human readable form
live_data = response.json()
LiveMatches = []
for matchtype in live_data['typeMatches']:
    for seriesmatch in matchtype['seriesMatches']:
        if 'seriesAdWrapper' in seriesmatch:
            seriesmatch = seriesmatch['seriesAdWrapper']
            Series_ID = seriesmatch['seriesId']
            Series_Name = seriesmatch['seriesName']
            Matches = seriesmatch['matches']
            for match in Matches:
                if 'matchInfo' in match:
                    match_info = match['matchInfo']
                    #match_info
                    matchNum = match_info['matchFormat']
                    s_name = match_info['seriesName']
                    format = match_info['matchFormat']
                    date = match_info['startDate']
                    venue = match_info['venueInfo']['ground']
                    city = match_info['venueInfo']['city']
                    team1 = match_info['team1']['teamName']
                    team2 = match_info['team2']['teamName']
                    status = match_info['status']    
                if 'matchScore' in match:
                    match_score = match['matchScore']

                
                    #match score
                    #team1
                    if 'team1Score' in match_score:
                        if 'runs' in match_score['team1Score']['inngs1']:
                            runst1 = match_score['team1Score']['inngs1']['runs']
                        else:
                            runst1 = '0'
                        if 'overs' in match_score['team1Score']['inngs1']:
                            overst1 = match_score['team1Score']['inngs1']['overs']
                        else:
                            overst1 = '0'
                        if 'wickets' in match_score['team1Score']['inngs1']:
                            wktst1 = match_score['team1Score']['inngs1']['wickets']
                        else:
                            wktst1 = '0'
                    else:
                        runst1, overst1, wktst1 = '0','0','0'
                    #team2
                    if 'team2Score' in match_score:
                        if 'runs' in match_score['team2Score']['inngs1']:
                            runst2 = match_score['team2Score']['inngs1']['runs']
                        else:
                            runst2 = '0'
                        if 'overs' in match_score['team2Score']['inngs1']:
                            overst2 = match_score['team2Score']['inngs1']['overs']
                        else:
                            overst2 = '0'
                        if 'wickets' in match_score['team2Score']['inngs1']:
                            wktst2 = match_score['team2Score']['inngs1']['wickets']
                        else:
                            wktst2 = '0'
                    else:
                        runst2, overst2, wktst2 = '0','0','0'
                else:
                    runst1,runst2,overst1,overst2,wktst1,wktst2 = '0','0','0','0','0','0'
                LiveMatches.append({
                    'series' : s_name,
                    'Format' : format,
                    'Date' : date,
                    'Venue' : f"{venue}, {city}",
                    f"{team1} runs" : runst1,
                    f"{team2} runs" : runst2,
                    f"{team1} Score" : f"{runst1}/{wktst1} in {overst1}",
                    f"{team2} Score" : f"{runst2}/{wktst2} in {overst2}",
                    'Status' : status
                })

In [99]:
# getting final information in human readable form
live_data = response.json()
LiveMatches = []
for matchtype in live_data['typeMatches']:
    for seriesmatch in matchtype['seriesMatches']:
        if 'seriesAdWrapper' in seriesmatch:
            seriesmatch = seriesmatch['seriesAdWrapper']
            Series_ID = seriesmatch['seriesId']
            Series_Name = seriesmatch['seriesName']
            Matches = seriesmatch['matches']
            for match in Matches:
                if 'matchInfo' in match:
                    match_info = match['matchInfo']
                    #match_info
                    s_name = match_info['seriesName']
                    format = match_info['matchFormat']
                    date = match_info['startDate']
                    venue = match_info['venueInfo']['ground']
                    city = match_info['venueInfo']['city']
                    team1 = match_info['team1']['teamName']
                    team2 = match_info['team2']['teamName']
                    status = match_info['status']    
                if 'matchScore' in match:
                    match_score = match['matchScore']

                
                    #match score
                    #team1
                    if 'team1Score' in match_score:
                        if 'runs' in match_score['team1Score']['inngs1']:
                            runst1 = match_score['team1Score']['inngs1']['runs']
                        else:
                            runst1 = '0'
                        if 'overs' in match_score['team1Score']['inngs1']:
                            overst1 = match_score['team1Score']['inngs1']['overs']
                        else:
                            overst1 = '0'
                        if 'wickets' in match_score['team1Score']['inngs1']:
                            wktst1 = match_score['team1Score']['inngs1']['wickets']
                        else:
                            wktst1 = '0'
                    else:
                        runst1, overst1, wktst1 = '0','0','0'
                    #team2
                    if 'team2Score' in match_score:
                        if 'runs' in match_score['team2Score']['inngs1']:
                            runst2 = match_score['team2Score']['inngs1']['runs']
                        else:
                            runst2 = '0'
                        if 'overs' in match_score['team2Score']['inngs1']:
                            overst2 = match_score['team2Score']['inngs1']['overs']
                        else:
                            overst2 = '0'
                        if 'wickets' in match_score['team2Score']['inngs1']:
                            wktst2 = match_score['team2Score']['inngs1']['wickets']
                        else:
                            wktst2 = '0'
                    else:
                        runst2, overst2, wktst2 = '0','0','0'
                else:
                    runst1,runst2,overst1,overst2,wktst1,wktst2 = '0','0','0','0','0','0'
                LiveMatches.append({
                    f"{team1} runs" : runst1,
                    f"{team2} runs" : runst2,
                    f"{team1} wickets" : wktst1,
                    f"{team2} wickets" : wktst2
                })

In [100]:
LiveMatches

[{'Canada runs': '0',
  'New Zealand runs': '0',
  'Canada wickets': '0',
  'New Zealand wickets': '0'},
 {'Bengal runs': 328,
  'Jammu and Kashmir runs': 281,
  'Bengal wickets': 10,
  'Jammu and Kashmir wickets': 8},
 {'Karnataka runs': 734,
  'Uttarakhand runs': '0',
  'Karnataka wickets': 9,
  'Uttarakhand wickets': '0'},
 {'Central Districts runs': 276,
  'Canterbury runs': 234,
  'Central Districts wickets': 8,
  'Canterbury wickets': 9},
 {'Otago runs': 158,
  'Auckland runs': 161,
  'Otago wickets': 10,
  'Auckland wickets': 4},
 {'Victoria runs': 431,
  'Western Australia runs': 15,
  'Victoria wickets': 9,
  'Western Australia wickets': '0'},
 {'Tasmania runs': 136,
  'New South Wales runs': 204,
  'Tasmania wickets': 10,
  'New South Wales wickets': 3},
 {'Queensland runs': 185,
  'South Australia runs': 214,
  'Queensland wickets': 10,
  'South Australia wickets': 10},
 {'Nepal Women runs': 78,
  'India A Women runs': 82,
  'Nepal Women wickets': 10,
  'India A Women wickets': 3}]

In [101]:
data = LiveMatches  # your list of dicts

def extract_match(row):
    # find dynamic team run keys
    run_keys = [k for k in row.keys() if k.endswith(" runs")]

    team1 = run_keys[0].replace(" runs", "")
    team2 = run_keys[1].replace(" runs", "")

    team1_runs = int(row[run_keys[0]])
    team2_runs = int(row[run_keys[1]])

    team1_score = row.get(f"{team1} Score")
    team2_score = row.get(f"{team2} Score")

    return (
        row['series'],
        row['Format'],
        int(row['Date']),
        row['Venue'],
        team1,
        team2,
        team1_runs,
        team2_runs,
        team1_score,
        team2_score,
        row['Status']
    )

In [65]:
LiveMatches

[{'Bengal runs': 328,
  'Jammu and Kashmir runs': 198,
  'Bengal wickest': 10,
  'Jammu and Kashmir wickets': 5},
 {'Karnataka runs': 689,
  'Uttarakhand runs': '0',
  'Karnataka wickest': 6,
  'Uttarakhand wickets': '0'},
 {'Central Districts runs': 276,
  'Canterbury runs': 102,
  'Central Districts wickest': 8,
  'Canterbury wickets': 5},
 {'Otago runs': 158,
  'Auckland runs': 161,
  'Otago wickest': 10,
  'Auckland wickets': 4},
 {'Tasmania runs': 136,
  'New South Wales runs': 138,
  'Tasmania wickest': 10,
  'New South Wales wickets': 2},
 {'Queensland runs': 185,
  'South Australia runs': 174,
  'Queensland wickest': 10,
  'South Australia wickets': 7},
 {'Victoria runs': 380,
  'Western Australia runs': '0',
  'Victoria wickest': 8,
  'Western Australia wickets': '0'},
 {'Nepal Women runs': 62,
  'India A Women runs': '0',
  'Nepal Women wickest': 7,
  'India A Women wickets': '0'}]

In [97]:
data = LiveMatches  # your list of dicts

def extract_match(row):
    # find dynamic team run keys
    run_keys = [k for k in row.keys() if k.endswith(" runs")]

    team1 = run_keys[0].replace(" runs", "")
    team2 = run_keys[1].replace(" runs", "")

    team1_runs = int(row[run_keys[0]])
    team2_runs = int(row[run_keys[1]])

    team1_wickets = row.get(f"{team1} wickets")
    team2_wickets = row.get(f"{team2} wickets")

    return (
        team1_runs,
        team2_runs,
        team1_wickets,
        team2_wickets
    )

In [15]:
# recent matches

In [276]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "cfdf9c6205msh90e2dbc4b627d8cp118b91jsn3cd37e7c3174",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'message': 'You have exceeded the MONTHLY quota for Requests on your current plan, BASIC. Upgrade your plan at https://rapidapi.com/cricketapilive/api/cricbuzz-cricket'}

In [11]:
data_recent = response.json()

In [64]:
# data_recent

In [12]:
# getting readable information about recent matches
data_recent = response.json()
RecentMatches = []
for matchtype in data_recent['typeMatches']:
    for seriesmatch in matchtype['seriesMatches']:
        if 'seriesAdWrapper' in seriesmatch:
            seriesmatch = seriesmatch['seriesAdWrapper']
            Series_ID = seriesmatch['seriesId']
            Series_Name = seriesmatch['seriesName']
            Matches = seriesmatch['matches']
            for match in Matches:
                if 'matchScore' in match:
                    match_info = match['matchInfo']
                    match_score = match['matchScore']
                #match_info
                s_name = match_info['seriesName']
                format = match_info['matchFormat']
                date = match_info['startDate']
                venue = match_info['venueInfo']['ground']
                city = match_info['venueInfo']['city']
                team1 = match_info['team1']['teamName']
                team2 = match_info['team2']['teamName']
                status = match_info['status']
                #match score
                #team1
                if 'team1Score' in match_score:
                    if 'runs' in match_score['team1Score']['inngs1']:
                        runst1 = match_score['team1Score']['inngs1']['runs']
                    else:
                        runst1 = '0'
                    if 'overs' in match_score['team1Score']['inngs1']:
                        overst1 = match_score['team1Score']['inngs1']['overs']
                    else:
                        overst1 = '0'
                    if 'wickets' in match_score['team1Score']['inngs1']:
                        wktst1 = match_score['team1Score']['inngs1']['wickets']
                    else:
                        wktst1 = '0'
                #team2
                if 'team2Score' in match_score:
                    if 'runs' in match_score['team2Score']['inngs1']:
                        runst2 = match_score['team2Score']['inngs1']['runs']
                    else:
                        runst2 = '0'
                    if 'overs' in match_score['team2Score']['inngs1']:
                        overst2 = match_score['team2Score']['inngs1']['overs']
                    else:
                        overst2 = '0'
                    if 'wickets' in match_score['team2Score']['inngs1']:
                        wktst2 = match_score['team2Score']['inngs1']['wickets']
                    else:
                        wktst2 = '0'
                     
                    
                RecentMatches.append({
                        'series' : s_name,
                        'Format' : format,
                        'Date' : date,
                        'Venue' : f"{venue}, {city}",
                        f"{team1} score" : runst1,
                        f"{team2} score" : runst2,
                        'Team1 Score' : f"{runst1}/{wktst1} in {overst1}",
                        'Team2 Score' : f"{runst2}/{wktst2} in {overst2}"
                    })

In [63]:

#RecentMatches # we have a list of all recent matches where each element of the list is a dict.

In [89]:
# upcoming matches
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/upcoming"

headers = {
	"x-rapidapi-key": "cfdf9c6205msh90e2dbc4b627d8cp118b91jsn3cd37e7c3174",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'typeMatches': [{'matchType': 'International', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matches': [{'matchInfo': {'matchId': 139186, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '24th Match, Group D', 'matchFormat': 'T20', 'startDate': '1771075800000', 'endDate': '1771088400000', 'state': 'Preview', 'status': 'Match starts at Feb 14, 13:30 GMT', 'team1': {'teamId': 13, 'teamName': 'New Zealand', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'id': 50, 'ground': 'Narendra Modi Stadium', 'city': 'Ahmedabad', 'timezone': '+05:30', 'latitude': '23.091785', 'longitude': '72.597465'}, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'Preview', 'isFantasyEnabled': True}}, {'matchInfo': {'matchId': 139194, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '25th Match, Group C', 'matchFormat': 'T20', 'startDate': '1771133400000', 'endDate': '1771146000000', 'state': 'Preview', 'status': 'Match starts at Feb 15, 05:30 GMT', 'team1': {'teamId': 10, 'teamName': 'West Indies', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 72, 'teamName': 'Nepal', 'teamSName': 'NEP', 'imageId': 776331}, 'venueInfo': {'id': 81, 'ground': 'Wankhede Stadium', 'city': 'Mumbai', 'timezone': '+05:30', 'latitude': '18.938956', 'longitude': '72.825719'}, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'Preview'}}]}}, {'seriesAdWrapper': {'seriesId': 11528, 'seriesName': 'Bahrain tour of Qatar 2026', 'matches': [{'matchInfo': {'matchId': 146883, 'seriesId': 11528, 'seriesName': 'Bahrain tour of Qatar 2026', 'matchDesc': '4th T20I', 'matchFormat': 'T20', 'startDate': '1771074000000', 'endDate': '1771086600000', 'state': 'Preview', 'status': 'Match starts at Feb 14, 13:00 GMT', 'team1': {'teamId': 525, 'teamName': 'Qatar', 'teamSName': 'QAT', 'imageId': 172575}, 'team2': {'teamId': 543, 'teamName': 'Bahrain', 'teamSName': 'BHR', 'imageId': 172594}, 'venueInfo': {'id': 582, 'ground': 'West End Park International Cricket Stadium', 'city': 'Doha', 'timezone': '+03:00', 'latitude': '25.189391', 'longitude': '51.460211'}, 'seriesStartDt': '1770681600000', 'seriesEndDt': '1771286400000', 'isTimeAnnounced': True, 'stateTitle': 'Preview'}}]}}]}, {'matchType': 'Domestic', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26', 'matches': [{'matchInfo': {'matchId': 125074, 'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26', 'matchDesc': '2nd Semi Final', 'matchFormat': 'TEST', 'startDate': '1771126200000', 'endDate': '1771497000000', 'state': 'Preview', 'status': 'Match starts at Feb 15, 03:30 GMT', 'team1': {'teamId': 252, 'teamName': 'Jammu and Kashmir', 'teamSName': 'JK', 'imageId': 172305}, 'team2': {'teamId': 232, 'teamName': 'Bengal', 'teamSName': 'BEN', 'imageId': 172285}, 'venueInfo': {'id': 437, 'ground': 'Bengal Cricket Academy Ground', 'city': 'Kalyani', 'timezone': '+05:30', 'latitude': '22.9792675', 'longitude': '88.4416824'}, 'seriesStartDt': '1760486400000', 'seriesEndDt': '1772409600000', 'isTimeAnnounced': True, 'stateTitle': 'Preview'}}, {'matchInfo': {'matchId': 125069, 'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26', 'matchDesc': '1st Semi Final', 'matchFormat': 'TEST', 'startDate': '1771128000000', 'endDate': '1771498800000', 'state': 'Preview', 'status': 'Match starts at Feb 15, 04:00 GMT', 'team1': {'teamId': 467, 'teamName': 'Uttarakhand', 'teamSName': 'UTK', 'imageId': 172515}, 'team2': {'teamId': 128, 'teamName': 'Karnataka', 'teamSName': 'KAR', 'imageId': 776345}, 'venueInfo': {'id': 485, 'ground': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'city': 'Lucknow', 'timezone': '+05:30', 'latitude': '26.846694', 'longitude': '80.946166'}, 'seriesStartDt': '1760486400000', 'seriesEndDt': '1772409600000', 'isTimeAnnounced': True, 'stateTitle': 'Preview'}}]}}]}, {'matchType': 'Women', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11452, 'seriesName': "ACC Women's Asia Cup Rising Stars 2026", 'matches': [{'matchInfo': {'matchId': 144287, 'seriesId': 11452, 'seriesName': "ACC Women's Asia Cup Rising Stars 2026", 'matchDesc': '5th Match, Group A', 'matchFormat': 'T20', 'startDate': '1771122600000', 'endDate': '1771135200000', 'state': 'Preview', 'status': 'Match starts at Feb 15, 02:30 GMT', 'team1': {'teamId': 449, 'teamName': 'United Arab Emirates Women', 'teamSName': 'UAEW', 'imageId': 776246}, 'team2': {'teamId': 383, 'teamName': 'Nepal Women', 'teamSName': 'NEPW', 'imageId': 776189}, 'venueInfo': {'id': 474, 'ground': 'Terdthai Cricket Ground', 'city': 'Bangkok', 'timezone': '+07:00', 'latitude': '13.756331', 'longitude': '100.501765'}, 'seriesStartDt': '1770940800000', 'seriesEndDt': '1771891200000', 'isTimeAnnounced': True, 'stateTitle': 'Preview'}}, {'matchInfo': {'matchId': 144298, 'seriesId': 11452, 'seriesName': "ACC Women's Asia Cup Rising Stars 2026", 'matchDesc': '6th Match, Group A', 'matchFormat': 'T20', 'startDate': '1771138800000', 'endDate': '1771151400000', 'state': 'Preview', 'status': 'Match starts at Feb 15, 07:00 GMT', 'team1': {'teamId': 440, 'teamName': 'India A Women', 'teamSName': 'INDWA', 'imageId': 776184}, 'team2': {'teamId': 1552, 'teamName': 'Pakistan A Women', 'teamSName': 'PAKWA', 'imageId': 776324}, 'venueInfo': {'id': 474, 'ground': 'Terdthai Cricket Ground', 'city': 'Bangkok', 'timezone': '+07:00', 'latitude': '13.756331', 'longitude': '100.501765'}, 'seriesStartDt': '1770940800000', 'seriesEndDt': '1771891200000', 'isTimeAnnounced': True, 'stateTitle': 'Preview'}}]}}]}], 'filters': {'matchType': ['International', 'League', 'Domestic', 'Women']}, 'appIndex': {'seoTitle': 'Live Cricket Score - Scorecard and Match Results', 'webURL': 'www.cricbuzz.com/live-cricket-scores/'}, 'responseLastUpdated': '1771059894'}

In [90]:
data_upcoming = response.json()

In [91]:
# getting readable information about recent matches
data_upcoming = response.json()
UpcomingMatches = []
for matchtype in data_upcoming['typeMatches']:
    for seriesmatch in matchtype['seriesMatches']:
        if 'seriesAdWrapper' in seriesmatch:
            seriesmatch = seriesmatch['seriesAdWrapper']
            Series_ID = seriesmatch['seriesId']
            Series_Name = seriesmatch['seriesName']
            Matches = seriesmatch['matches']
            for match in Matches:
                match_info = match['matchInfo']
                #match_info
                s_name = match_info['seriesName']
                format = match_info['matchFormat']
                date = match_info['startDate']
                venue = match_info['venueInfo']['ground']
                city = match_info['venueInfo']['city']
                team1 = match_info['team1']['teamName']
                team2 = match_info['team2']['teamName']
                status = match_info['status']
                
                UpcomingMatches.append({
                        'series' : s_name,
                        'Format' : format,
                        'Date' : date,
                        'team1' : team1,
                        'team2' : team2,
                        'Venue' : f"{venue}, {city}"

                    })

In [61]:
# UpcomingMatches

In [93]:
# match-list
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "cfdf9c6205msh90e2dbc4b627d8cp118b91jsn3cd37e7c3174",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'typeMatches': [{'matchType': 'International', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matches': [{'matchInfo': {'matchId': 139142, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '20th Match, Group D', 'matchFormat': 'T20', 'startDate': '1770975000000', 'endDate': '1770987600000', 'state': 'Complete', 'status': 'United Arab Emirates won by 5 wkts', 'team1': {'teamId': 26, 'teamName': 'Canada', 'teamSName': 'CAN', 'imageId': 776227}, 'team2': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 776242}, 'venueInfo': {'id': 51, 'ground': 'Arun Jaitley Stadium', 'city': 'Delhi', 'timezone': '+05:30', 'latitude': '28.637891', 'longitude': '77.243073'}, 'currBatTeamId': 7, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'UAE Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 150, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 151, 'wickets': 5, 'overs': 19.4}}}}, {'matchInfo': {'matchId': 139129, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '18th Match, Group A', 'matchFormat': 'T20', 'startDate': '1770903000000', 'endDate': '1770915600000', 'state': 'Complete', 'status': 'India won by 93 runs', 'team1': {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 161, 'teamName': 'Namibia', 'teamSName': 'NAM', 'imageId': 776326}, 'venueInfo': {'id': 51, 'ground': 'Arun Jaitley Stadium', 'city': 'Delhi', 'timezone': '+05:30', 'latitude': '28.637891', 'longitude': '77.243073'}, 'currBatTeamId': 2, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'IND Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 209, 'wickets': 9, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 116, 'wickets': 10, 'overs': 18.2}}}}, {'matchInfo': {'matchId': 139093, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '14th Match, Group B', 'matchFormat': 'T20', 'startDate': '1770802200000', 'endDate': '1770814800000', 'state': 'Complete', 'status': 'Australia won by 67 runs', 'team1': {'teamId': 4, 'teamName': 'Australia', 'teamSName': 'AUS', 'imageId': 776202}, 'team2': {'teamId': 27, 'teamName': 'Ireland', 'teamSName': 'IRE', 'imageId': 839366}, 'venueInfo': {'id': 15, 'ground': 'R.Premadasa Stadium', 'city': 'Colombo', 'timezone': '+05:30', 'latitude': '6.939966', 'longitude': '79.872222'}, 'currBatTeamId': 4, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'AUS Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 182, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 115, 'wickets': 10, 'overs': 16.5}}}}, {'matchInfo': {'matchId': 139084, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '13th Match, Group D', 'matchFormat': 'T20', 'startDate': '1770787800000', 'endDate': '1770800400000', 'state': 'Complete', 'status': 'Match tied and 1st Super over tied (SA won 2nd Super Over)', 'team1': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 776287}, 'team2': {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 776177}, 'venueInfo': {'id': 50, 'ground': 'Narendra Modi Stadium', 'city': 'Ahmedabad', 'timezone': '+05:30', 'latitude': '23.091785', 'longitude': '72.597465'}, 'currBatTeamId': 11, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'RSA Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 187, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 187, 'wickets': 10, 'overs': 19.4}}}}, {'matchInfo': {'matchId': 139007, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '6th Match, Group B', 'matchFormat': 'T20', 'startDate': '1770557400000', 'endDate': '1770570000000', 'state': 'Complete', 'status': 'Sri Lanka won by 20 runs', 'team1': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 776254}, 'team2': {'teamId': 27, 'teamName': 'Ireland', 'teamSName': 'IRE', 'imageId': 839366}, 'venueInfo': {'id': 15, 'ground': 'R.Premadasa Stadium', 'city': 'Colombo', 'timezone': '+05:30', 'latitude': '6.939966', 'longitude': '79.872222'}, 'currBatTeamId': 5, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'SL Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 163, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 143, 'wickets': 10, 'overs': 19.5}}}}, {'matchInfo': {'matchId': 139140, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '19th Match, Group B', 'matchFormat': 'T20', 'startDate': '1770960600000', 'endDate': '1770973200000', 'state': 'Complete', 'status': 'Zimbabwe won by 23 runs', 'team1': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 776198}, 'team2': {'teamId': 4, 'teamName': 'Australia', 'teamSName': 'AUS', 'imageId': 776202}, 'venueInfo': {'id': 15, 'ground': 'R.Premadasa Stadium', 'city': 'Colombo', 'timezone': '+05:30', 'latitude': '6.939966', 'longitude': '79.872222'}, 'currBatTeamId': 12, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'ZIM Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 169, 'wickets': 2, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 146, 'wickets': 10, 'overs': 19.3}}}}, {'matchInfo': {'matchId': 139118, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '17th Match, Group C', 'matchFormat': 'T20', 'startDate': '1770888600000', 'endDate': '1770901200000', 'state': 'Complete', 'status': 'Italy won by 10 wkts', 'team1': {'teamId': 72, 'teamName': 'Nepal', 'teamSName': 'NEP', 'imageId': 776331}, 'team2': {'teamId': 527, 'teamName': 'Italy', 'teamSName': 'ITA', 'imageId': 776295}, 'venueInfo': {'id': 81, 'ground': 'Wankhede Stadium', 'city': 'Mumbai', 'timezone': '+05:30', 'latitude': '18.938956', 'longitude': '72.825719'}, 'currBatTeamId': 527, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'ITA Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 123, 'wickets': 10, 'overs': 19.3}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 124, 'overs': 12.4}}}}, {'matchInfo': {'matchId': 139018, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '7th Match, Group C', 'matchFormat': 'T20', 'startDate': '1770615000000', 'endDate': '1770627600000', 'state': 'Complete', 'status': 'Scotland won by 73 runs', 'team1': {'teamId': 23, 'teamName': 'Scotland', 'teamSName': 'SCO', 'imageId': 776280}, 'team2': {'teamId': 527, 'teamName': 'Italy', 'teamSName': 'ITA', 'imageId': 776295}, 'venueInfo': {'id': 31, 'ground': 'Eden Gardens', 'city': 'Kolkata', 'timezone': '+05:30', 'latitude': '22.564527', 'longitude': '88.343247'}, 'currBatTeamId': 23, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'SCO Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 207, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 134, 'wickets': 10, 'overs': 16.4}}}}, {'matchInfo': {'matchId': 138963, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '2nd Match, Group C', 'matchFormat': 'T20', 'startDate': '1770456600000', 'endDate': '1770469200000', 'state': 'Complete', 'status': 'West Indies won by 35 runs', 'team1': {'teamId': 10, 'teamName': 'West Indies', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 23, 'teamName': 'Scotland', 'teamSName': 'SCO', 'imageId': 776280}, 'venueInfo': {'id': 31, 'ground': 'Eden Gardens', 'city': 'Kolkata', 'timezone': '+05:30', 'latitude': '22.564527', 'longitude': '88.343247'}, 'currBatTeamId': 10, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'WI Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 182, 'wickets': 5, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 147, 'wickets': 10, 'overs': 18.5}}}}, {'matchInfo': {'matchId': 139104, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '15th Match, Group C', 'matchFormat': 'T20', 'startDate': '1770816600000', 'endDate': '1770829200000', 'state': 'Complete', 'status': 'West Indies won by 30 runs', 'team1': {'teamId': 10, 'teamName': 'West Indies', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 776237}, 'venueInfo': {'id': 81, 'ground': 'Wankhede Stadium', 'city': 'Mumbai', 'timezone': '+05:30', 'latitude': '18.938956', 'longitude': '72.825719'}, 'currBatTeamId': 10, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'WI Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 196, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 166, 'wickets': 10, 'overs': 18.6}}}}, {'matchInfo': {'matchId': 139153, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '21st Match, Group A', 'matchFormat': 'T20', 'startDate': '1770989400000', 'endDate': '1771002000000', 'state': 'Complete', 'status': 'United States of America won by 93 runs', 'team1': {'teamId': 15, 'teamName': 'United States of America', 'teamSName': 'USA', 'imageId': 776186}, 'team2': {'teamId': 24, 'teamName': 'Netherlands', 'teamSName': 'NED', 'imageId': 776335}, 'venueInfo': {'id': 11, 'ground': 'MA Chidambaram Stadium', 'city': 'Chennai', 'timezone': '+05:30', 'latitude': '13.06282', 'longitude': '80.279274'}, 'currBatTeamId': 15, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'USA Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 196, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 103, 'wickets': 10, 'overs': 15.5}}}}, {'matchInfo': {'matchId': 139040, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '9th Match, Group D', 'matchFormat': 'T20', 'startDate': '1770643800000', 'endDate': '1770656400000', 'state': 'Complete', 'status': 'South Africa won by 57 runs', 'team1': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 776287}, 'team2': {'teamId': 26, 'teamName': 'Canada', 'teamSName': 'CAN', 'imageId': 776227}, 'venueInfo': {'id': 50, 'ground': 'Narendra Modi Stadium', 'city': 'Ahmedabad', 'timezone': '+05:30', 'latitude': '23.091785', 'longitude': '72.597465'}, 'currBatTeamId': 11, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'RSA Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 213, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 156, 'wickets': 8, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 139073, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '12th Match, Group A', 'matchFormat': 'T20', 'startDate': '1770730200000', 'endDate': '1770742800000', 'state': 'Complete', 'status': 'Pakistan won by 32 runs', 'team1': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 776308}, 'team2': {'teamId': 15, 'teamName': 'United States of America', 'teamSName': 'USA', 'imageId': 776186}, 'venueInfo': {'id': 14, 'ground': 'Sinhalese Sports Club', 'city': 'Colombo', 'timezone': '+05:30', 'latitude': '6.905929', 'longitude': '79.869403'}, 'currBatTeamId': 3, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'PAK Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 190, 'wickets': 9, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 158, 'wickets': 8, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 138953, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '1st Match, Group A', 'matchFormat': 'T20', 'startDate': '1770442200000', 'endDate': '1770454800000', 'state': 'Complete', 'status': 'Pakistan won by 3 wkts', 'team1': {'teamId': 24, 'teamName': 'Netherlands', 'teamSName': 'NED', 'imageId': 776335}, 'team2': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 776308}, 'venueInfo': {'id': 14, 'ground': 'Sinhalese Sports Club', 'city': 'Colombo', 'timezone': '+05:30', 'latitude': '6.905929', 'longitude': '79.869403'}, 'currBatTeamId': 3, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'PAK Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 147, 'wickets': 10, 'overs': 19.5}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 148, 'wickets': 7, 'overs': 19.3}}}}, {'matchInfo': {'matchId': 139051, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '10th Match, Group A', 'matchFormat': 'T20', 'startDate': '1770701400000', 'endDate': '1770714000000', 'state': 'Complete', 'status': 'Netherlands won by 7 wkts', 'team1': {'teamId': 161, 'teamName': 'Namibia', 'teamSName': 'NAM', 'imageId': 776326}, 'team2': {'teamId': 24, 'teamName': 'Netherlands', 'teamSName': 'NED', 'imageId': 776335}, 'venueInfo': {'id': 51, 'ground': 'Arun Jaitley Stadium', 'city': 'Delhi', 'timezone': '+05:30', 'latitude': '28.637891', 'longitude': '77.243073'}, 'currBatTeamId': 24, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'NED Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 156, 'wickets': 8, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 159, 'wickets': 3, 'overs': 17.6}}}}, {'matchInfo': {'matchId': 139115, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '16th Match, Group B', 'matchFormat': 'T20', 'startDate': '1770874200000', 'endDate': '1770886800000', 'state': 'Complete', 'status': 'Sri Lanka won by 105 runs', 'team1': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 776254}, 'team2': {'teamId': 304, 'teamName': 'Oman', 'teamSName': 'OMAN', 'imageId': 776328}, 'venueInfo': {'id': 254, 'ground': 'Pallekele International Cricket Stadium', 'city': 'Pallekele', 'timezone': '+05:30', 'latitude': '7.280691', 'longitude': '80.722493'}, 'currBatTeamId': 5, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'SL Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 225, 'wickets': 5, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 120, 'wickets': 9, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 139062, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '11th Match, Group D', 'matchFormat': 'T20', 'startDate': '1770715800000', 'endDate': '1770728400000', 'state': 'Complete', 'status': 'New Zealand won by 10 wkts', 'team1': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 776242}, 'team2': {'teamId': 13, 'teamName': 'New Zealand', 'teamSName': 'NZ', 'imageId': 776333}, 'venueInfo': {'id': 11, 'ground': 'MA Chidambaram Stadium', 'city': 'Chennai', 'timezone': '+05:30', 'latitude': '13.06282', 'longitude': '80.279274'}, 'currBatTeamId': 13, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'NZ Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 173, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 175, 'overs': 15.2}}}}, {'matchInfo': {'matchId': 138996, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '5th Match, Group C', 'matchFormat': 'T20', 'startDate': '1770543000000', 'endDate': '1770555600000', 'state': 'Complete', 'status': 'England won by 4 runs', 'team1': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 776237}, 'team2': {'teamId': 72, 'teamName': 'Nepal', 'teamSName': 'NEP', 'imageId': 776331}, 'venueInfo': {'id': 81, 'ground': 'Wankhede Stadium', 'city': 'Mumbai', 'timezone': '+05:30', 'latitude': '18.938956', 'longitude': '72.825719'}, 'currBatTeamId': 9, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'ENG Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 184, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 180, 'wickets': 6, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 138985, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '4th Match, Group D', 'matchFormat': 'T20', 'startDate': '1770528600000', 'endDate': '1770541200000', 'state': 'Complete', 'status': 'New Zealand won by 5 wkts', 'team1': {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 776177}, 'team2': {'teamId': 13, 'teamName': 'New Zealand', 'teamSName': 'NZ', 'imageId': 776333}, 'venueInfo': {'id': 11, 'ground': 'MA Chidambaram Stadium', 'city': 'Chennai', 'timezone': '+05:30', 'latitude': '13.06282', 'longitude': '80.279274'}, 'currBatTeamId': 13, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'NZ Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 182, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 183, 'wickets': 5, 'overs': 17.5}}}}, {'matchInfo': {'matchId': 138974, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '3rd Match, Group A', 'matchFormat': 'T20', 'startDate': '1770471000000', 'endDate': '1770483600000', 'state': 'Complete', 'status': 'India won by 29 runs', 'team1': {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 15, 'teamName': 'United States of America', 'teamSName': 'USA', 'imageId': 776186}, 'venueInfo': {'id': 81, 'ground': 'Wankhede Stadium', 'city': 'Mumbai', 'timezone': '+05:30', 'latitude': '18.938956', 'longitude': '72.825719'}, 'currBatTeamId': 2, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'IND Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 161, 'wickets': 9, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 132, 'wickets': 8, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 139029, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '8th Match, Group B', 'matchFormat': 'T20', 'startDate': '1770629400000', 'endDate': '1770642000000', 'state': 'Complete', 'status': 'Zimbabwe won by 8 wkts', 'team1': {'teamId': 304, 'teamName': 'Oman', 'teamSName': 'OMAN', 'imageId': 776328}, 'team2': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 776198}, 'venueInfo': {'id': 14, 'ground': 'Sinhalese Sports Club', 'city': 'Colombo', 'timezone': '+05:30', 'latitude': '6.905929', 'longitude': '79.869403'}, 'currBatTeamId': 12, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'ZIM Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 

In [96]:
match_list = response.json()

In [62]:
# match_list

In [99]:
# stats/get-records
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats/0"

querystring = {"statsType":"mostRuns"}

headers = {
	"x-rapidapi-key": "cfdf9c6205msh90e2dbc4b627d8cp118b91jsn3cd37e7c3174",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'filter': {'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'}, {'matchTypeId': '2', 'matchTypeDesc': 'odi'}, {'matchTypeId': '3', 'matchTypeDesc': 't20i'}], 'team': [{'id': '2', 'teamShortName': 'IND'}, {'id': '27', 'teamShortName': 'IRE'}, {'id': '3', 'teamShortName': 'PAK'}, {'id': '4', 'teamShortName': 'AUS'}, {'id': '5', 'teamShortName': 'SL'}, {'id': '6', 'teamShortName': 'BAN'}, {'id': '9', 'teamShortName': 'ENG'}, {'id': '10', 'teamShortName': 'WI'}, {'id': '11', 'teamShortName': 'RSA'}, {'id': '12', 'teamShortName': 'ZIM'}, {'id': '13', 'teamShortName': 'NZ'}, {'id': '96', 'teamShortName': 'AFG'}], 'selectedMatchType': 'test'}, 'headers': ['Batter', 'M', 'I', 'R', 'Avg'], 'values': [{'values': ['25', 'Tendulkar', '200', '329', '15921', '53.79']}, {'values': ['8019', 'Root', '163', '298', '13943', '51.07']}, {'values': ['38', 'R Ponting', '168', '287', '13378', '51.85']}, {'values': ['213', 'Kallis', '166', '280', '13289', '55.37']}, {'values': ['27', 'Dravid', '164', '286', '13288', '52.31']}, {'values': ['488', 'Cook', '161', '291', '12472', '45.35']}, {'values': ['104', 'Sangakkara', '134', '233', '12400', '57.14']}, {'values': ['240', 'B Lara', '131', '232', '11953', '52.89']}, {'values': ['244', 'Chanderpaul', '164', '280', '11867', '51.37']}, {'values': ['101', 'Mahela', '149', '252', '11814', '49.85']}, {'values': ['4672', 'A Border', '156', '265', '11174', '50.56']}, {'values': ['4712', 'S Waugh', '168', '260', '10927', '51.06']}, {'values': ['2250', 'Steven Smith', '123', '220', '10763', '56.06']}, {'values': ['3817', 'S Gavaskar', '125', '214', '10122', '51.12']}, {'values': ['130', 'Younis Khan', '118', '213', '10099', '52.06']}, {'values': ['6326', 'Williamson', '108', '192', '9461', '54.69']}, {'values': ['314', 'Amla', '124', '215', '9282', '46.64']}, {'values': ['207', 'Graeme Smith', '117', '205', '9265', '48.26']}, {'values': ['1413', 'Virat Kohli', '123', '210', '9230', '46.85']}, {'values': ['5308', 'G Gooch', '118', '215', '8900', '42.58']}], 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com', 'webURL': 'www.cricbuzz.com'}}

In [100]:
records_data = response.json()

In [60]:
# records_data

In [166]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/6635"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'id': '6635', 'bat': 'Left Handed Bat', 'bowl': 'Right-arm offbreak', 'name': 'Usman Khawaja', 'nickName': 'Khawaja', 'height': '1.75 m ', 'role': 'Batsman', 'birthPlace': 'Islamabad, Pakistan ', 'intlTeam': 'Australia', 'teams': 'Australia, New South Wales, Derbyshire, Cricket Australia Chairmans XI, Sydney Thunder, Queensland, Australians, Australia A, Lancashire, Rising Pune Supergiant, Glamorgan, Islamabad United, Brisbane Heat', 'DoB': 'December 18, 1986 (39 years)', 'image': 'http://i.cricketcb.com/stats/img/faceImages/6635.jpg', 'bio': "Ricky Ponting's injury at Sydney in 2011, opened the doors for the first Muslim cricketer to represent Australia at the highest level. A qualified pilot, the highs of this achievement were unparalleled. Having moved to Australia as a kid, Usman Khawaja with the bat in his hands was identified pretty early as the boy wonder.  <br/>  <br/> Honing his skills at the Valley District Cricket Club, Usman made it to the Australian under-19 squad for the 2006 World Cup. He featured in 4 games and hunted down 140 runs making an impression with his poise at the crease and crafty technique. A backlift which comes down on the ball like butter on bread, Khawaja loves to cut and pull.  <br/>  <br/> Following his debut series,  Usman travelled to Sri Lanka and South Africa without much of a success. The year of 2011 ended with a home series against the Kiwis and that also remained a low key affair for the then New batsman.  <br/>  <br/> He was dropped post that and his next tryst with the baggy green happened during the Ashes in England in 2013 after a layoff of almost 18 months. In 3 Tests, he managed only fifty and another exile from Test cricket was handed out.  <br/>  <br/> In the meanwhile, Usman had made his ODI debut at the beginning of 2013 and met a similar fate as he was dropped after three unsuccessful outings in colored clothing. Another big move that Usman had made was the move from NSW to Queensland in 2012. <br/>  <br/> His debut season at Queensland yielded 438 runs from 6 games and it got better in the succeeding season as he riled up 551 runs at an average of 50.09 in 8 games. But then occurred a career-threatening injury. He tore his ACL (Anterior Cruciate Ligament) on his left knee and was out of cricket for the next 9 months.  <br/>  <br/> Khawaja who was now aware and accustomed to the waiting game built on his patience on the sidelines. He returned to the 2015-16 season with a bang. A ton on his return game for Sydney Thunder in December 2015 made the world aware of the destruction that he can be. The T20I debut was just a mere formal announcement when the touring Indians whitewashed Australia 0-3. <br/>  <br/> All this was just before his Test comeback. Usman went onto become a permanent member of the Test team post that barring the tour to India for which he was dropped unceremoniously. But he returned for the Ashes 2017-18 and scored vital knocks over the course of the series. His couple of tons in BBL 05 ensured Sydney Thunder,  the constant wooden Spooner shocked the cricketing fraternity and ended up winning the title.  <br/>  <br/> With the bans of Steve Smith and David Warner in 2018, Khawaja was thrust with the responsibility of being Australia's premier batsman in Tests and he rose to the responsibility with elan. A marathon match-saving knock in UAE was the start of a dream run for the stylish left-hander who also stamped his class during the limited-overs tour of India in 2019. <br/>  <br/> His prolific run in that ODI series and the succeeding one against Pakistan in the UAE helped Khawaja book his maiden World Cup call-up in 2019. A hamstring injury early in the tournament, however, cut his campaign short. He recovered in time for the following Ashes series but a poor run of form saw him dropped from the side and it wouldn't be until 2022 that he'd make a comeback to the international setup.  <br/>  <br/> After a 3-year hiatus, Khawaja returned to the Test side for the 4th Ashes Test in 2021/22 and he made a strong statement after scoring twin-centuries. He followed that up with another excellent performance in Pakistan and ended as the leading run-scorer. Khawaja proved his worth once again as he finished the highly-anticipated 2023 Ashes in England as the leading run-scorer. His contributions at the top of the order were vital in helping Australia retain the Ashes after drawing the series 2-2.  <br/>  <br/> In T20s, Khawaja had a brief stint in the IPL in 2016 with the now defunct Rising Pune Supergiants. He also played a few games for the Islamabad United in the PSL and represented the Sydney Thunder in the BBL until 2022. For the 2023 season, he was signed by the Brisbane Heat and named their captain despite his slim availability due to international duties.  <br/>  <br/> <b>Interesting facts:</b> Apart from being a professional cricketer, Khawaja is also a qualified pilot. <br/>  <br/> Usman is an ex-student of Westfields Sports School, which has also produced sportsmen of the calibre of Michael Clarke (former Australia captain), soccer player Harry Kewell and world champion discus thrower Dani Samuels. <br/>  <br/> <b>By Cricbuzz Staff</b>", 'rankings': {'bat': {'testRank': '27', 'testBestRank': '4', 'odiBestRank': '15', 't20BestRank': '54'}, 'bowl': {}, 'all': {}}, 'appIndex': {'seoTitle': 'Usman Khawaja Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/6635/usman-khawaja'}, 'DoBFormat': 'December 18, 1986', 'faceImageId': 332905, 'teamNameIds': [{'teamId': '4', 'teamName': 'Australia'}, {'teamId': '104', 'teamName': 'New South Wales'}, {'teamId': '144', 'teamName': 'Derbyshire'}, {'teamId': '191', 'teamName': 'Cricket Australia Chairmans XI'}, {'teamId': '192', 'teamName': 'Sydney Thunder'}, {'teamId': '164', 'teamName': 'Queensland'}, {'teamId': '266', 'teamName': 'Australians'}, {'teamId': '79', 'teamName': 'Australia A'}, {'teamId': '143', 'teamName': 'Lancashire'}, {'teamId': '346', 'teamName': 'Rising Pune Supergiant'}, {'teamId': '149', 'teamName': 'Glamorgan'}, {'teamId': '330', 'teamName': 'Islamabad United'}, {'teamId': '193', 'teamName': 'Brisbane Heat'}], 'playerTeamIds': '4, 104, 144, 191, 192, 164, 266, 79, 143, 346, 149, 330, 193', 'intlTeamImageId': 776202, 'recentBatting': {'headers': ['Score', 'OPPN.', 'Format', 'Date'], 'rows': [{'values': ['108811', '17 & 6', 'ENG', 'Test', '04 Jan 26'], 'followUpLinkText': '/live-cricket-scores/108811/aus-vs-eng-5th-test-the-ashes-2025-26'}, {'values': ['108809', '29 & 0', 'ENG', 'Test', '26 Dec 25'], 'followUpLinkText': '/live-cricket-scores/108809/aus-vs-eng-4th-test-the-ashes-2025-26'}, {'values': ['108801', '82 & 40', 'ENG', 'Test', '17 Dec 25'], 'followUpLinkText': '/live-cricket-scores/108801/aus-vs-eng-3rd-test-the-ashes-2025-26'}, {'values': ['108787', '2 & DNB', 'ENG', 'Test', '21 Nov 25'], 'followUpLinkText': '/live-cricket-scores/108787/aus-vs-eng-1st-test-the-ashes-2025-26'}, {'values': ['114600', '23 & 14', 'WI', 'Test', '13 Jul 25'], 'followUpLinkText': '/live-cricket-scores/114600/wi-vs-aus-3rd-test-australia-tour-of-west-indies-2025'}]}, 'recentBowling': {'headers': ['Wickets', 'OPPN.', 'Format', 'Date'], 'rows': [{'values': ['40348', 'DNB & 0-3', 'PAK', 'Test', '04 Mar 22'], 'followUpLinkText': '/live-cricket-scores/40348/pak-vs-aus-1st-test-australia-tour-of-pakistan-2022'}, {'values': ['20304', '0-4 & DNB', 'IND', 'Test', '03 Jan 19'], 'followUpLinkText': '/live-cricket-scores/20304/aus-vs-ind-4th-test-india-tour-of-australia-2018-19'}, {'values': ['18375', 'DNB & 0-1', 'BAN', 'Test', '27 Aug 17'], 'followUpLinkText': '/live-cricket-scores/18375/ban-vs-aus-1st-test-australia-tour-of-bangladesh-2017'}]}}

In [121]:
player_data = response.json()

In [59]:
# player_data

In [164]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/139216/scard"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'scorecard': [{'inningsid': 1, 'batsman': [{'id': 10276, 'balls': 40, 'runs': 77, 'fours': 10, 'sixes': 3, 'strkrate': '192.5', 'name': 'Ishan Kishan', 'nickname': 'Ishan Kishan', 'iscaptain': False, 'iskeeper': True, 'outdec': 'b Saim Ayub', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 12086, 'balls': 4, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Abhishek Sharma', 'nickname': 'Abhishek Sharma', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Shaheen Afridi b Salman Agha', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 14504, 'balls': 24, 'runs': 25, 'fours': 2, 'sixes': 1, 'strkrate': '104.17', 'name': 'Tilak Varma', 'nickname': 'Tilak Varma', 'iscaptain': False, 'iskeeper': False, 'outdec': 'lbw b Saim Ayub', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 7915, 'balls': 29, 'runs': 32, 'fours': 3, 'sixes': 0, 'strkrate': '110.34', 'name': 'Suryakumar Yadav', 'nickname': 'Suryakumar Yadav', 'iscaptain': True, 'iskeeper': False, 'outdec': 'c Saim Ayub b Usman Tariq', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 9647, 'balls': 1, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Hardik Pandya', 'nickname': 'Hardik Pandya', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Babar Azam b Saim Ayub', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11195, 'balls': 17, 'runs': 27, 'fours': 3, 'sixes': 1, 'strkrate': '158.82', 'name': 'Shivam Dube', 'nickname': 'Shivam Dube', 'iscaptain': False, 'iskeeper': False, 'outdec': 'run out (Mohammad Nawaz/Usman Khan)', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 10896, 'balls': 4, 'runs': 11, 'fours': 1, 'sixes': 1, 'strkrate': '275', 'name': 'Rinku Singh', 'nickname': 'Rinku Singh', 'iscaptain': False, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8808, 'balls': 1, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Axar Patel', 'nickname': 'Axar Patel', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Saim Ayub b Shaheen Afridi', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8292, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Kuldeep Yadav', 'nickname': 'Kuldeep Yadav', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 12926, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Varun Chakaravarthy', 'nickname': 'Varun Chakaravarthy', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 9311, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Jasprit Bumrah', 'nickname': 'Jasprit Bumrah', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'bowler': [{'id': 10101, 'overs': '2', 'maidens': 0, 'wickets': 1, 'runs': 10, 'economy': '5', 'name': 'Salman Agha', 'nickname': 'Salman Agha', 'iscaptain': True, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 12, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 12160, 'overs': '2', 'maidens': 0, 'wickets': 1, 'runs': 31, 'economy': '15.5', 'name': 'Shaheen Afridi', 'nickname': 'Shaheen Afridi', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 12, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 14241, 'overs': '4', 'maidens': 0, 'wickets': 3, 'runs': 25, 'economy': '6.2', 'name': 'Saim Ayub', 'nickname': 'Saim Ayub', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 24, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 12555, 'overs': '3', 'maidens': 0, 'wickets': 0, 'runs': 38, 'economy': '12.7', 'name': 'Abrar Ahmed', 'nickname': 'Abrar Ahmed', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 18, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11186, 'overs': '1', 'maidens': 0, 'wickets': 0, 'runs': 17, 'economy': '17', 'name': 'Shadab Khan', 'nickname': 'Shadab Khan', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 6, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8367, 'overs': '4', 'maidens': 0, 'wickets': 0, 'runs': 28, 'economy': '7', 'name': 'Mohammad Nawaz', 'nickname': 'Mohammad Nawaz', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 24, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 55799, 'overs': '4', 'maidens': 0, 'wickets': 1, 'runs': 24, 'economy': '6', 'name': 'Usman Tariq', 'nickname': 'Usman Tariq', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 24, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'fow': {'fow': [{'batsmanid': 12086, 'batsmanname': 'Abhishek Sharma', 'overnbr': 0.6, 'runs': 1, 'ballnbr': 6}, {'batsmanid': 10276, 'batsmanname': 'Ishan Kishan', 'overnbr': 8.4, 'runs': 88, 'ballnbr': 52}, {'batsmanid': 14504, 'batsmanname': 'Tilak Varma', 'overnbr': 14.2, 'runs': 126, 'ballnbr': 86}, {'batsmanid': 9647, 'batsmanname': 'Hardik Pandya', 'overnbr': 14.3, 'runs': 126, 'ballnbr': 87}, {'batsmanid': 7915, 'batsmanname': 'Suryakumar Yadav', 'overnbr': 18.5, 'runs': 159, 'ballnbr': 113}, {'batsmanid': 11195, 'batsmanname': 'Shivam Dube', 'overnbr': 19.5, 'runs': 175, 'ballnbr': 119}, {'batsmanid': 8808, 'batsmanname': 'Axar Patel', 'overnbr': 19.6, 'runs': 175, 'ballnbr': 120}]}, 'extras': {'legbyes': 2, 'byes': 0, 'wides': 1, 'noballs': 0, 'penalty': 0, 'total': 3}, 'pp': {'powerplay': [{'id': 17, 'ovrfrom': 0.1, 'ovrto': 6.0, 'pptype': 'Mandatory', 'run': 52, 'wickets': 0}]}, 'score': 175, 'wickets': 7, 'overs': 20.0, 'runrate': 8.75, 'batteamname': 'India', 'batteamsname': 'IND', 'isdeclared': False, 'isfollowon': False, 'ballnbr': 120, 'rpb': 1.46, 'partnership': {'partnership': [{'id': 0, 'bat1id': 10276, 'bat1name': 'Ishan Kishan', 'bat1runs': 1, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 12086, 'bat2name': 'Abhishek Sharma', 'bat2runs': 0, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 1, 'totalballs': 6, 'bat1balls': 2, 'bat2balls': 4, 'teamname': '', 'teamid': 0, 'bat1ones': 1, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 10276, 'bat1name': 'Ishan Kishan', 'bat1runs': 76, 'bat1fours': 10, 'bat1sixes': 3, 'bat2id': 14504, 'bat2name': 'Tilak Varma', 'bat2runs': 11, 'bat2fours': 2, 'bat2sixes': 0, 'totalruns': 87, 'totalballs': 46, 'bat1balls': 38, 'bat2balls': 8, 'teamname': '', 'teamid': 0, 'bat1ones': 10, 'bat1twos': 4, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 10, 'bat1sixers': 3, 'bat2ones': 3, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 2, 'bat2sixers': 0}, {'id': 0, 'bat1id': 7915, 'bat1name': 'Suryakumar Yadav', 'bat1runs': 22, 'bat1fours': 2, 'bat1sixes': 0, 'bat2id': 14504, 'bat2name': 'Tilak Varma', 'bat2runs': 14, 'bat2fours': 0, 'bat2sixes': 1, 'totalruns': 38, 'totalballs': 34, 'bat1balls': 18, 'bat2balls': 16, 'teamname': '', 'teamid': 0, 'bat1ones': 9, 'bat1twos': 1, 'bat1threes': 1, 'bat1fives': 0, 'bat1boundaries': 2, 'bat1sixers': 0, 'bat2ones': 6, 'bat2twos': 1, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 1}, {'id': 0, 'bat1id': 7915, 'bat1name': 'Suryakumar Yadav', 'bat1runs': 0, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 9647, 'bat2name': 'Hardik Pandya', 'bat2runs': 0, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 0, 'totalballs': 1, 'bat1balls': 0, 'bat2balls': 1, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 7915, 'bat1name': 'Suryakumar Yadav', 'bat1runs': 10, 'bat1fours': 1, 'bat1sixes': 0, 'bat2id': 11195, 'bat2name': 'Shivam Dube', 'bat2runs': 22, 'bat2fours': 2, 'bat2sixes': 1, 'totalruns': 33, 'totalballs': 26, 'bat1balls': 11, 'bat2balls': 15, 'teamname': '', 'teamid': 0, 'bat1ones': 6, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 1, 'bat1sixers': 0, 'bat2ones': 8, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 2, 'bat2sixers': 1}, {'id': 0, 'bat1id': 10896, 'bat1name': 'Rinku Singh', 'bat1runs': 10, 'bat1fours': 1, 'bat1sixes': 1, 'bat2id': 11195, 'bat2name': 'Shivam Dube', 'bat2runs': 5, 'bat2fours': 1, 'bat2sixes': 0, 'totalruns': 16, 'totalballs': 6, 'bat1balls': 4, 'bat2balls': 2, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 1, 'bat1sixers': 1, 'bat2ones': 1, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 1, 'bat2sixers': 0}, {'id': 0, 'bat1id': 10896, 'bat1name': 'Rinku Singh', 'bat1runs': 0, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 8808, 'bat2name': 'Axar Patel', 'bat2runs': 0, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 0, 'totalballs': 1, 'bat1balls': 0, 'bat2balls': 1, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}]}}, {'inningsid': 2, 'batsman': [{'id': 13625, 'balls': 4, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Sahibzada Farhan', 'nickname': 'Sahibzada Farhan', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Rinku Singh b Hardik Pandya', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 14241, 'balls': 2, 'runs': 6, 'fours': 0, 'sixes': 1, 'strkrate': '300', 'name': 'Saim Ayub', 'nickname': 'Saim Ayub', 'iscaptain': False, 'iskeeper': False, 'outdec': 'lbw b Jasprit Bumrah', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 10101, 'balls': 4, 'runs': 4, 'fours': 1, 'sixes': 0, 'strkrate': '100', 'name': 'Salman Agha', 'nickname': 'Salman Agha', 'iscaptain': True, 'iskeeper': False, 'outdec': 'c Hardik Pandya b Jasprit Bumrah', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8359, 'balls': 7, 'runs': 5, 'fours': 0, 'sixes': 0, 'strkrate': '71.43', 'name': 'Babar Azam', 'nickname': 'Babar Azam', 'iscaptain': False, 'iskeeper': False, 'outdec': 'b Axar Patel', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 19013, 'balls': 34, 'runs': 44, 'fours': 6, 'sixes': 1, 'strkrate': '129.41', 'name': 'Usman Khan', 'nickname': 'Usman Khan', 'iscaptain': False, 'iskeeper': True, 'outdec': 'st Ishan Kishan b Axar Patel', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11186, 'balls': 15, 'runs': 14, 'fours': 1, 'sixes': 0, 'strkrate': '93.33', 'name': 'Shadab Khan', 'nickname': 'Shadab Khan', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Shivam Dube b Tilak Varma', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8367, 'balls': 5, 'runs': 4, 'fours': 1, 'sixes': 0, 'strkrate': '80', 'name': 'Mohammad Nawaz', 'nickname': 'Mohammad Nawaz', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Shivam Dube b Kuldeep Yadav', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11265, 'balls': 14, 'runs': 10, 'fours': 1, 'sixes': 0, 'strkrate': '71.43', 'name': 'Faheem Ashraf', 'nickname': 'Faheem Ashraf', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Rinku Singh b Varun Chakaravarthy', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 12160, 'balls': 19, 'runs': 23, 'fours': 2, 'sixes': 1, 'strkrate': '121.05', 'name': 'Shaheen Afridi', 'nickname': 'Shaheen Afridi', 'iscaptain': False, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 12555, 'balls': 1, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Abrar Ahmed', 'nickname': 'Abrar Ahmed', 'iscaptain': False, 'iskeeper': False, 'outdec': 'lbw b Varun Chakaravarthy', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 55799, 'balls': 3, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Usman Tariq', 'nickname': 'Usman Tariq', 'iscaptain': False, 'iskeeper': False, 'outdec': 'b Hardik Pandya', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'bowler': [{'id': 9647, 'overs': '3', 'maidens': 1, 'wickets': 2, 'runs': 16, 'economy': '5.3', 'name': 'Hardik Pandya', 'nickname': 'Hardik Pandya', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 18, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 9311, 'overs': '2', 'maidens': 0, 'wickets': 2, 'runs': 17, 'economy': '8.5', 'name': 'Jasprit Bumrah', 'nickname': 'Jasprit Bumrah', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 12, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8808, 'overs': '4', 'maidens': 0, 'wickets': 2, 'runs': 29, 'economy': '7.2', 'name': 'Axar Patel', 'nickname': 'Axar Patel', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 24, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 12926, 'overs': '3', 'maidens': 0, 'wickets': 2, 'runs': 17, 'economy': '5.7', 'name': 'Varun Chakaravarthy', 'nickname': 'Varun Chakaravarthy', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 18, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8292, 'overs': '3', 'maidens': 0, 'wickets': 1, 'runs': 14, 'economy': '4.7', 'name': 'Kuldeep Yadav', 'nickname': 'Kuldeep Yadav', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 18, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 14504, 'overs': '2', 'maidens': 0, 'wickets': 1, 'runs': 11, 'economy': '5.5', 'name': 'Tilak Varma', 'nickname': 'Tilak Varma', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 12, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 10896, 'overs': '1', 'maidens': 0, 'wickets': 0, 'runs': 9, 'economy': '9', 'name': 'Rinku Singh', 'nickname': 'Rinku Singh', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 6, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'fow': {'fow': [{'batsmanid': 13625, 'batsmanname': 'Sahibzada Farhan', 'overnbr': 0.4, 'runs': 0, 'ballnbr': 4}, {'batsmanid': 14241, 'batsmanname': 'Saim Ayub', 'overnbr': 1.2, 'runs': 6, 'ballnbr': 8}, {'batsmanid': 10101, 'batsmanname': 'Salman Agha', 'overnbr': 1.6, 'runs': 13, 'ballnbr': 12}, {'batsmanid': 8359, 'batsmanname': 'Babar Azam', 'overnbr': 4.5, 'runs': 34, 'ballnbr': 29}, {'batsmanid': 19013, 'batsmanname': 'Usman Khan', 'overnbr': 10.4, 'runs': 73, 'ballnbr': 64}, {'batsmanid': 8367, 'batsmanname': 'Mohammad Nawaz', 'overnbr': 11.4, 'runs': 7

In [58]:
# response.json()

In [11]:
!pip install psycopg2
import psycopg2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting psycopg2
  Downloading psycopg2-2.9.11-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2-2.9.11-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 2.8/2.8 MB 14.6 MB/s  0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.11

In [197]:
connection = psycopg2.connect(
    host="localhost",
    port=5432,
    database="guvi",
    user="postgres",
    password="armaaz911"
)
cursor = connection.cursor()
connection.autocommit=True

In [22]:
cursor.execute("select * from employees")

In [57]:
# rows = cursor.fetchall()
# rows

In [31]:
connection.commit()

In [72]:
cursor.execute("drop table if exists live_score")
cursor.execute("""
               create table live_score(
               team1runs smallint,
               team2runs smallint,
               team1wickets smallint,
               team2wickets smallint
               )

""")

In [73]:
insert_query = """
               insert into live_score(team1runs,team2runs,team1wickets,team2wickets) values
               (%s,%s,%s,%s)
"""
for i in data:
    record = extract_match(i)
    cursor.execute(insert_query, record)

In [ ]:
for i in data:
    record = extract_match(i)
    print(record)

KeyError: 'series'

In [ ]:
# getting score card of live match

import requests

url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/40381/scard"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'scorecard': [{'inningsid': 1, 'batsman': [{'id': 1114, 'balls': 5, 'runs': 5, 'fours': 1, 'sixes': 0, 'strkrate': '100', 'name': 'Stirling', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'lbw b Nisarg Patel', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 6710, 'balls': 5, 'runs': 10, 'fours': 2, 'sixes': 0, 'strkrate': '200', 'name': 'Balbirnie', 'nickname': '', 'iscaptain': True, 'iskeeper': False, 'outdec': 'c Sushant Modani b Netravalkar', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11131, 'balls': 56, 'runs': 84, 'fours': 9, 'sixes': 3, 'strkrate': '150', 'name': 'Lorcan Tucker', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'b Netravalkar', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 18143, 'balls': 11, 'runs': 17, 'fours': 2, 'sixes': 1, 'strkrate': '154.55', 'name': 'Curtis Campher', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Marty Kain b Yasir Mohammad', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 6471, 'balls': 10, 'runs': 5, 'fours': 0, 'sixes': 0, 'strkrate': '50', 'name': 'Getkate', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Ritwik Behera b Vatsal Vaghela', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 13309, 'balls': 5, 'runs': 4, 'fours': 0, 'sixes': 0, 'strkrate': '80', 'name': 'Neil Rock', 'nickname': '', 'iscaptain': False, 'iskeeper': True, 'outdec': 'c Ritwik Behera b Vatsal Vaghela', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11129, 'balls': 3, 'runs': 1, 'fours': 0, 'sixes': 0, 'strkrate': '33.33', 'name': 'William McClintock', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Marty Kain b Nisarg Patel', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 10449, 'balls': 4, 'runs': 3, 'fours': 0, 'sixes': 0, 'strkrate': '75', 'name': 'Mark Adair', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'b Netravalkar', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 12769, 'balls': 11, 'runs': 13, 'fours': 1, 'sixes': 0, 'strkrate': '118.18', 'name': 'Simi Singh', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Ali Khan b Yasir Mohammad', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 10451, 'balls': 1, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Barry McCarthy', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'run out (Monank Patel)', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11124, 'balls': 2, 'runs': 2, 'fours': 0, 'sixes': 0, 'strkrate': '100', 'name': 'Benjamin White', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'bowler': [{'id': 15475, 'overs': '4', 'maidens': 0, 'wickets': 2, 'runs': 29, 'economy': '7.2', 'name': 'Nisarg Patel', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 24, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 9748, 'overs': '3.5', 'maidens': 0, 'wickets': 3, 'runs': 33, 'economy': '8.6', 'name': 'Netravalkar', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 23, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11450, 'overs': '3', 'maidens': 0, 'wickets': 0, 'runs': 34, 'economy': '11.3', 'name': 'Ali Khan', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 18, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 22901, 'overs': '4', 'maidens': 0, 'wickets': 2, 'runs': 32, 'economy': '8', 'name': 'Yasir Mohammad', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 24, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 22531, 'overs': '3', 'maidens': 0, 'wickets': 2, 'runs': 16, 'economy': '5.3', 'name': 'Vatsal Vaghela', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 18, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 22891, 'overs': '1', 'maidens': 0, 'wickets': 0, 'runs': 5, 'economy': '5', 'name': 'Ritwik Behera', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 6, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'fow': {'fow': [{'batsmanid': 1114, 'batsmanname': 'Stirling', 'overnbr': 0.6, 'runs': 6, 'ballnbr': 6}, {'batsmanid': 6710, 'batsmanname': 'Balbirnie', 'overnbr': 1.6, 'runs': 20, 'ballnbr': 12}, {'batsmanid': 18143, 'batsmanname': 'Curtis Campher', 'overnbr': 6.1, 'runs': 59, 'ballnbr': 37}, {'batsmanid': 6471, 'batsmanname': 'Getkate', 'overnbr': 9.5, 'runs': 83, 'ballnbr': 59}, {'batsmanid': 13309, 'batsmanname': 'Neil Rock', 'overnbr': 11.4, 'runs': 92, 'ballnbr': 70}, {'batsmanid': 11129, 'batsmanname': 'William McClintock', 'overnbr': 12.4, 'runs': 96, 'ballnbr': 76}, {'batsmanid': 10449, 'batsmanname': 'Mark Adair', 'overnbr': 13.5, 'runs': 102, 'ballnbr': 83}, {'batsmanid': 12769, 'batsmanname': 'Simi Singh', 'overnbr': 16.5, 'runs': 128, 'ballnbr': 101}, {'batsmanid': 10451, 'batsmanname': 'Barry McCarthy', 'overnbr': 17.3, 'runs': 134, 'ballnbr': 105}, {'batsmanid': 11131, 'batsmanname': 'Lorcan Tucker', 'overnbr': 18.5, 'runs': 150, 'ballnbr': 113}]}, 'extras': {'legbyes': 1, 'byes': 0, 'wides': 5, 'noballs': 0, 'penalty': 0, 'total': 6}, 'pp': {'powerplay': [{'id': 27, 'ovrfrom': 0.1, 'ovrto': 6.0, 'pptype': 'Mandatory', 'run': 59, 'wickets': 0}]}, 'score': 150, 'wickets': 10, 'overs': 18.5, 'runrate': 7.96, 'batteamname': 'Ireland', 'batteamsname': 'IRE', 'isdeclared': False, 'isfollowon': False, 'ballnbr': 113, 'rpb': 1.33, 'partnership': {'partnership': [{'id': 0, 'bat1id': 1114, 'bat1name': 'Stirling', 'bat1runs': 5, 'bat1fours': 1, 'bat1sixes': 0, 'bat2id': 6710, 'bat2name': 'Balbirnie', 'bat2runs': 1, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 6, 'totalballs': 6, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 11131, 'bat1name': 'Lorcan Tucker', 'bat1runs': 5, 'bat1fours': 1, 'bat1sixes': 0, 'bat2id': 6710, 'bat2name': 'Balbirnie', 'bat2runs': 9, 'bat2fours': 2, 'bat2sixes': 0, 'totalruns': 14, 'totalballs': 6, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 11131, 'bat1name': 'Lorcan Tucker', 'bat1runs': 22, 'bat1fours': 3, 'bat1sixes': 1, 'bat2id': 18143, 'bat2name': 'Curtis Campher', 'bat2runs': 17, 'bat2fours': 2, 'bat2sixes': 1, 'totalruns': 39, 'totalballs': 25, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 11131, 'bat1name': 'Lorcan Tucker', 'bat1runs': 19, 'bat1fours': 3, 'bat1sixes': 0, 'bat2id': 6471, 'bat2name': 'Getkate', 'bat2runs': 5, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 24, 'totalballs': 22, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 11131, 'bat1name': 'Lorcan Tucker', 'bat1runs': 5, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 13309, 'bat2name': 'Neil Rock', 'bat2runs': 4, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 9, 'totalballs': 11, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 11131, 'bat1name': 'Lorcan Tucker', 'bat1runs': 3, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 11129, 'bat2name': 'William McClintock', 'bat2runs': 1, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 4, 'totalballs': 6, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 11131, 'bat1name': 'Lorcan Tucker', 'bat1runs': 3, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 10449, 'bat2name': 'Mark Adair', 'bat2runs': 3, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 6, 'totalballs': 7, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 11131, 'bat1name': 'Lorcan Tucker', 'bat1runs': 7, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 12769, 'bat2name': 'Simi Singh', 'bat2runs': 13, 'bat2fours': 1, 'bat2sixes': 0, 'totalruns': 26, 'totalballs': 18, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 11131, 'bat1name': 'Lorcan Tucker', 'bat1runs': 6, 'bat1fours': 0, 'bat1sixes': 1, 'bat2id': 10451, 'bat2name': 'McCarthy', 'bat2runs': 0, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 6, 'totalballs': 4, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 11131, 'bat1name': 'Lorcan Tucker', 'bat1runs': 14, 'bat1fours': 2, 'bat1sixes': 1, 'bat2id': 11124, 'bat2name': 'Benjamin White', 'bat2runs': 2, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 16, 'totalballs': 8, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}]}}, {'inningsid': 2, 'batsman': [{'id': 22891, 'balls': 23, 'runs': 16, 'fours': 1, 'sixes': 0, 'strkrate': '69.57', 'name': 'Ritwik Behera', 'nickname': 'Ritwik Behera', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Getkate b Mark Adair', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 22896, 'balls': 11, 'runs': 11, 'fours': 2, 'sixes': 0, 'strkrate': '100', 'name': 'Ryan Scott', 'nickname': 'Ryan Scott', 'iscaptain': False, 'iskeeper': False, 'outdec': 'run out (Curtis Campher)', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 14732, 'balls': 27, 'runs': 26, 'fours': 2, 'sixes': 1, 'strkrate': '96.3', 'name': 'Monank Patel', 'nickname': 'Monank Patel', 'iscaptain': True, 'iskeeper': True, 'outdec': 'c Mark Adair b Benjamin White', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 12788, 'balls': 20, 'runs': 22, 'fours': 1, 'sixes': 1, 'strkrate': '110', 'name': 'Gajanand Singh', 'nickname': 'Gajanand Singh', 'iscaptain': False, 'iskeeper': False, 'outdec': 'lbw b Curtis Campher', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 20217, 'balls': 16, 'runs': 27, 'fours': 1, 'sixes': 2, 'strkrate': '168.75', 'name': 'Sushant Modani', 'nickname': 'Sushant Modani', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Lorcan Tucker b Curtis Campher', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 10699, 'balls': 11, 'runs': 11, 'fours': 1, 'sixes': 0, 'strkrate': '100', 'name': 'Marty Kain', 'nickname': 'Marty Kain', 'iscaptain': False, 'iskeeper': False, 'outdec': 'b Curtis Campher', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 15475, 'balls': 6, 'runs': 10, 'fours': 2, 'sixes': 0, 'strkrate': '166.67', 'name': 'Nisarg Patel', 'nickname': 'Nisarg Patel', 'iscaptain': False, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 22901, 'balls': 2, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Yasir Mohammad', 'nickname': 'Yasir Mohammad', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c and b Curtis Campher', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 9748, 'balls': 6, 'runs': 5, 'fours': 0, 'sixes': 0, 'strkrate': '83.33', 'name': 'Saurabh Netravalkar', 'nickname': 'Netravalkar', 'iscaptain': False, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 22531, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Vatsal Vaghela', 'nickname': 'Vatsal Vaghela', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11450, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Ali Khan', 'nickname': 'Ali Khan', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'bowler': [{'id': 10449, 'overs': '4', 'maidens': 0, 'wickets': 1, 'runs': 25, 'economy': '6.2', 'name': 'Mark Adair', 'nickname': 'Mark Adair', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 24, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 10451, 'overs': '4', 'maidens': 0, 'wickets': 0, 'runs': 24, 'economy': '6', 'name': 'Barry McCarthy', 'nickname': 'Barry McCarthy', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 24, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 18143, 'overs': '4', 'maidens': 1, 'wickets': 4, 'runs': 25, 'economy': '6.2', 'name': 'Curtis Campher', 'nickname': 'Curtis Campher', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 24, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 12769, 'overs': '4', 'maidens': 0, 'wickets': 0, 'runs': 31, 'economy': '7.8', 'name': 'Simi Singh', 'nickname': 'Simi Singh', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 24, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11124, 'overs': '3', 'maidens': 0, 'wickets': 1, 'runs': 27, 'economy': '9', 'name': 'Benjamin White', 'nickname': 'Benjamin White', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 18, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 1114, 'overs': '1', 'maidens': 0, 'wickets': 0, 'runs': 4, 'economy': '4', 'name': 'Paul Stirling', 'nickname': 'Stirling', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 6, 'rpb': 0.0, 'planid

In [134]:
score_data = response.json()
score_data['scorecard'][0]['batsman'][0]
score_data['appindex']
len(score_data['scorecard'])
score_data['scorecard'][0]['inningsid']

1

In [ ]:
bat_stat1 = []
bat_stat2 = []
for score in score_data['scorecard']:
    if score['inningsid']==1:
        batting_stat = score['batsman']
        for playerscore in batting_stat:
            b_name = playerscore['name']
            b_runs = playerscore['runs']
            b_balls = playerscore['balls']
            b_sixes = playerscore['sixes']
            b_fours = playerscore['fours']
            
        bat_stat1.append({
            'Batsman Name' : b_name,
            'Runs' : b_runs,
            'Balls' : b_balls,
            'Sixes' : b_sixes,
            'Fours' : b_fours
        })

In [147]:
bat_stat1 = []
bat_stat2 = []
for s in score_data['scorecard']:
    if s['inningsid'] == 1:
        for ps in s['batsman']:
            name = ps['name']
            runs = ps['runs']
            balls = ps['balls']
            sixes = ps['sixes']
            fours = ps['fours']

            bat_stat1.append({
                'name' : name,
                'runs' : runs,
                'balls' : balls,
                'sixes' : sixes,
                'fours' : fours
            })
    elif s['inningsid'] == 2:
        for ps in s['batsman']:
            name = ps['name']
            runs = ps['runs']
            balls = ps['balls']
            sixes = ps['sixes']
            fours = ps['fours']

            bat_stat2.append({
                'name' : name,
                'runs' : runs,
                'balls' : balls,
                'sixes' : sixes,
                'fours' : fours
            })

In [148]:
bat_stat1

[{'name': 'Stirling', 'runs': 5, 'balls': 5, 'sixes': 0, 'fours': 1},
 {'name': 'Balbirnie', 'runs': 10, 'balls': 5, 'sixes': 0, 'fours': 2},
 {'name': 'Lorcan Tucker', 'runs': 84, 'balls': 56, 'sixes': 3, 'fours': 9},
 {'name': 'Curtis Campher', 'runs': 17, 'balls': 11, 'sixes': 1, 'fours': 2},
 {'name': 'Getkate', 'runs': 5, 'balls': 10, 'sixes': 0, 'fours': 0},
 {'name': 'Neil Rock', 'runs': 4, 'balls': 5, 'sixes': 0, 'fours': 0},
 {'name': 'William McClintock', 'runs': 1, 'balls': 3, 'sixes': 0, 'fours': 0},
 {'name': 'Mark Adair', 'runs': 3, 'balls': 4, 'sixes': 0, 'fours': 0},
 {'name': 'Simi Singh', 'runs': 13, 'balls': 11, 'sixes': 0, 'fours': 1},
 {'name': 'Barry McCarthy', 'runs': 0, 'balls': 1, 'sixes': 0, 'fours': 0},
 {'name': 'Benjamin White', 'runs': 2, 'balls': 2, 'sixes': 0, 'fours': 0}]

In [149]:
bat_stat2

[{'name': 'Ritwik Behera', 'runs': 16, 'balls': 23, 'sixes': 0, 'fours': 1},
 {'name': 'Ryan Scott', 'runs': 11, 'balls': 11, 'sixes': 0, 'fours': 2},
 {'name': 'Monank Patel', 'runs': 26, 'balls': 27, 'sixes': 1, 'fours': 2},
 {'name': 'Gajanand Singh', 'runs': 22, 'balls': 20, 'sixes': 1, 'fours': 1},
 {'name': 'Sushant Modani', 'runs': 27, 'balls': 16, 'sixes': 2, 'fours': 1},
 {'name': 'Marty Kain', 'runs': 11, 'balls': 11, 'sixes': 0, 'fours': 1},
 {'name': 'Nisarg Patel', 'runs': 10, 'balls': 6, 'sixes': 0, 'fours': 2},
 {'name': 'Yasir Mohammad', 'runs': 0, 'balls': 2, 'sixes': 0, 'fours': 0},
 {'name': 'Saurabh Netravalkar',
  'runs': 5,
  'balls': 6,
  'sixes': 0,
  'fours': 0},
 {'name': 'Vatsal Vaghela', 'runs': 0, 'balls': 0, 'sixes': 0, 'fours': 0},
 {'name': 'Ali Khan', 'runs': 0, 'balls': 0, 'sixes': 0, 'fours': 0}]

In [161]:
cursor.execute("drop table if exists innings1_scorecard")
cursor.execute("""
               create table innings1_scorecard(
               Name varchar(30),
               Runs smallint,
               Balls smallint,
               Sixes smallint,
               Fours smallint)
            """)

In [162]:
query_scorecard = """
                insert into innings1_scorecard(Name,Runs,Balls,Sixes,Fours) values
                (%s,%s,%s,%s,%s)
"""
for i in  bat_stat1:
    row = (i['name'],i['runs'],i['balls'],i['sixes'],i['fours'])
    cursor.execute(query_scorecard,row)

In [160]:
cursor.execute("drop table if exists innings2_scorecard")
cursor.execute("""
               create table innings2_scorecard(
               Name varchar(30),
               Runs smallint,
               Balls smallint,
               Sixes smallint,
               Fours smallint)
            """)

query_scorecard = """
                insert into innings2_scorecard(Name,Runs,Balls,Sixes,Fours) values
                (%s,%s,%s,%s,%s)
"""
for i in  bat_stat2:
    row = (i['name'],i['runs'],i['balls'],i['sixes'],i['fours'])
    cursor.execute(query_scorecard,row)

In [ ]:
insert_query = """
               insert into live_score(team1runs,team2runs,team1wickets,team2wickets) values
               (%s,%s,%s,%s)
"""
for i in data:
    record = extract_match(i)
    cursor.execute(insert_query, record)

In [167]:
# players get career
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/8733/career"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'values': [{'name': 't20', 'debut': 'vs Zimbabwe,  2016-06-18, Harare Sports Club', 'lastPlayed': 'vs England,  2022-11-10, Adelaide Oval', 'debutMatchID': '16610', 'lastPlayedMatchId': '43201'}, {'name': 'test', 'debut': 'vs Australia,  2014-12-26, Melbourne Cricket Ground', 'lastPlayed': 'vs South Africa,  2025-11-22, Barsapara Cricket Stadium', 'debutMatchID': '13842', 'lastPlayedMatchId': '117380'}, {'name': 'odi', 'debut': 'vs Zimbabwe,  2016-06-11, Harare Sports Club', 'lastPlayed': 'vs New Zealand,  2026-01-18, Holkar Stadium', 'debutMatchID': '16607', 'lastPlayedMatchId': '121378'}, {'name': 'ipl', 'debut': 'vs Kolkata Knight Riders,  2013-04-11, M.Chinnaswamy Stadium', 'lastPlayed': 'vs Punjab Kings,  2025-05-24, Sawai Mansingh Stadium', 'debutMatchID': '11876', 'lastPlayedMatchId': '118874'}, {'name': 'cl', 'debut': 'Not played', 'lastPlayed': 'Not played'}], 'appIndex': {'seoTitle': 'KL Rahul Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/8733/kl-rahul'}}

In [168]:
player_careed_data = response.json()
player_careed_data

{'values': [{'name': 't20',
   'debut': 'vs Zimbabwe,  2016-06-18, Harare Sports Club',
   'lastPlayed': 'vs England,  2022-11-10, Adelaide Oval',
   'debutMatchID': '16610',
   'lastPlayedMatchId': '43201'},
  {'name': 'test',
   'debut': 'vs Australia,  2014-12-26, Melbourne Cricket Ground',
   'lastPlayed': 'vs South Africa,  2025-11-22, Barsapara Cricket Stadium',
   'debutMatchID': '13842',
   'lastPlayedMatchId': '117380'},
  {'name': 'odi',
   'debut': 'vs Zimbabwe,  2016-06-11, Harare Sports Club',
   'lastPlayed': 'vs New Zealand,  2026-01-18, Holkar Stadium',
   'debutMatchID': '16607',
   'lastPlayedMatchId': '121378'},
  {'name': 'ipl',
   'debut': 'vs Kolkata Knight Riders,  2013-04-11, M.Chinnaswamy Stadium',
   'lastPlayed': 'vs Punjab Kings,  2025-05-24, Sawai Mansingh Stadium',
   'debutMatchID': '11876',
   'lastPlayedMatchId': '118874'},
  {'name': 'cl', 'debut': 'Not played', 'lastPlayed': 'Not played'}],
 'appIndex': {'seoTitle': 'KL Rahul Profile - Cricbuzz | Cricbuzz.com',
  'webURL': 'http://www.cricbuzz.com/profiles/8733/kl-rahul'}}

In [ ]:
# player info
# player personal info/profile
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/6635"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'id': '6635', 'bat': 'Left Handed Bat', 'bowl': 'Right-arm offbreak', 'name': 'Usman Khawaja', 'nickName': 'Khawaja', 'height': '1.75 m ', 'role': 'Batsman', 'birthPlace': 'Islamabad, Pakistan ', 'intlTeam': 'Australia', 'teams': 'Australia, New South Wales, Derbyshire, Cricket Australia Chairmans XI, Sydney Thunder, Queensland, Australians, Australia A, Lancashire, Rising Pune Supergiant, Glamorgan, Islamabad United, Brisbane Heat', 'DoB': 'December 18, 1986 (39 years)', 'image': 'http://i.cricketcb.com/stats/img/faceImages/6635.jpg', 'bio': "Ricky Ponting's injury at Sydney in 2011, opened the doors for the first Muslim cricketer to represent Australia at the highest level. A qualified pilot, the highs of this achievement were unparalleled. Having moved to Australia as a kid, Usman Khawaja with the bat in his hands was identified pretty early as the boy wonder.  <br/>  <br/> Honing his skills at the Valley District Cricket Club, Usman made it to the Australian under-19 squad for the 2006 World Cup. He featured in 4 games and hunted down 140 runs making an impression with his poise at the crease and crafty technique. A backlift which comes down on the ball like butter on bread, Khawaja loves to cut and pull.  <br/>  <br/> Following his debut series,  Usman travelled to Sri Lanka and South Africa without much of a success. The year of 2011 ended with a home series against the Kiwis and that also remained a low key affair for the then New batsman.  <br/>  <br/> He was dropped post that and his next tryst with the baggy green happened during the Ashes in England in 2013 after a layoff of almost 18 months. In 3 Tests, he managed only fifty and another exile from Test cricket was handed out.  <br/>  <br/> In the meanwhile, Usman had made his ODI debut at the beginning of 2013 and met a similar fate as he was dropped after three unsuccessful outings in colored clothing. Another big move that Usman had made was the move from NSW to Queensland in 2012. <br/>  <br/> His debut season at Queensland yielded 438 runs from 6 games and it got better in the succeeding season as he riled up 551 runs at an average of 50.09 in 8 games. But then occurred a career-threatening injury. He tore his ACL (Anterior Cruciate Ligament) on his left knee and was out of cricket for the next 9 months.  <br/>  <br/> Khawaja who was now aware and accustomed to the waiting game built on his patience on the sidelines. He returned to the 2015-16 season with a bang. A ton on his return game for Sydney Thunder in December 2015 made the world aware of the destruction that he can be. The T20I debut was just a mere formal announcement when the touring Indians whitewashed Australia 0-3. <br/>  <br/> All this was just before his Test comeback. Usman went onto become a permanent member of the Test team post that barring the tour to India for which he was dropped unceremoniously. But he returned for the Ashes 2017-18 and scored vital knocks over the course of the series. His couple of tons in BBL 05 ensured Sydney Thunder,  the constant wooden Spooner shocked the cricketing fraternity and ended up winning the title.  <br/>  <br/> With the bans of Steve Smith and David Warner in 2018, Khawaja was thrust with the responsibility of being Australia's premier batsman in Tests and he rose to the responsibility with elan. A marathon match-saving knock in UAE was the start of a dream run for the stylish left-hander who also stamped his class during the limited-overs tour of India in 2019. <br/>  <br/> His prolific run in that ODI series and the succeeding one against Pakistan in the UAE helped Khawaja book his maiden World Cup call-up in 2019. A hamstring injury early in the tournament, however, cut his campaign short. He recovered in time for the following Ashes series but a poor run of form saw him dropped from the side and it wouldn't be until 2022 that he'd make a comeback to the international setup.  <br/>  <br/> After a 3-year hiatus, Khawaja returned to the Test side for the 4th Ashes Test in 2021/22 and he made a strong statement after scoring twin-centuries. He followed that up with another excellent performance in Pakistan and ended as the leading run-scorer. Khawaja proved his worth once again as he finished the highly-anticipated 2023 Ashes in England as the leading run-scorer. His contributions at the top of the order were vital in helping Australia retain the Ashes after drawing the series 2-2.  <br/>  <br/> In T20s, Khawaja had a brief stint in the IPL in 2016 with the now defunct Rising Pune Supergiants. He also played a few games for the Islamabad United in the PSL and represented the Sydney Thunder in the BBL until 2022. For the 2023 season, he was signed by the Brisbane Heat and named their captain despite his slim availability due to international duties.  <br/>  <br/> <b>Interesting facts:</b> Apart from being a professional cricketer, Khawaja is also a qualified pilot. <br/>  <br/> Usman is an ex-student of Westfields Sports School, which has also produced sportsmen of the calibre of Michael Clarke (former Australia captain), soccer player Harry Kewell and world champion discus thrower Dani Samuels. <br/>  <br/> <b>By Cricbuzz Staff</b>", 'rankings': {'bat': {'testRank': '27', 'testBestRank': '4', 'odiBestRank': '15', 't20BestRank': '54'}, 'bowl': {}, 'all': {}}, 'appIndex': {'seoTitle': 'Usman Khawaja Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/6635/usman-khawaja'}, 'DoBFormat': 'December 18, 1986', 'faceImageId': 332905, 'teamNameIds': [{'teamId': '4', 'teamName': 'Australia'}, {'teamId': '104', 'teamName': 'New South Wales'}, {'teamId': '144', 'teamName': 'Derbyshire'}, {'teamId': '191', 'teamName': 'Cricket Australia Chairmans XI'}, {'teamId': '192', 'teamName': 'Sydney Thunder'}, {'teamId': '164', 'teamName': 'Queensland'}, {'teamId': '266', 'teamName': 'Australians'}, {'teamId': '79', 'teamName': 'Australia A'}, {'teamId': '143', 'teamName': 'Lancashire'}, {'teamId': '346', 'teamName': 'Rising Pune Supergiant'}, {'teamId': '149', 'teamName': 'Glamorgan'}, {'teamId': '330', 'teamName': 'Islamabad United'}, {'teamId': '193', 'teamName': 'Brisbane Heat'}], 'playerTeamIds': '4, 104, 144, 191, 192, 164, 266, 79, 143, 346, 149, 330, 193', 'intlTeamImageId': 776202, 'recentBatting': {'headers': ['Score', 'OPPN.', 'Format', 'Date'], 'rows': [{'values': ['108811', '17 & 6', 'ENG', 'Test', '04 Jan 26'], 'followUpLinkText': '/live-cricket-scores/108811/aus-vs-eng-5th-test-the-ashes-2025-26'}, {'values': ['108809', '29 & 0', 'ENG', 'Test', '26 Dec 25'], 'followUpLinkText': '/live-cricket-scores/108809/aus-vs-eng-4th-test-the-ashes-2025-26'}, {'values': ['108801', '82 & 40', 'ENG', 'Test', '17 Dec 25'], 'followUpLinkText': '/live-cricket-scores/108801/aus-vs-eng-3rd-test-the-ashes-2025-26'}, {'values': ['108787', '2 & DNB', 'ENG', 'Test', '21 Nov 25'], 'followUpLinkText': '/live-cricket-scores/108787/aus-vs-eng-1st-test-the-ashes-2025-26'}, {'values': ['114600', '23 & 14', 'WI', 'Test', '13 Jul 25'], 'followUpLinkText': '/live-cricket-scores/114600/wi-vs-aus-3rd-test-australia-tour-of-west-indies-2025'}]}, 'recentBowling': {'headers': ['Wickets', 'OPPN.', 'Format', 'Date'], 'rows': [{'values': ['40348', 'DNB & 0-3', 'PAK', 'Test', '04 Mar 22'], 'followUpLinkText': '/live-cricket-scores/40348/pak-vs-aus-1st-test-australia-tour-of-pakistan-2022'}, {'values': ['20304', '0-4 & DNB', 'IND', 'Test', '03 Jan 19'], 'followUpLinkText': '/live-cricket-scores/20304/aus-vs-ind-4th-test-india-tour-of-australia-2018-19'}, {'values': ['18375', 'DNB & 0-1', 'BAN', 'Test', '27 Aug 17'], 'followUpLinkText': '/live-cricket-scores/18375/ban-vs-aus-1st-test-australia-tour-of-bangladesh-2017'}]}}

In [170]:
player_info = response.json()

In [ ]:
player_info

{'id': '6635',
 'bat': 'Left Handed Bat',
 'bowl': 'Right-arm offbreak',
 'name': 'Usman Khawaja',
 'nickName': 'Khawaja',
 'height': '1.75 m ',
 'role': 'Batsman',
 'birthPlace': 'Islamabad, Pakistan ',
 'intlTeam': 'Australia',
 'teams': 'Australia, New South Wales, Derbyshire, Cricket Australia Chairmans XI, Sydney Thunder, Queensland, Australians, Australia A, Lancashire, Rising Pune Supergiant, Glamorgan, Islamabad United, Brisbane Heat',
 'DoB': 'December 18, 1986 (39 years)',
 'image': 'http://i.cricketcb.com/stats/img/faceImages/6635.jpg',
 'bio': "Ricky Ponting's injury at Sydney in 2011, opened the doors for the first Muslim cricketer to represent Australia at the highest level. A qualified pilot, the highs of this achievement were unparalleled. Having moved to Australia as a kid, Usman Khawaja with the bat in his hands was identified pretty early as the boy wonder.  <br/>  <br/> Honing his skills at the Valley District Cricket Club, Usman made it to the Australian under-19 squad for the 2006 World Cup. He featured in 4 games and hunted down 140 runs making an impression with his poise at the crease and crafty technique. A backlift which comes down on the ball like butter on bread, Khawaja loves to cut and pull.  <br/>  <br/> Following his debut series,  Usman travelled to Sri Lanka and South Africa without much of a success. The year of 2011 ended with a home series against the Kiwis and that also remained a low key affair for the then New batsman.  <br/>  <br/> He was dropped post that and his next tryst with the baggy green happened during the Ashes in England in 2013 after a layoff of almost 18 months. In 3 Tests, he managed only fifty and another exile from Test cricket was handed out.  <br/>  <br/> In the meanwhile, Usman had made his ODI debut at the beginning of 2013 and met a similar fate as he was dropped after three unsuccessful outings in colored clothing. Another big move that Usman had made was the move from NSW to Queensland in 2012. <br/>  <br/> His debut season at Queensland yielded 438 runs from 6 games and it got better in the succeeding season as he riled up 551 runs at an average of 50.09 in 8 games. But then occurred a career-threatening injury. He tore his ACL (Anterior Cruciate Ligament) on his left knee and was out of cricket for the next 9 months.  <br/>  <br/> Khawaja who was now aware and accustomed to the waiting game built on his patience on the sidelines. He returned to the 2015-16 season with a bang. A ton on his return game for Sydney Thunder in December 2015 made the world aware of the destruction that he can be. The T20I debut was just a mere formal announcement when the touring Indians whitewashed Australia 0-3. <br/>  <br/> All this was just before his Test comeback. Usman went onto become a permanent member of the Test team post that barring the tour to India for which he was dropped unceremoniously. But he returned for the Ashes 2017-18 and scored vital knocks over the course of the series. His couple of tons in BBL 05 ensured Sydney Thunder,  the constant wooden Spooner shocked the cricketing fraternity and ended up winning the title.  <br/>  <br/> With the bans of Steve Smith and David Warner in 2018, Khawaja was thrust with the responsibility of being Australia's premier batsman in Tests and he rose to the responsibility with elan. A marathon match-saving knock in UAE was the start of a dream run for the stylish left-hander who also stamped his class during the limited-overs tour of India in 2019. <br/>  <br/> His prolific run in that ODI series and the succeeding one against Pakistan in the UAE helped Khawaja book his maiden World Cup call-up in 2019. A hamstring injury early in the tournament, however, cut his campaign short. He recovered in time for the following Ashes series but a poor run of form saw him dropped from the side and it wouldn't be until 2022 that he'd make a comeback to the international setup.  <br/>  <br/> After a 3-year hiatus, Khawaja returned to the Test side for the 4th Ashes Test in 2021/22 and he made a strong statement after scoring twin-centuries. He followed that up with another excellent performance in Pakistan and ended as the leading run-scorer. Khawaja proved his worth once again as he finished the highly-anticipated 2023 Ashes in England as the leading run-scorer. His contributions at the top of the order were vital in helping Australia retain the Ashes after drawing the series 2-2.  <br/>  <br/> In T20s, Khawaja had a brief stint in the IPL in 2016 with the now defunct Rising Pune Supergiants. He also played a few games for the Islamabad United in the PSL and represented the Sydney Thunder in the BBL until 2022. For the 2023 season, he was signed by the Brisbane Heat and named their captain despite his slim availability due to international duties.  <br/>  <br/> <b>Interesting facts:</b> Apart from being a professional cricketer, Khawaja is also a qualified pilot. <br/>  <br/> Usman is an ex-student of Westfields Sports School, which has also produced sportsmen of the calibre of Michael Clarke (former Australia captain), soccer player Harry Kewell and world champion discus thrower Dani Samuels. <br/>  <br/> <b>By Cricbuzz Staff</b>",
 'rankings': {'bat': {'testRank': '27',
   'testBestRank': '4',
   'odiBestRank': '15',
   't20BestRank': '54'},
  'bowl': {},
  'all': {}},
 'appIndex': {'seoTitle': 'Usman Khawaja Profile - Cricbuzz | Cricbuzz.com',
  'webURL': 'http://www.cricbuzz.com/profiles/6635/usman-khawaja'},
 'DoBFormat': 'December 18, 1986',
 'faceImageId': 332905,
 'teamNameIds': [{'teamId': '4', 'teamName': 'Australia'},
  {'teamId': '104', 'teamName': 'New South Wales'},
  {'teamId': '144', 'teamName': 'Derbyshire'},
  {'teamId': '191', 'teamName': 'Cricket Australia Chairmans XI'},
  {'teamId': '192', 'teamName': 'Sydney Thunder'},
  {'teamId': '164', 'teamName': 'Queensland'},
  {'teamId': '266', 'teamName': 'Australians'},
  {'teamId': '79', 'teamName': 'Australia A'},
  {'teamId': '143', 'teamName': 'Lancashire'},
  {'teamId': '346', 'teamName': 'Rising Pune Supergiant'},
  {'teamId': '149', 'teamName': 'Glamorgan'},
  {'teamId': '330', 'teamName': 'Islamabad United'},
  {'teamId': '193', 'teamName': 'Brisbane Heat'}],
 'playerTeamIds': '4, 104, 144, 191, 192, 164, 266, 79, 143, 346, 149, 330, 193',
 'intlTeamImageId': 776202,
 'recentBatting': {'headers': ['Score', 'OPPN.', 'Format', 'Date'],
  'rows': [{'values': ['108811', '17 & 6', 'ENG', 'Test', '04 Jan 26'],
    'followUpLinkText': '/live-cricket-scores/108811/aus-vs-eng-5th-test-the-ashes-2025-26'},
   {'values': ['108809', '29 & 0', 'ENG', 'Test', '26 Dec 25'],
    'followUpLinkText': '/live-cricket-scores/108809/aus-vs-eng-4th-test-the-ashes-2025-26'},
   {'values': ['108801', '82 & 40', 'ENG', 'Test', '17 Dec 25'],
    'followUpLinkText': '/live-cricket-scores/108801/aus-vs-eng-3rd-test-the-ashes-2025-26'},
   {'values': ['108787', '2 & DNB', 'ENG', 'Test', '21 Nov 25'],
    'followUpLinkText': '/live-cricket-scores/108787/aus-vs-eng-1st-test-the-ashes-2025-26'},
   {'values': ['114600', '23 & 14', 'WI', 'Test', '13 Jul 25'],
    'followUpLinkText': '/live-cricket-scores/114600/wi-vs-aus-3rd-test-australia-tour-of-west-indies-2025'}]},
 'recentBowling': {'headers': ['Wickets', 'OPPN.', 'Format', 'Date'],
  'rows': [{'values': ['40348', 'DNB & 0-3', 'PAK', 'Test', '04 Mar 22'],
    'followUpLinkText': '/live-cricket-scores/40348/pak-vs-aus-1st-test-australia-tour-of-pakistan-2022'},
   {'values': ['20304', '0-4 & DNB', 'IND', 'Test', '03 Jan 19'],
    'followUpLinkText': '/live-cricket-scores/20304/aus-vs-ind-4th-test-india-tour-of-australia-2018-19'},
   {'values': ['18375', 'DNB & 0-1', 'BAN', 'Test', '27 Aug 17'],
    'followUpLinkText': '/live-cricket-scores/18375/ban-vs-aus-1st-test-australia-tour-of-bangladesh-2017'}]}}

In [173]:
player_info.keys()

dict_keys(['id', 'bat', 'bowl', 'name', 'nickName', 'height', 'role', 'birthPlace', 'intlTeam', 'teams', 'DoB', 'image', 'bio', 'rankings', 'appIndex', 'DoBFormat', 'faceImageId', 'teamNameIds', 'playerTeamIds', 'intlTeamImageId', 'recentBatting', 'recentBowling'])

In [175]:
cricket_details = {
    'Role': player_info['role'],
    'Batting Style' : player_info['bat'],
    'Bowling style': player_info['bowl'],
    'International Team' : player_info['intlTeam']  
 }
cricket_details

{'Role': 'Batsman',
 'Batting Style': 'Left Handed Bat',
 'Bowling style': 'Right-arm offbreak',
 'International Team': 'Australia'}

In [176]:
personal_details = {
    'Date of Birth' : player_info['DoB'],
    'Birthplace' : player_info['birthPlace'],
    'Height' : player_info['height'],
    'Nickname' : player_info['nickName']
}
personal_details

{'Date of Birth': 'December 18, 1986 (39 years)',
 'Birthplace': 'Islamabad, Pakistan ',
 'Height': '1.75 m ',
 'Nickname': 'Khawaja'}

In [177]:
teams_detail = []
for i in player_info['teamNameIds']:
    teams_detail.append(i['teamName'])
teams_detail

['Australia',
 'New South Wales',
 'Derbyshire',
 'Cricket Australia Chairmans XI',
 'Sydney Thunder',
 'Queensland',
 'Australians',
 'Australia A',
 'Lancashire',
 'Rising Pune Supergiant',
 'Glamorgan',
 'Islamabad United',
 'Brisbane Heat']

In [179]:
player_profile_link = player_info['appIndex']['webURL']
player_profile_link

'http://www.cricbuzz.com/profiles/6635/usman-khawaja'

In [180]:
# player batting info
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/8733/batting"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

player_batstat = response.json()

{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '67', '94', '72', '145']}, {'values': ['Innings', '118', '86', '68', '136']}, {'values': ['Runs', '4053', '3360', '2265', '5222']}, {'values': ['Balls', '7810', '3715', '1628', '3839']}, {'values': ['Highest', '199', '112', '110', '132']}, {'values': ['Average', '35.87', '50.91', '37.75', '46.21']}, {'values': ['SR', '51.90', '90.45', '139.13', '136.03']}, {'values': ['Not Out', '5', '20', '8', '23']}, {'values': ['Fours', '484', '259', '191', '452']}, {'values': ['Sixes', '30', '76', '99', '208']}, {'values': ['Ducks', '9', '3', '5', '4']}, {'values': ['50s', '20', '20', '22', '40']}, {'values': ['100s', '11', '8', '2', '5']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'KL Rahul Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/8733/kl-rahul'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26'}]}

In [182]:
type(player_batstat)

dict

In [183]:
player_batstat.keys()

dict_keys(['headers', 'values', 'appIndex', 'seriesSpinner'])

In [186]:
player_batstat['headers']

['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL']

In [188]:
player_batstat['values']

[{'values': ['Matches', '67', '94', '72', '145']},
 {'values': ['Innings', '118', '86', '68', '136']},
 {'values': ['Runs', '4053', '3360', '2265', '5222']},
 {'values': ['Balls', '7810', '3715', '1628', '3839']},
 {'values': ['Highest', '199', '112', '110', '132']},
 {'values': ['Average', '35.87', '50.91', '37.75', '46.21']},
 {'values': ['SR', '51.90', '90.45', '139.13', '136.03']},
 {'values': ['Not Out', '5', '20', '8', '23']},
 {'values': ['Fours', '484', '259', '191', '452']},
 {'values': ['Sixes', '30', '76', '99', '208']},
 {'values': ['Ducks', '9', '3', '5', '4']},
 {'values': ['50s', '20', '20', '22', '40']},
 {'values': ['100s', '11', '8', '2', '5']},
 {'values': ['200s', '0', '0', '0', '0']},
 {'values': ['300s', '0', '0', '0', '0']},
 {'values': ['400s', '0', '0', '0', '0']}]

In [189]:
player_batstat

{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
 'values': [{'values': ['Matches', '67', '94', '72', '145']},
  {'values': ['Innings', '118', '86', '68', '136']},
  {'values': ['Runs', '4053', '3360', '2265', '5222']},
  {'values': ['Balls', '7810', '3715', '1628', '3839']},
  {'values': ['Highest', '199', '112', '110', '132']},
  {'values': ['Average', '35.87', '50.91', '37.75', '46.21']},
  {'values': ['SR', '51.90', '90.45', '139.13', '136.03']},
  {'values': ['Not Out', '5', '20', '8', '23']},
  {'values': ['Fours', '484', '259', '191', '452']},
  {'values': ['Sixes', '30', '76', '99', '208']},
  {'values': ['Ducks', '9', '3', '5', '4']},
  {'values': ['50s', '20', '20', '22', '40']},
  {'values': ['100s', '11', '8', '2', '5']},
  {'values': ['200s', '0', '0', '0', '0']},
  {'values': ['300s', '0', '0', '0', '0']},
  {'values': ['400s', '0', '0', '0', '0']}],
 'appIndex': {'seoTitle': 'KL Rahul Profile - Cricbuzz | Cricbuzz.com',
  'webURL': 'http://www.cricbuzz.com/profiles/8733/kl-rahul'},
 'seriesSpinner': [{'seriesName': 'Career'},
  {'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26'}]}

In [190]:
import pandas as pd

In [209]:
cursor.execute("drop table if exists player_batting_stats")
cursor.execute("""
    create table player_batting_stats (
               Statistic varchar(15),
               Test float,
               ODI float,
               T20 float,
               IPL float
               )
""")

In [194]:
query = """
    insert into player_batting_stats values
    (%s,%s,%s,%s,%s)
"""

In [199]:
player_batstat

{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
 'values': [{'values': ['Matches', '67', '94', '72', '145']},
  {'values': ['Innings', '118', '86', '68', '136']},
  {'values': ['Runs', '4053', '3360', '2265', '5222']},
  {'values': ['Balls', '7810', '3715', '1628', '3839']},
  {'values': ['Highest', '199', '112', '110', '132']},
  {'values': ['Average', '35.87', '50.91', '37.75', '46.21']},
  {'values': ['SR', '51.90', '90.45', '139.13', '136.03']},
  {'values': ['Not Out', '5', '20', '8', '23']},
  {'values': ['Fours', '484', '259', '191', '452']},
  {'values': ['Sixes', '30', '76', '99', '208']},
  {'values': ['Ducks', '9', '3', '5', '4']},
  {'values': ['50s', '20', '20', '22', '40']},
  {'values': ['100s', '11', '8', '2', '5']},
  {'values': ['200s', '0', '0', '0', '0']},
  {'values': ['300s', '0', '0', '0', '0']},
  {'values': ['400s', '0', '0', '0', '0']}],
 'appIndex': {'seoTitle': 'KL Rahul Profile - Cricbuzz | Cricbuzz.com',
  'webURL': 'http://www.cricbuzz.com/profiles/8733/kl-rahul'},
 'seriesSpinner': [{'seriesName': 'Career'},
  {'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26'}]}

In [ ]:
for values in player_batstat['values']:
    row = values['values']
    cursor.execute(query,row)

In [211]:
# player bowling info

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/8733/bowling"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

player_bowlstat = response.json()

{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '67', '94', '72', '145']}, {'values': ['Innings', '0', '0', '0', '0']}, {'values': ['Balls', '0', '0', '0', '0']}, {'values': ['Runs', '0', '0', '0', '0']}, {'values': ['Maidens', '0', '0', '0', '0']}, {'values': ['Wickets', '0', '0', '0', '0']}, {'values': ['Avg', '0.0', '0.0', '0.0', '0.0']}, {'values': ['Eco', '0', '0', '0', '0']}, {'values': ['SR', '0.0', '0.0', '0.0', '0.0']}, {'values': ['BBI', '-/-', '-/-', '-/-', '-/-']}, {'values': ['BBM', '-/-', '-/-', '-/-', '-/-']}, {'values': ['4w', '0', '0', '0', '0']}, {'values': ['5w', '0', '0', '0', '0']}, {'values': ['10w', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'KL Rahul Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/8733/kl-rahul'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26'}]}

In [222]:
#query to create bowl stat table
cursor.execute("drop table if exists player_bowling_stats")
cursor.execute("""
    create table player_bowling_stats (
               Statistic varchar(15),
               Test varchar(10),
               ODI varchar(10),
               T20 varchar(10),
               IPL varchar(10)
               )
""")

# query to insert bowling statistics into the table
query = """
    insert into player_bowling_stats values
    (%s,%s,%s,%s,%s)
"""

# nested execution of query to insert every row in the table
for values in player_bowlstat['values']:
    row = [None if value == "-/-" else value for value in values['values']]
    print(row)
    cursor.execute(query,row)

['Matches', '67', '94', '72', '145']
['Innings', '0', '0', '0', '0']
['Balls', '0', '0', '0', '0']
['Runs', '0', '0', '0', '0']
['Maidens', '0', '0', '0', '0']
['Wickets', '0', '0', '0', '0']
['Avg', '0.0', '0.0', '0.0', '0.0']
['Eco', '0', '0', '0', '0']
['SR', '0.0', '0.0', '0.0', '0.0']
['BBI', None, None, None, None]
['BBM', None, None, None, None]
['4w', '0', '0', '0', '0']
['5w', '0', '0', '0', '0']
['10w', '0', '0', '0', '0']

In [223]:
# player list with player id

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/players/v1/list"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

# print(response.json())

list_data = response.json()
list_data

{'message': "Endpoint '/players/v1/list' does not exist"}

In [238]:
# search api
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/search"

querystring = {"plrN":"Rohit Sharma"}

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'player': [{'id': '576', 'name': 'Rohit Sharma', 'teamName': 'India', 'faceImageId': 616514, 'dob': '1987-04-30'}], 'category': 'Rohit Sharma'}

In [226]:
search_data = response.json()

In [227]:
search_data.keys()

dict_keys(['player', 'category'])

In [228]:
search_data['category']

'Sachin'

In [229]:
search_data['player']

[{'id': '25',
  'name': 'Sachin Tendulkar',
  'teamName': 'India',
  'faceImageId': 171004,
  'dob': '1973-04-24'},
 {'id': '1891',
  'name': 'Sachin Rana',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1984-09-18'},
 {'id': '8709',
  'name': 'Sachin Baby',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1988-12-18'},
 {'id': '8882',
  'name': 'Sachin Chaudhari',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1986-03-27'},
 {'id': '9296',
  'name': 'Sachin Hooda',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1988-08-27'},
 {'id': '9692',
  'name': 'Sachin Mohan',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1990-04-10'},
 {'id': '10308',
  'name': 'Sachin Omprakash Katariya',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1995-04-14'},
 {'id': '10602',
  'name': 'Sachin Joshi',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1984-08-07'},
 {'id': '11409',
  'name': 'Audhi Sachin',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': 'N/A'},
 {'id': '11724',
  'name': 'Sachin Gankal',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1995-03-28'},
 {'id': '11760',
  'name': 'Sachin Shinde',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1987-09-29'},
 {'id': '11840',
  'name': 'Sachin Solanki',
  'teamName': 'United Arab Emirates',
  'faceImageId': 182026,
  'dob': 'N/A'},
 {'id': '12378',
  'name': 'Sachin Rathi',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '2003-11-03'},
 {'id': '12917',
  'name': 'Sachin Sharma',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': 'N/A'},
 {'id': '13076',
  'name': 'Lal Sachin',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': 'N/A'},
 {'id': '13376',
  'name': 'Sachin Bhudia',
  'teamName': 'Kenya',
  'faceImageId': 153979,
  'dob': '1998-09-24'},
 {'id': '13691',
  'name': 'Sachintha Peiris',
  'teamName': 'Sri Lanka',
  'faceImageId': 182026,
  'dob': '1995-11-16'},
 {'id': '14905',
  'name': 'Sachin Mevada ',
  'teamName': 'India',
  'faceImageId': 169688,
  'dob': '1999-04-23'},
 {'id': '14966',
  'name': 'Sachin Madhuker Yadav',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1994-04-07'},
 {'id': '15012',
  'name': 'Sachin Wagh',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': 'N/A'},
 {'id': '15490',
  'name': 'Sachin Kumar Singh',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1997-12-25'},
 {'id': '15667',
  'name': 'Sachindu Colombage',
  'teamName': 'Sri Lanka',
  'faceImageId': 182026,
  'dob': '1998-02-21'},
 {'id': '21793',
  'name': 'Sachini Nisansala',
  'teamName': 'Sri Lanka',
  'faceImageId': 182026,
  'dob': '2001-11-10'},
 {'id': '26346',
  'name': 'Sachin Mandy Gangareddy',
  'teamName': 'Germany',
  'faceImageId': 182026,
  'dob': '1991-06-07'},
 {'id': '27039',
  'name': 'Sachini Jayasinghe',
  'teamName': 'Bahrain',
  'faceImageId': 182026,
  'dob': '1996-08-22'},
 {'id': '28199',
  'name': 'Sachin Ganpat Shinde',
  'teamName': 'Serbia',
  'faceImageId': 182026,
  'dob': '1983-11-15'},
 {'id': '29480',
  'name': 'Sachin Kumar',
  'teamName': 'Bahrain',
  'faceImageId': 182026,
  'dob': '1989-04-03'},
 {'id': '34144',
  'name': 'Suresh Sachin',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1998-01-02'},
 {'id': '46317',
  'name': 'Sachin Singh Rathi',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1987-04-30'},
 {'id': '46559',
  'name': 'Balasubramaniam Sachin',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '2003-08-30'},
 {'id': '48599',
  'name': 'Sachin Parmar',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1999-04-23'},
 {'id': '49396',
  'name': 'Sachin Kakodia',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': 'N/A'},
 {'id': '49443',
  'name': 'Sachin Malav',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': 'N/A'},
 {'id': '49499',
  'name': 'Sachin Yadav',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '2003-12-29'},
 {'id': '51798',
  'name': 'Sachin Dhas',
  'teamName': 'India',
  'faceImageId': 808195,
  'dob': '2005-02-03'},
 {'id': '52222',
  'name': 'Sachin Bhosale',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1998-01-02'},
 {'id': '52379',
  'name': 'Sachin Sharma',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1993-09-21'},
 {'id': '55312',
  'name': 'Sachin Banamali',
  'teamName': 'Singapore',
  'faceImageId': 182026,
  'dob': '1989-08-17'},
 {'id': '1424248',
  'name': 'Sachin Ravikumar',
  'teamName': 'Costa Rica',
  'faceImageId': 182026,
  'dob': '1988-05-27'},
 {'id': '1431361',
  'name': 'Sachin Gill',
  'teamName': 'Kenya',
  'faceImageId': 182026,
  'dob': '1996-12-04'},
 {'id': '1454129',
  'name': 'Sachin Pawar',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '2007-06-06'},
 {'id': '1456754',
  'name': 'Sachin B',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '2006-08-14'},
 {'id': '1460509',
  'name': 'Sachin PS',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1998-01-15'},
 {'id': '1461506',
  'name': 'Sachin Singh',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '2002-11-19'},
 {'id': '1463960',
  'name': 'Sachin Kumar',
  'teamName': 'India',
  'faceImageId': 182026,
  'dob': '1999-11-30'},
 {'id': '1465973',
  'name': 'Sachin Bhatt',
  'teamName': 'Nepal',
  'faceImageId': 182026,
  'dob': 'N/A'}]

In [231]:
len(search_data['player'])

46

In [235]:
search_list = []
for plyr in search_data['player']:
    search_list.append({
        'Name' : plyr['name'],
        'PlayerID' : plyr['id']
    })
search_list

[{'Name': 'Sachin Tendulkar', 'PlayerID': '25'},
 {'Name': 'Sachin Rana', 'PlayerID': '1891'},
 {'Name': 'Sachin Baby', 'PlayerID': '8709'},
 {'Name': 'Sachin Chaudhari', 'PlayerID': '8882'},
 {'Name': 'Sachin Hooda', 'PlayerID': '9296'},
 {'Name': 'Sachin Mohan', 'PlayerID': '9692'},
 {'Name': 'Sachin Omprakash Katariya', 'PlayerID': '10308'},
 {'Name': 'Sachin Joshi', 'PlayerID': '10602'},
 {'Name': 'Audhi Sachin', 'PlayerID': '11409'},
 {'Name': 'Sachin Gankal', 'PlayerID': '11724'},
 {'Name': 'Sachin Shinde', 'PlayerID': '11760'},
 {'Name': 'Sachin Solanki', 'PlayerID': '11840'},
 {'Name': 'Sachin Rathi', 'PlayerID': '12378'},
 {'Name': 'Sachin Sharma', 'PlayerID': '12917'},
 {'Name': 'Lal Sachin', 'PlayerID': '13076'},
 {'Name': 'Sachin Bhudia', 'PlayerID': '13376'},
 {'Name': 'Sachintha Peiris', 'PlayerID': '13691'},
 {'Name': 'Sachin Mevada ', 'PlayerID': '14905'},
 {'Name': 'Sachin Madhuker Yadav', 'PlayerID': '14966'},
 {'Name': 'Sachin Wagh', 'PlayerID': '15012'},
 {'Name': 'Sachin Kumar Singh', 'PlayerID': '15490'},
 {'Name': 'Sachindu Colombage', 'PlayerID': '15667'},
 {'Name': 'Sachini Nisansala', 'PlayerID': '21793'},
 {'Name': 'Sachin Mandy Gangareddy', 'PlayerID': '26346'},
 {'Name': 'Sachini Jayasinghe', 'PlayerID': '27039'},
 {'Name': 'Sachin Ganpat Shinde', 'PlayerID': '28199'},
 {'Name': 'Sachin Kumar', 'PlayerID': '29480'},
 {'Name': 'Suresh Sachin', 'PlayerID': '34144'},
 {'Name': 'Sachin Singh Rathi', 'PlayerID': '46317'},
 {'Name': 'Balasubramaniam Sachin', 'PlayerID': '46559'},
 {'Name': 'Sachin Parmar', 'PlayerID': '48599'},
 {'Name': 'Sachin Kakodia', 'PlayerID': '49396'},
 {'Name': 'Sachin Malav', 'PlayerID': '49443'},
 {'Name': 'Sachin Yadav', 'PlayerID': '49499'},
 {'Name': 'Sachin Dhas', 'PlayerID': '51798'},
 {'Name': 'Sachin Bhosale', 'PlayerID': '52222'},
 {'Name': 'Sachin Sharma', 'PlayerID': '52379'},
 {'Name': 'Sachin Banamali', 'PlayerID': '55312'},
 {'Name': 'Sachin Ravikumar', 'PlayerID': '1424248'},
 {'Name': 'Sachin Gill', 'PlayerID': '1431361'},
 {'Name': 'Sachin Pawar', 'PlayerID': '1454129'},
 {'Name': 'Sachin B', 'PlayerID': '1456754'},
 {'Name': 'Sachin PS', 'PlayerID': '1460509'},
 {'Name': 'Sachin Singh', 'PlayerID': '1461506'},
 {'Name': 'Sachin Kumar', 'PlayerID': '1463960'},
 {'Name': 'Sachin Bhatt', 'PlayerID': '1465973'}]

In [237]:

search_names = []
for names in search_list:
    search_names.append(names['Name'])
len(search_names)

46

In [241]:
# player info
# player personal info/profile
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/576"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

player_info = response.json()

# cricketing information
cricket_details = {
    'Role': player_info['role'],
    'Batting Style' : player_info['bat'],
    'Bowling style': player_info['bowl'],
    'International Team' : player_info['intlTeam']  
 }

# personal details
personal_details = {
    'Date of Birth' : player_info['DoB'],
    'Birthplace' : player_info['birthPlace'],
    'Height' : player_info.get('heightr', 'Height not available'),
    'Nickname' : player_info['nickName']
}

# teams played for
teams_detail = []
for i in player_info['teamNameIds']:
    teams_detail.append(i['teamName'])

# profile link
player_profile_link = player_info['appIndex']['webURL']

{'id': '576', 'bat': 'Right Handed Bat', 'bowl': 'Right-arm offbreak', 'name': 'Rohit Sharma', 'nickName': 'Rohit Sharma', 'role': 'Batsman', 'birthPlace': 'Nagpur, Maharashtra', 'intlTeam': 'India', 'teams': 'India, Deccan Chargers, India A, India Green, India U19, Mumbai, Mumbai Indians, Indians, India Blue, Board Presidents XI', 'DoB': 'April 30, 1987 (38 years)', 'image': 'http://i.cricketcb.com/stats/img/faceImages/576.jpg', 'bio': "Talent – an apparently heartening term that has followed Rohit Sharma around like a shadow; even haunted him at times. It seems to be a burden that the cricketing fraternity has enforced upon him and, after more than a decade in the national setting, he has been weighed down by the label.  <br/>  <br/> Harsha Bhogle spoke of whispers in the domestic circuit; of coaches and scouts spotting the effortless, free-flowing stroke-play of a Mumbai teenager. Having cruised through first-class cricket, with an average well above 50, he shot to the limelight when he scored a brisk unbeaten triple-hundred at the Ranji level. <br/>  <br/> It all began after an injury to an in-form Yuvraj Singh in the 2007 World T20, when Rohit was called upon as a last-minute emergency replacement to play a league game against the hosts. After a lacklustre start to the Indian innings, the 20-year-old strode out into Kingsmead and stroked his way to a fluent half-century against the likes of Pollock, Ntini and Morkel as though he were having a net session. He showed startling maturity under pressure to survive till the end of the innings, escorting India to a respectable total that they ultimately defended, knocking South Africa out of the tournament in their own backyard. <br/>  <br/> Indian cricket-frenzy fans have a thing for like-for-like replacements. More specifically, they have a thing for spotting similarities with the days gone by. With an incessant obsession for stats, there lies a cricketing romantic who is struck by nostalgia when manifested with the idea of an elegant-looking batsman with free-flowing batting style from Mumbai. That's right – Rohit Sharma was touted to be the Great Sachin Tendulkar's long-destined successor at number 4 in the Test batting line-up. After all, it added up: so much time to play his shots, effortless stroke-making capabilities even against express pace, and a wide repertoire of shots. This had to be God's gift to cricket in the post-Tendulkar era, right? <br/>  <br/> Rohit was subsequently picked for the ODI team on a selection whim after his burst of vital performances in the World T20 and his impressive Ranji Trophy record. He made an impression in the CB series Down Under, playing some crucial cameos against stalwarts like Brett Lee and Stuart Clark, and a more-than-competent Sri Lankan attack. These inspired away performances in the World T20 and the CB series caught the eye of the selectors, and warranted him an extended run with the limited-overs side. <br/>  <br/> However, inconsistency and a knack of gifting his wicket away meant that he struggled to cement his spot in the side. Critics pointed out that he had too many shots for the same ball, and this meant that shot selection was becoming a bit of an issue for him. Furthermore, several experts spotted that he had trouble playing the short ball since his stance was too side-on and that he had no back-and-across trigger movement. His pedestrian batting average of 22 to go with a string of low scores and unconverted starts meant that he failed to cement a spot in the side for the 2011 Cricket World Cup squad...  <br/>  <br/> Looking back at his career, Rohit Sharma would have the Indian Premier League to thank for keeping him in the reckoning and not being discarded liked several other young and talented cricketers who burst forth into national reckoning but couldn't make it big at the highest level. In the first two years of the IPL, his performance stood out, as he made over 350 runs each time for the Deccan Chargers and proved his worth to his franchise. He was then transferred to the Mumbai Indians franchise in 2011 and has been one of their most consistent batsmen over the years. <br/>  <br/> Rohit continued to oscillate in and out of the Indian eleven without being able to establish himself in the side, having been given ample opportunities despite a well-established Indian middle-order. Alas, after making it to the Playing XI for the Nagpur Test against South Africa in 2010, he was lamentably injured in a warm-up football game after coming heart-breakingly close to receiving the coveted India cap. He was subsequently ruled out of the series in a gut-wrenching turn of events, and wouldn't get another opportunity to prove his Test credentials for another 4 years. <br/>  <br/> Rohit's proved himself on the IPL stage again in 2011 and made a comeback into the ODI squad for the tour of West Indies where he scored three half-centuries in five matches. However, this turned out to be another false dawn as he followed it up with a string of low scores in the CB series in Australia and a nightmare tour of Sri Lanka with just 14 runs from 5 innings, including 2 ducks. He had already been given a more-than-extended run and was starting to build an unenviable reputation of a frustratingly fascinating player.  <br/>  <br/> The generally fickle selectors, surprisingly, continued to back him. Eventually, due to lack of contenders for the opener's spot in ODIs, MS Dhoni, the Indian captain, decided to try him as an opener in the limited-overs' format.  <br/>  <br/> The term 'masterstroke' has always been a bit of an enigma, historically being used in a vague, result-based manner. The move to promote Rohit Sharma to the top of the order has paid enough dividends for it to be termed a masterstroke – India had finally found a candidate for the opener's spot, and Rohit seemed to have finally scripted a turnaround after almost 5 years in and out of the side. With enough time to play himself in as an opener, Rohit and Dhawan formed a formidable opening partnership, playing a substantial role in India's unbeaten and successful Champions' Trophy campaign in 2013. Still, the talented tag followed him around, and Rohit – at long last – started to live up to it. In a run-fest of an ODI series against Australia, Rohit scored 491 runs in 6 outings, culminating in a violent 209 in the deciding ODI in Bangalore, joining a crème de la crème list of ODI double-centurions that comprised of Sachin Tendulkar and Virender Sehwag. <br/>  <br/> With the retirements of stalwarts like Rahul Dravid and VVS Laxman, a new crop of Test batsmen needed to be honed, and opened up new avenues in the team. Rohit, at long last, earned the oh-so-desirable India Test cap against West Indies in the first Test at the Eden Gardens in his fabled 'predecessor's' farewell series. Rohit wasn't going to let this opportunity go begging and embraced the Test arena immediately, easing his way to a typically Rohit-esque 177 in his debut innings; a vital innings in the context of the match, dragging the momentum India's way. He reinforced his metaphorical statement to the selectors with an unbeaten 111 in the following Test, enchanting a tearful Wankhede in Sachin Tendulkar's farewell Test match and taming the West Indian bowling attack. After an injury-break, Rohit, as if to make up for lost time, ripped apart a hapless Sri Lankan attack on his way to a jaw-dropping 264 – wait for it – <i>in an ODI</i> at the Eden Gardens, making thirteen runs more than the entire Lankan team managed.  <br/>  <br/> However, a worrying trend continued after the selectors picked him for the tour to Australia after his Kolkata epic: that of getting picked for away Test tours based on white ball performances in less testing conditions. He was picked after his 209 for the South Africa tour in late 2013 and looked technically inept in seaming conditions, committing to the line of the ball too early and playing as if it were a true wicket. His strength of picking the length early in ODIs was turning into a curse in Test matches. Similarly, having been picked for the tour of Australia on the back of his 264, he made just one fifty in 6 innings, looking completely at sea against the pace-heavy Australian attack, continuously playing away from the body, trying to hit through the line in conditions conducive to lateral movement and showing poor off-stump awareness.  <br/>  <br/> Nevertheless he continued his golden run in ODIs, ending the 2015 World Cup campaign as India's second-highest run-scorer with a total of 330 runs, including a hundred in the quarter-final against Bangladesh to go with two fifties. <br/>  <br/> Rohit, the ODI player, finally delivered a break-through performance as an opener with an impeccable limited-overs tour of Australia in early 2016, making back-to-back hundreds and a 99 in the series and finally answering the faith of the selectors and his captain. He had become a one-day monster who developed a habit - started his ODI innings in a slow and steady manner, but could really lay into any bowling attack once he was in. With an extended home season, Rohit continued to get chances in Tests and showed vast improvement in his technique, playing closer to his body and preventing his ODI game to amalgamate with his more air-tight Test technique. With four fifties and a hundred in his last 5 innings, he capped off a fruitful home season with an unprecedented third ODI double-century against a woebegone Sri Lankan attack.  <br/>  <br/> With gifted technique and languid elegance as his allies, Rohit found a route to consistency and has been a regular feature in the Test set-up since 2018. His white-ball, prowess, however witnessed yet another high in 2019 as he ended up as the highest run-getter in the ODI World Cup in England with 648 runs from 9 games at an average of 81 that included 67 fours and 14 sixes. Just over a month ahead of the 2021 T20 World Cup, Virat Kohli stepped down as T20I captain, and there were no qualms about who the next skipper was going to be, with Rohit Sharma being the ultimate favourite. A couple of months later, BCCI named Rohit as the ODI skipper for the tour of South Africa 2021-22. Having missed the entire tour due to injury, Rohit assumed the full-time captaincy in India's 1000th ODI in Ahmedabad (vs West Indies on 06 February 2022). A couple of weeks later, and on expected lines, Rohit took over the Test captaincy from Kohli and led India to series wins over Sri Lanka and Bangladesh (drew series with England in England 2021-22) thus far (As of March 2023). <br/>  <br/> Rohit was India’s skipper in the 2022 T20I World Cup, where his team was brutally outplayed by England in the semi-final. Post that defeat, he took the mantle on himself to change the team culture and instill a brand of fearless cricket amongst his boys. Rohit led from the front in the 2023 ODI World Cup, giving the team blazing starts in most games. He scored quick runs without caring too much for personal records as India cruised through to the finals, unbeaten. They were unfortunately beaten in the final by Australia. <br/>  <br/> Rohit Sharma got his chance at redemption though a few months later in the T20I World Cup. He was instrumental for India in a group game against Australia and then in the semi-final against England where he scored big runs to drive the opposition out of the game. It was under his captaincy that India eventually managed to break their 11 year trophy jinx as they won the 2024 T20I World Cup in Barbados. Rohit Sharma subsequently retired from T20Is after winning the World Cup. Post the World Cup, Rohit had a bit of a slump in form, especially in Test cricket as India suffered a 3-0 home whitewash at the hands of New Zealand and then lost the Border Gavaskar Series as well. He famously dropped himself from the side despite being skipper for the final Sydney Test of the BGT. <br/>  <br/> Rohit found form once again when white ball cricket resumed, as he scored a superb hundred against England in a home bilateral series. He followed that form into the Champions Trophy, reserving his best for the final where he top scored for India to claim the Man of the Match and also lead the team to a second ICC trophy in the span of nine months. <br/>  <br/> In April, 2025, while still the captain of the Test team, Rohit Sharma announced his retirement from Test cricket, drawing the curtains on a career that spanned 12 years.      <br/>  <br/>  <br/> <b>IPL through the years</b> <br/>  <br/> The IPL has done a lot for Rohit Sharma. When he was a young, talented batsman who struggled with consistency, the IPL gave him a ticket to stay relevant, and he grabbed it with both hands during his time with the Deccan Chargers from 2008-2010, scoring over 350 runs in each of the three seasons. Then the IPL took him back to his home of Mumbai, and Rohit couldn't have been happier. His statistics with the Mumbai Indians got progressively better from 2011-13, and eventually his best IPL season in 2013 - where he finished the tournament with 538 runs - coincided with MI's maiden title win.  <br/>  <br/> And finally, the IPL helped unveil a leadership side to Rohit Sharma that has impressed a lot of people. Rohit led MI to five IPL titles which is an amazing accomplishment.  Rohit is also among the all-time top run-scorers in the IPL, only behind Virat Kohli and Shikhar Dhawan. <br/>  <br/> In 2024, Rohit was removed as captain by Mumbai Indians with a returning Hardik Pandya taking over captaincy after being transferred in from Gujarat Titans. Rohit Sharma was retained by the franchise ahead of the mega auction for IPL 2025.  <br/>  <br/> By <b>Rishi Roy</b> and <b>Saurabh Shankar</b>", 'rankings': {'bat': {'odiRank': '4', 'testBestRank': '5', 'odiBestRank': '1', 't20BestRank': '7'}, 'bowl': {'testBestRank': '87', 't20BestRank': '94'}, 'all': {}}, 'appIndex': {'seoTitle': 'Rohit Sharma Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/576/rohit-sharma'}, 'DoBFormat': 'April 30, 1987', 'faceImageId': 616514, 'teamNameIds': [{'teamId': '2', 'teamName': 'India'}, {'teamId': '60', 'teamName': 'Deccan Chargers'}, {'teamId': '78', 'teamName': 'India A'}, {'teamId': '20', 'teamName': 'India Green'}, {'teamId': '54', 'teamName': 'India U19'}, {'teamId': '95', 'teamName': 'Mumbai'}, {'teamId': '62', 'teamName': 'Mumbai Indians'}, {'teamId': '276', 'teamName': 'Indians'}, {'teamId': '36', 'teamName': 'India Blue'}, {'teamId': '86', 'teamName': 'Board Presidents XI'}], 'playerTeamIds': '2, 60, 78, 20, 54, 95, 62, 276, 36, 86', 'intlTeamImageId': 776162, 'recentBatting': {'headers': ['Score', 'OPPN.', 'Format', 'Date'], 'rows': [{'values': ['121378', '11(13)', 'NZ', 'ODI', '18 Jan 26'], 'followUpLinkText': '/live-cricket-scores/121378/ind-vs-nz-3rd-odi-new-zealand-tour-of-india-2026'}, {'values': ['121373', '24(38)', 'NZ', 'ODI', '14 Jan 26'], 'followUpLinkText': '/live-cricket-scores/121373/ind-vs-nz-2nd-odi-new-zealand-tour-of-india-2026'}, {'values': ['121367', '26(29)', 'NZ', 'ODI', '11 Jan 26'], 'followUpLinkText': '/live-cricket-scores/121367/ind-vs-nz-1st-odi-new-zealand-tour-of-india-2026'}, {'values': ['117404', '75(73)', 'RSA', 'ODI', '06 Dec 25'], 'followUpLinkText': '/live-cricket-scores/117404/ind-vs-rsa-3rd-odi-south-africa-tour-of-india-2025'}, {'values': ['117398', '14(8)', 'RSA', 'ODI', '03 Dec 25'], 'followUpLinkText': '/live-cricket-scores/117398/ind-vs-rsa-2nd-odi-south-africa-tour-of-india-2025'}]}, 'recentBowling': {'headers': ['Wickets', 'OPPN.', 'Format', 'Date'], 'rows': [{'values': ['101550', '0-11', 'SL', 'ODI', '04 Aug 24'], 'followUpLinkText': '/live-cricket-scores/101550/sl-vs-ind-2nd-odi-india-tour-of-sri-lanka-2024'}, {'values': ['75623', '1-7', 'NED', 'ODI', '12 Nov 23'], 'followUpLinkText': '/live-cricket-scores/75623/ind-vs-ned-45th-match-icc-cricket-world-cup-2023'}, {'values': ['37572', '0-4', 'KKR', 'T20', '23 Sep 21'], 'followUpLinkText': '/live-cricket-scores/37572/mi-vs-kkr-34th-match-indian-premier-league-2021'}, {'values': ['35627', '0-9', 'KKR', 'T20', '13 Apr 21'], 'followUpLinkText': '/live-cricket-scores/35627/kkr-vs-mi-5th-match-indian-premier-league-2021'}, {'values': ['32253', '0-7 & DNB', 'ENG', 'Test', '05 Feb 21'], 'followUpLinkText': '/live-cricket-scores/32253/ind-vs-eng-1st-test-england-tour-of-india-2021'}]}}

In [240]:
player_info

{'id': '576',
 'bat': 'Right Handed Bat',
 'bowl': 'Right-arm offbreak',
 'name': 'Rohit Sharma',
 'nickName': 'Rohit Sharma',
 'role': 'Batsman',
 'birthPlace': 'Nagpur, Maharashtra',
 'intlTeam': 'India',
 'teams': 'India, Deccan Chargers, India A, India Green, India U19, Mumbai, Mumbai Indians, Indians, India Blue, Board Presidents XI',
 'DoB': 'April 30, 1987 (38 years)',
 'image': 'http://i.cricketcb.com/stats/img/faceImages/576.jpg',
 'bio': "Talent – an apparently heartening term that has followed Rohit Sharma around like a shadow; even haunted him at times. It seems to be a burden that the cricketing fraternity has enforced upon him and, after more than a decade in the national setting, he has been weighed down by the label.  <br/>  <br/> Harsha Bhogle spoke of whispers in the domestic circuit; of coaches and scouts spotting the effortless, free-flowing stroke-play of a Mumbai teenager. Having cruised through first-class cricket, with an average well above 50, he shot to the limelight when he scored a brisk unbeaten triple-hundred at the Ranji level. <br/>  <br/> It all began after an injury to an in-form Yuvraj Singh in the 2007 World T20, when Rohit was called upon as a last-minute emergency replacement to play a league game against the hosts. After a lacklustre start to the Indian innings, the 20-year-old strode out into Kingsmead and stroked his way to a fluent half-century against the likes of Pollock, Ntini and Morkel as though he were having a net session. He showed startling maturity under pressure to survive till the end of the innings, escorting India to a respectable total that they ultimately defended, knocking South Africa out of the tournament in their own backyard. <br/>  <br/> Indian cricket-frenzy fans have a thing for like-for-like replacements. More specifically, they have a thing for spotting similarities with the days gone by. With an incessant obsession for stats, there lies a cricketing romantic who is struck by nostalgia when manifested with the idea of an elegant-looking batsman with free-flowing batting style from Mumbai. That's right – Rohit Sharma was touted to be the Great Sachin Tendulkar's long-destined successor at number 4 in the Test batting line-up. After all, it added up: so much time to play his shots, effortless stroke-making capabilities even against express pace, and a wide repertoire of shots. This had to be God's gift to cricket in the post-Tendulkar era, right? <br/>  <br/> Rohit was subsequently picked for the ODI team on a selection whim after his burst of vital performances in the World T20 and his impressive Ranji Trophy record. He made an impression in the CB series Down Under, playing some crucial cameos against stalwarts like Brett Lee and Stuart Clark, and a more-than-competent Sri Lankan attack. These inspired away performances in the World T20 and the CB series caught the eye of the selectors, and warranted him an extended run with the limited-overs side. <br/>  <br/> However, inconsistency and a knack of gifting his wicket away meant that he struggled to cement his spot in the side. Critics pointed out that he had too many shots for the same ball, and this meant that shot selection was becoming a bit of an issue for him. Furthermore, several experts spotted that he had trouble playing the short ball since his stance was too side-on and that he had no back-and-across trigger movement. His pedestrian batting average of 22 to go with a string of low scores and unconverted starts meant that he failed to cement a spot in the side for the 2011 Cricket World Cup squad...  <br/>  <br/> Looking back at his career, Rohit Sharma would have the Indian Premier League to thank for keeping him in the reckoning and not being discarded liked several other young and talented cricketers who burst forth into national reckoning but couldn't make it big at the highest level. In the first two years of the IPL, his performance stood out, as he made over 350 runs each time for the Deccan Chargers and proved his worth to his franchise. He was then transferred to the Mumbai Indians franchise in 2011 and has been one of their most consistent batsmen over the years. <br/>  <br/> Rohit continued to oscillate in and out of the Indian eleven without being able to establish himself in the side, having been given ample opportunities despite a well-established Indian middle-order. Alas, after making it to the Playing XI for the Nagpur Test against South Africa in 2010, he was lamentably injured in a warm-up football game after coming heart-breakingly close to receiving the coveted India cap. He was subsequently ruled out of the series in a gut-wrenching turn of events, and wouldn't get another opportunity to prove his Test credentials for another 4 years. <br/>  <br/> Rohit's proved himself on the IPL stage again in 2011 and made a comeback into the ODI squad for the tour of West Indies where he scored three half-centuries in five matches. However, this turned out to be another false dawn as he followed it up with a string of low scores in the CB series in Australia and a nightmare tour of Sri Lanka with just 14 runs from 5 innings, including 2 ducks. He had already been given a more-than-extended run and was starting to build an unenviable reputation of a frustratingly fascinating player.  <br/>  <br/> The generally fickle selectors, surprisingly, continued to back him. Eventually, due to lack of contenders for the opener's spot in ODIs, MS Dhoni, the Indian captain, decided to try him as an opener in the limited-overs' format.  <br/>  <br/> The term 'masterstroke' has always been a bit of an enigma, historically being used in a vague, result-based manner. The move to promote Rohit Sharma to the top of the order has paid enough dividends for it to be termed a masterstroke – India had finally found a candidate for the opener's spot, and Rohit seemed to have finally scripted a turnaround after almost 5 years in and out of the side. With enough time to play himself in as an opener, Rohit and Dhawan formed a formidable opening partnership, playing a substantial role in India's unbeaten and successful Champions' Trophy campaign in 2013. Still, the talented tag followed him around, and Rohit – at long last – started to live up to it. In a run-fest of an ODI series against Australia, Rohit scored 491 runs in 6 outings, culminating in a violent 209 in the deciding ODI in Bangalore, joining a crème de la crème list of ODI double-centurions that comprised of Sachin Tendulkar and Virender Sehwag. <br/>  <br/> With the retirements of stalwarts like Rahul Dravid and VVS Laxman, a new crop of Test batsmen needed to be honed, and opened up new avenues in the team. Rohit, at long last, earned the oh-so-desirable India Test cap against West Indies in the first Test at the Eden Gardens in his fabled 'predecessor's' farewell series. Rohit wasn't going to let this opportunity go begging and embraced the Test arena immediately, easing his way to a typically Rohit-esque 177 in his debut innings; a vital innings in the context of the match, dragging the momentum India's way. He reinforced his metaphorical statement to the selectors with an unbeaten 111 in the following Test, enchanting a tearful Wankhede in Sachin Tendulkar's farewell Test match and taming the West Indian bowling attack. After an injury-break, Rohit, as if to make up for lost time, ripped apart a hapless Sri Lankan attack on his way to a jaw-dropping 264 – wait for it – <i>in an ODI</i> at the Eden Gardens, making thirteen runs more than the entire Lankan team managed.  <br/>  <br/> However, a worrying trend continued after the selectors picked him for the tour to Australia after his Kolkata epic: that of getting picked for away Test tours based on white ball performances in less testing conditions. He was picked after his 209 for the South Africa tour in late 2013 and looked technically inept in seaming conditions, committing to the line of the ball too early and playing as if it were a true wicket. His strength of picking the length early in ODIs was turning into a curse in Test matches. Similarly, having been picked for the tour of Australia on the back of his 264, he made just one fifty in 6 innings, looking completely at sea against the pace-heavy Australian attack, continuously playing away from the body, trying to hit through the line in conditions conducive to lateral movement and showing poor off-stump awareness.  <br/>  <br/> Nevertheless he continued his golden run in ODIs, ending the 2015 World Cup campaign as India's second-highest run-scorer with a total of 330 runs, including a hundred in the quarter-final against Bangladesh to go with two fifties. <br/>  <br/> Rohit, the ODI player, finally delivered a break-through performance as an opener with an impeccable limited-overs tour of Australia in early 2016, making back-to-back hundreds and a 99 in the series and finally answering the faith of the selectors and his captain. He had become a one-day monster who developed a habit - started his ODI innings in a slow and steady manner, but could really lay into any bowling attack once he was in. With an extended home season, Rohit continued to get chances in Tests and showed vast improvement in his technique, playing closer to his body and preventing his ODI game to amalgamate with his more air-tight Test technique. With four fifties and a hundred in his last 5 innings, he capped off a fruitful home season with an unprecedented third ODI double-century against a woebegone Sri Lankan attack.  <br/>  <br/> With gifted technique and languid elegance as his allies, Rohit found a route to consistency and has been a regular feature in the Test set-up since 2018. His white-ball, prowess, however witnessed yet another high in 2019 as he ended up as the highest run-getter in the ODI World Cup in England with 648 runs from 9 games at an average of 81 that included 67 fours and 14 sixes. Just over a month ahead of the 2021 T20 World Cup, Virat Kohli stepped down as T20I captain, and there were no qualms about who the next skipper was going to be, with Rohit Sharma being the ultimate favourite. A couple of months later, BCCI named Rohit as the ODI skipper for the tour of South Africa 2021-22. Having missed the entire tour due to injury, Rohit assumed the full-time captaincy in India's 1000th ODI in Ahmedabad (vs West Indies on 06 February 2022). A couple of weeks later, and on expected lines, Rohit took over the Test captaincy from Kohli and led India to series wins over Sri Lanka and Bangladesh (drew series with England in England 2021-22) thus far (As of March 2023). <br/>  <br/> Rohit was India’s skipper in the 2022 T20I World Cup, where his team was brutally outplayed by England in the semi-final. Post that defeat, he took the mantle on himself to change the team culture and instill a brand of fearless cricket amongst his boys. Rohit led from the front in the 2023 ODI World Cup, giving the team blazing starts in most games. He scored quick runs without caring too much for personal records as India cruised through to the finals, unbeaten. They were unfortunately beaten in the final by Australia. <br/>  <br/> Rohit Sharma got his chance at redemption though a few months later in the T20I World Cup. He was instrumental for India in a group game against Australia and then in the semi-final against England where he scored big runs to drive the opposition out of the game. It was under his captaincy that India eventually managed to break their 11 year trophy jinx as they won the 2024 T20I World Cup in Barbados. Rohit Sharma subsequently retired from T20Is after winning the World Cup. Post the World Cup, Rohit had a bit of a slump in form, especially in Test cricket as India suffered a 3-0 home whitewash at the hands of New Zealand and then lost the Border Gavaskar Series as well. He famously dropped himself from the side despite being skipper for the final Sydney Test of the BGT. <br/>  <br/> Rohit found form once again when white ball cricket resumed, as he scored a superb hundred against England in a home bilateral series. He followed that form into the Champions Trophy, reserving his best for the final where he top scored for India to claim the Man of the Match and also lead the team to a second ICC trophy in the span of nine months. <br/>  <br/> In April, 2025, while still the captain of the Test team, Rohit Sharma announced his retirement from Test cricket, drawing the curtains on a career that spanned 12 years.      <br/>  <br/>  <br/> <b>IPL through the years</b> <br/>  <br/> The IPL has done a lot for Rohit Sharma. When he was a young, talented batsman who struggled with consistency, the IPL gave him a ticket to stay relevant, and he grabbed it with both hands during his time with the Deccan Chargers from 2008-2010, scoring over 350 runs in each of the three seasons. Then the IPL took him back to his home of Mumbai, and Rohit couldn't have been happier. His statistics with the Mumbai Indians got progressively better from 2011-13, and eventually his best IPL season in 2013 - where he finished the tournament with 538 runs - coincided with MI's maiden title win.  <br/>  <br/> And finally, the IPL helped unveil a leadership side to Rohit Sharma that has impressed a lot of people. Rohit led MI to five IPL titles which is an amazing accomplishment.  Rohit is also among the all-time top run-scorers in the IPL, only behind Virat Kohli and Shikhar Dhawan. <br/>  <br/> In 2024, Rohit was removed as captain by Mumbai Indians with a returning Hardik Pandya taking over captaincy after being transferred in from Gujarat Titans. Rohit Sharma was retained by the franchise ahead of the mega auction for IPL 2025.  <br/>  <br/> By <b>Rishi Roy</b> and <b>Saurabh Shankar</b>",
 'rankings': {'bat': {'odiRank': '4',
   'testBestRank': '5',
   'odiBestRank': '1',
   't20BestRank': '7'},
  'bowl': {'testBestRank': '87', 't20BestRank': '94'},
  'all': {}},
 'appIndex': {'seoTitle': 'Rohit Sharma Profile - Cricbuzz | Cricbuzz.com',
  'webURL': 'http://www.cricbuzz.com/profiles/576/rohit-sharma'},
 'DoBFormat': 'April 30, 1987',
 'faceImageId': 616514,
 'teamNameIds': [{'teamId': '2', 'teamName': 'India'},
  {'teamId': '60', 'teamName': 'Deccan Chargers'},
  {'teamId': '78', 'teamName': 'India A'},
  {'teamId': '20', 'teamName': 'India Green'},
  {'teamId': '54', 'teamName': 'India U19'},
  {'teamId': '95', 'teamName': 'Mumbai'},
  {'teamId': '62', 'teamName': 'Mumbai Indians'},
  {'teamId': '276', 'teamName': 'Indians'},
  {'teamId': '36', 'teamName': 'India Blue'},
  {'teamId': '86', 'teamName': 'Board Presidents XI'}],
 'playerTeamIds': '2, 60, 78, 20, 54, 95, 62, 276, 36, 86',
 'intlTeamImageId': 776162,
 'recentBatting': {'headers': ['Score', 'OPPN.', 'Format', 'Date'],
  'rows': [{'values': ['121378', '11(13)', 'NZ', 'ODI', '18 Jan 26'],
    'followUpLinkText': '/live-cricket-scores/121378/ind-vs-nz-3rd-odi-new-zealand-tour-of-india-2026'},
   {'values': ['121373', '24(38)', 'NZ', 'ODI', '14 Jan 26'],
    'followUpLinkText': '/live-cricket-scores/121373/ind-vs-nz-2nd-odi-new-zealand-tour-of-india-2026'},
   {'values': ['121367', '26(29)', 'NZ', 'ODI', '11 Jan 26'],
    'followUpLinkText': '/live-cricket-scores/121367/ind-vs-nz-1st-odi-new-zealand-tour-of-india-2026'},
   {'values': ['117404', '75(73)', 'RSA', 'ODI', '06 Dec 25'],
    'followUpLinkText': '/live-cricket-scores/117404/ind-vs-rsa-3rd-odi-south-africa-tour-of-india-2025'},
   {'values': ['117398', '14(8)', 'RSA', 'ODI', '03 Dec 25'],
    'followUpLinkText': '/live-cricket-scores/117398/ind-vs-rsa-2nd-odi-south-africa-tour-of-india-2025'}]},
 'recentBowling': {'headers': ['Wickets', 'OPPN.', 'Format', 'Date'],
  'rows': [{'values': ['101550', '0-11', 'SL', 'ODI', '04 Aug 24'],
    'followUpLinkText': '/live-cricket-scores/101550/sl-vs-ind-2nd-odi-india-tour-of-sri-lanka-2024'},
   {'values': ['75623', '1-7', 'NED', 'ODI', '12 Nov 23'],
    'followUpLinkText': '/live-cricket-scores/75623/ind-vs-ned-45th-match-icc-cricket-world-cup-2023'},
   {'values': ['37572', '0-4', 'KKR', 'T20', '23 Sep 21'],
    'followUpLinkText': '/live-cricket-scores/37572/mi-vs-kkr-34th-match-indian-premier-league-2021'},
   {'values': ['35627', '0-9', 'KKR', 'T20', '13 Apr 21'],
    'followUpLinkText': '/live-cricket-scores/35627/kkr-vs-mi-5th-match-indian-premier-league-2021'},
   {'values': ['32253', '0-7 & DNB', 'ENG', 'Test', '05 Feb 21'],
    'followUpLinkText': '/live-cricket-scores/32253/ind-vs-eng-1st-test-england-tour-of-india-2021'}]}}

In [242]:
personal_details

{'Date of Birth': 'April 30, 1987 (38 years)',
 'Birthplace': 'Nagpur, Maharashtra',
 'Height': 'Height not available',
 'Nickname': 'Rohit Sharma'}

In [332]:
# Question 1
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/teams/v1/2/players"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

In [ ]:
team_player_data = response.json()
team_player_data

In [244]:
team_player_data.keys()

dict_keys(['player'])

In [258]:
# full name, role, bat style, ball style
tp_data = team_player_data.get('player', [])
tp_data

[{'name': 'BATSMEN', 'imageId': 174146},
 {'id': '11808',
  'name': 'Shubman Gill',
  'imageId': 616515,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '13940',
  'name': 'Yashasvi Jaiswal',
  'imageId': 591942,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '13866',
  'name': 'Sai Sudharsan',
  'imageId': 717782,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '576',
  'name': 'Rohit Sharma',
  'imageId': 616514,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '1413',
  'name': 'Virat Kohli',
  'imageId': 616517,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm medium'},
 {'id': '7915',
  'name': 'Suryakumar Yadav',
  'imageId': 846028,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '9428',
  'name': 'Shreyas Iyer',
  'imageId': 616518,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '10896',
  'name': 'Rinku Singh',
  'imageId': 846030,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '14504',
  'name': 'Tilak Varma',
  'imageId': 846029,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '11813',
  'name': 'Ruturaj Gaikwad',
  'imageId': 781069,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '10636',
  'name': 'Rajat Patidar',
  'imageId': 760758,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '9429',
  'name': 'Sarfaraz Khan',
  'imageId': 591955,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '9716',
  'name': 'Abhimanyu Easwaran',
  'imageId': 591956,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '8257',
  'name': 'Karun Nair',
  'imageId': 717781,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'name': 'ALL ROUNDER', 'imageId': 174146},
 {'id': '14701',
  'name': 'Nitish Kumar Reddy',
  'imageId': 591947,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '9647',
  'name': 'Hardik Pandya',
  'imageId': 846032,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '11195',
  'name': 'Shivam Dube',
  'imageId': 846034,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm medium'},
 {'id': '12086',
  'name': 'Abhishek Sharma',
  'imageId': 846031,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm orthodox'},
 {'id': '587',
  'name': 'Ravindra Jadeja',
  'imageId': 616520,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm orthodox'},
 {'id': '8683',
  'name': 'Shardul Thakur',
  'imageId': 352487,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '10945',
  'name': 'Washington Sundar',
  'imageId': 616522,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '8808',
  'name': 'Axar Patel',
  'imageId': 846033,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm orthodox'},
 {'name': 'WICKET KEEPER', 'imageId': 174146},
 {'id': '10744',
  'name': 'Rishabh Pant',
  'imageId': 616524,
  'battingStyle': 'Left-hand bat'},
 {'id': '8733',
  'name': 'KL Rahul',
  'imageId': 616523,
  'battingStyle': 'Right-hand bat'},
 {'id': '14691',
  'name': 'Dhruv Jurel',
  'imageId': 591954,
  'battingStyle': 'Right-hand bat'},
 {'id': '8271',
  'name': 'Sanju Samson',
  'imageId': 846035,
  'battingStyle': 'Right-hand bat'},
 {'id': '10276',
  'name': 'Ishan Kishan',
  'imageId': 846036,
  'battingStyle': 'Left-hand bat'},
 {'name': 'BOWLER', 'imageId': 174146},
 {'id': '10808',
  'name': 'Mohammed Siraj',
  'imageId': 591952,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast'},
 {'id': '9311',
  'name': 'Jasprit Bumrah',
  'imageId': 846037,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast'},
 {'id': '10551',
  'name': 'Prasidh Krishna',
  'imageId': 591958,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast'},
 {'id': '14726',
  'name': 'Akash Deep',
  'imageId': 591951,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '8292',
  'name': 'Kuldeep Yadav',
  'imageId': 846039,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm wrist-spin'},
 {'id': '13217',
  'name': 'Arshdeep Singh',
  'imageId': 846038,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm fast-medium'},
 {'id': '24729',
  'name': 'Harshit Rana',
  'imageId': 616529,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '14659',
  'name': 'Ravi Bishnoi',
  'imageId': 226280,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '10754',
  'name': 'Mukesh Kumar',
  'imageId': 333872,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '12926',
  'name': 'Varun Chakaravarthy',
  'imageId': 846040,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'}]

In [ ]:
separated = {}
current_category = None

for player in tp_data:
    # If it's a category row (no 'id')
    if "id" not in player:
        current_category = player["name"]
        separated[current_category] = []
    else:
        separated[current_category].append(player)

In [260]:
batsmen = separated.get('BATSMEN', [])
all_rounders = separated.get('ALL ROUNDER', [])
bowlers = separated.get('BOWLER', [])
wk = separated.get('WICKET KEEPER', [])

In [259]:
separated.keys()

dict_keys(['BATSMEN', 'ALL ROUNDER', 'WICKET KEEPER', 'BOWLER'])

In [270]:
cursor.execute("drop table if exists players_representing_India")
cursor.execute("""
    create table players_representing_India(
    Name varchar(30),
    Playing_role varchar(25),
    Batting_style varchar(25),
    Bowling_style varchar(25)
    )
""")
query = """
    insert into players_representing_India values
    (%s,%s,%s,%s)
"""

In [ ]:
for ba in batsmen:
    row = (ba.get('name',''), "Batsman", ba.get('battingStyle', ''), ba.get('bowlingStyle', ''))
    cursor.execute(query, row)
for bo in bowlers:
    row = (bo.get('name',''), "Bowler", bo.get('battingStyle', ''), bo.get('bowlingStyle', ''))
    cursor.execute(query, row)
for a in all_rounders:
    row = (a.get('name',''), "All-rounder", a.get('battingStyle', ''), a.get('bowlingStyle', ''))
    cursor.execute(query, row)
for w in wk:
    row = (w.get('name',''), "Wicket keeper", w.get('battingStyle', ''), w.get('bowlingStyle', ''))
    cursor.execute(query, row)

In [275]:
len(tp_data)

41

{'typeMatches': [{'matchType': 'International', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matches': [{'matchInfo': {'matchId': 139362, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '41st Match, Super 8 Group 2 (Y2 v Y3)', 'matchFormat': 'T20', 'startDate': '1771680600000', 'endDate': '1771693200000', 'state': 'Complete', 'status': 'Match abandoned without a ball bowled', 'team1': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 776308}, 'team2': {'teamId': 13, 'teamName': 'New Zealand', 'teamSName': 'NZ', 'imageId': 776333}, 'venueInfo': {'id': 15, 'ground': 'R.Premadasa Stadium', 'city': 'Colombo', 'timezone': '+05:30', 'latitude': '6.939966', 'longitude': '79.872222'}, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon', 'isFantasyEnabled': True}}, {'matchInfo': {'matchId': 139381, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '43rd Match, Super 8 Group 1 (X1 v X4)', 'matchFormat': 'T20', 'startDate': '1771767000000', 'endDate': '1771779600000', 'state': 'Complete', 'status': 'South Africa won by 76 runs', 'team1': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 776287}, 'team2': {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 776162}, 'venueInfo': {'id': 50, 'ground': 'Narendra Modi Stadium', 'city': 'Ahmedabad', 'timezone': '+05:30', 'latitude': '23.091785', 'longitude': '72.597465'}, 'currBatTeamId': 11, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'RSA Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 187, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 111, 'wickets': 10, 'overs': 18.5}}}}, {'matchInfo': {'matchId': 139263, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '32nd Match, Group B', 'matchFormat': 'T20', 'startDate': '1771320600000', 'endDate': '1771333200000', 'state': 'Complete', 'status': 'Match abandoned due to rain (no toss)', 'team1': {'teamId': 27, 'teamName': 'Ireland', 'teamSName': 'IRE', 'imageId': 839366}, 'team2': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 776198}, 'venueInfo': {'id': 254, 'ground': 'Pallekele International Cricket Stadium', 'city': 'Pallekele', 'timezone': '+05:30', 'latitude': '7.280691', 'longitude': '80.722493'}, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon', 'isFantasyEnabled': True}}, {'matchInfo': {'matchId': 139318, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '37th Match, Group C', 'matchFormat': 'T20', 'startDate': '1771479000000', 'endDate': '1771491600000', 'state': 'Complete', 'status': 'West Indies won by 42 runs', 'team1': {'teamId': 10, 'teamName': 'West Indies', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 527, 'teamName': 'Italy', 'teamSName': 'ITA', 'imageId': 776295}, 'venueInfo': {'id': 31, 'ground': 'Eden Gardens', 'city': 'Kolkata', 'timezone': '+05:30', 'latitude': '22.564527', 'longitude': '88.343247'}, 'currBatTeamId': 10, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'WI Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 165, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 123, 'wickets': 10, 'overs': 17.6}}}}, {'matchInfo': {'matchId': 139373, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '42nd Match, Super 8 Group 2 (Y1 v Y4)', 'matchFormat': 'T20', 'startDate': '1771752600000', 'endDate': '1771765200000', 'state': 'Complete', 'status': 'England won by 51 runs', 'team1': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 776237}, 'team2': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'id': 254, 'ground': 'Pallekele International Cricket Stadium', 'city': 'Pallekele', 'timezone': '+05:30', 'latitude': '7.280691', 'longitude': '80.722493'}, 'currBatTeamId': 9, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'ENG Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 146, 'wickets': 9, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 95, 'wickets': 10, 'overs': 16.4}}}}, {'matchInfo': {'matchId': 139307, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '36th Match, Group A', 'matchFormat': 'T20', 'startDate': '1771421400000', 'endDate': '1771434000000', 'state': 'Complete', 'status': 'India won by 17 runs', 'team1': {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 24, 'teamName': 'Netherlands', 'teamSName': 'NED', 'imageId': 776335}, 'venueInfo': {'id': 50, 'ground': 'Narendra Modi Stadium', 'city': 'Ahmedabad', 'timezone': '+05:30', 'latitude': '23.091785', 'longitude': '72.597465'}, 'currBatTeamId': 2, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'IND Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 193, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 176, 'wickets': 7, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 139296, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '35th Match, Group A', 'matchFormat': 'T20', 'startDate': '1771407000000', 'endDate': '1771419600000', 'state': 'Complete', 'status': 'Pakistan won by 102 runs', 'team1': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 776308}, 'team2': {'teamId': 161, 'teamName': 'Namibia', 'teamSName': 'NAM', 'imageId': 776326}, 'venueInfo': {'id': 14, 'ground': 'Sinhalese Sports Club', 'city': 'Colombo', 'timezone': '+05:30', 'latitude': '6.905929', 'longitude': '79.869403'}, 'currBatTeamId': 3, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'PAK Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 199, 'wickets': 3, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 97, 'wickets': 10, 'overs': 17.3}}}}, {'matchInfo': {'matchId': 139351, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '40th Match, Group B', 'matchFormat': 'T20', 'startDate': '1771594200000', 'endDate': '1771606800000', 'state': 'Complete', 'status': 'Australia won by 9 wkts', 'team1': {'teamId': 304, 'teamName': 'Oman', 'teamSName': 'OMAN', 'imageId': 776328}, 'team2': {'teamId': 4, 'teamName': 'Australia', 'teamSName': 'AUS', 'imageId': 776202}, 'venueInfo': {'id': 254, 'ground': 'Pallekele International Cricket Stadium', 'city': 'Pallekele', 'timezone': '+05:30', 'latitude': '7.280691', 'longitude': '80.722493'}, 'currBatTeamId': 4, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'AUS Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 104, 'wickets': 10, 'overs': 16.2}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 108, 'wickets': 1, 'overs': 9.4}}}}, {'matchInfo': {'matchId': 139241, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '30th Match, Group B', 'matchFormat': 'T20', 'startDate': '1771248600000', 'endDate': '1771261200000', 'state': 'Complete', 'status': 'Sri Lanka won by 8 wkts', 'team1': {'teamId': 4, 'teamName': 'Australia', 'teamSName': 'AUS', 'imageId': 776202}, 'team2': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'id': 254, 'ground': 'Pallekele International Cricket Stadium', 'city': 'Pallekele', 'timezone': '+05:30', 'latitude': '7.280691', 'longitude': '80.722493'}, 'currBatTeamId': 5, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'SL Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 181, 'wickets': 10, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 184, 'wickets': 2, 'overs': 17.6}}}}, {'matchInfo': {'matchId': 139274, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '33rd Match, Group C', 'matchFormat': 'T20', 'startDate': '1771335000000', 'endDate': '1771347600000', 'state': 'Complete', 'status': 'Nepal won by 7 wkts', 'team1': {'teamId': 23, 'teamName': 'Scotland', 'teamSName': 'SCO', 'imageId': 776280}, 'team2': {'teamId': 72, 'teamName': 'Nepal', 'teamSName': 'NEP', 'imageId': 776331}, 'venueInfo': {'id': 81, 'ground': 'Wankhede Stadium', 'city': 'Mumbai', 'timezone': '+05:30', 'latitude': '18.938956', 'longitude': '72.825719'}, 'currBatTeamId': 72, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'NEP Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 170, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 171, 'wickets': 3, 'overs': 19.2}}}}, {'matchInfo': {'matchId': 139285, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '34th Match, Group D', 'matchFormat': 'T20', 'startDate': '1771392600000', 'endDate': '1771405200000', 'state': 'Complete', 'status': 'South Africa won by 6 wkts', 'team1': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 776242}, 'team2': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'id': 51, 'ground': 'Arun Jaitley Stadium', 'city': 'Delhi', 'timezone': '+05:30', 'latitude': '28.637891', 'longitude': '77.243073'}, 'currBatTeamId': 11, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'RSA Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 122, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 123, 'wickets': 4, 'overs': 13.2}}}}, {'matchInfo': {'matchId': 139230, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '29th Match, Group C', 'matchFormat': 'T20', 'startDate': '1771234200000', 'endDate': '1771246800000', 'state': 'Complete', 'status': 'England won by 24 runs', 'team1': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 776237}, 'team2': {'teamId': 527, 'teamName': 'Italy', 'teamSName': 'ITA', 'imageId': 776295}, 'venueInfo': {'id': 31, 'ground': 'Eden Gardens', 'city': 'Kolkata', 'timezone': '+05:30', 'latitude': '22.564527', 'longitude': '88.343247'}, 'currBatTeamId': 9, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'ENG Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 202, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 178, 'wickets': 10, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 139329, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '38th Match, Group B', 'matchFormat': 'T20', 'startDate': '1771493400000', 'endDate': '1771506000000', 'state': 'Complete', 'status': 'Zimbabwe won by 6 wkts', 'team1': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 776254}, 'team2': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 776198}, 'venueInfo': {'id': 15, 'ground': 'R.Premadasa Stadium', 'city': 'Colombo', 'timezone': '+05:30', 'latitude': '6.939966', 'longitude': '79.872222'}, 'currBatTeamId': 12, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'ZIM Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 178, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 182, 'wickets': 4, 'overs': 19.3}}}}, {'matchInfo': {'matchId': 139252, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '31st Match, Group D', 'matchFormat': 'T20', 'startDate': '1771306200000', 'endDate': '1771318800000', 'state': 'Complete', 'status': 'New Zealand won by 8 wkts', 'team1': {'teamId': 26, 'teamName': 'Canada', 'teamSName': 'CAN', 'imageId': 776227}, 'team2': {'teamId': 13, 'teamName': 'New Zealand', 'teamSName': 'NZ', 'imageId': 776333}, 'venueInfo': {'id': 11, 'ground': 'MA Chidambaram Stadium', 'city': 'Chennai', 'timezone': '+05:30', 'latitude': '13.06282', 'longitude': '80.279274'}, 'currBatTeamId': 13, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'NZ Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 173, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 176, 'wickets': 2, 'overs': 15.1}}}}, {'matchInfo': {'matchId': 139340, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '39th Match, Group D', 'matchFormat': 'T20', 'startDate': '1771507800000', 'endDate': '1771520400000', 'state': 'Complete', 'status': 'Afghanistan won by 82 runs', 'team1': {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 776177}, 'team2': {'teamId': 26, 'teamName': 'Canada', 'teamSName': 'CAN', 'imageId': 776227}, 'venueInfo': {'id': 11, 'ground': 'MA Chidambaram Stadium', 'city': 'Chennai', 'timezone': '+05:30', 'latitude': '13.06282', 'longitude': '80.279274'}, 'currBatTeamId': 96, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'AFG Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 200, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 118, 'wickets': 8, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 139227, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '28th Match, Group D', 'matchFormat': 'T20', 'startDate': '1771219800000', 'endDate': '1771232400000', 'state': 'Complete', 'status': 'Afghanistan won by 5 wkts', 'team1': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 776242}, 'team2': {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 776177}, 'venueInfo': {'id': 51, 'ground': 'Arun Jaitley Stadium', 'city': 'Delhi', 'timezone': '+05:30', 'latitude': '28.637891', 'longitude': '77.243073'}, 'currBatTeamId': 96, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'AFG Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 160, 'wickets': 9, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 162, 'wickets': 5, 'overs': 19.2}}}}]}}]}, {'matchType': 'Domestic', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26', 'matches': [{'matchInfo': {'matchId': 125074, 'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26', 'matchDesc': '2nd Semi Final', 'matchFormat': 'TEST', 'startDate': '1771126200000', 'endDate': '1771497000000', 'state': 'Complete', 'status': 'Jammu and Kashmir won by 6 wkts', 'team1': {'teamId': 232, 'teamName': 'Bengal', 'teamSName': 'BEN', 'imageId': 172285}, 'team2': {'teamId': 252, 'teamName': 'Jammu and Kashmir', 'teamSName': 'JK', 'imageId': 172305}, 'venueInfo': {'id': 437, 'ground': 'Bengal Cricket Academy Ground', 'city': 'Kalyani', 'timezone': '+05:30', 'latitude': '22.9792675', 'longitude': '88.4416824'}, 'currBatTeamId': 252, 'seriesStartDt': '1760486400000', 'seriesEndDt': '1772409600000', 'isTimeAnnounced': True, 'stateTitle': 'JK Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 328, 'wickets': 10, 'overs': 97.1}, 'inngs2': {'inningsId': 3, 'runs': 99, 'wickets': 10, 'overs': 25.1}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 302, 'wickets': 10, 'overs': 76.1}, 'inngs2': {'inningsId': 4, 'runs': 126, 'wickets': 4, 'overs': 34.4}}}}, {'matchInfo': {'matchId': 125069, 'seriesId': 10317, 'seriesName': 'Ranji Trophy Elite 2025-26', 'matchDesc': '1st Semi Final', 'matchFormat': 'TEST', 'startDate': '1771128000000', 'endDate': '1771498800000', 'state': 'Complete', 'status': 'Match drawn', 'team1': {'teamId': 128, 'teamName': 'Karnataka', 'teamSName': 'KAR', 'imageId': 776345}, 'team2': {'teamId': 467, 'teamName': 'Uttarakhand', 'teamSName': 'UTK', 'imageId': 172515}, 'venueInfo': {'id': 485, 'ground': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'city': 'Lucknow', 'timezone': '+05:30', 'latitude': '26.846694', 'longitude': '80.946166'}, 'seriesStartDt': '1760486400000', 'seriesEndDt': '1772409600000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 736, 'wickets': 10, 'overs': 194.4}, 'inngs2': {'inningsId': 3, 'runs': 323, 'wickets': 10, 'overs': 74.3}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 233, 'wickets': 10, 'overs': 88.5}, 'inngs2': {'inningsId': 4, 'runs': 260, 'wickets': 6, 'overs': 61.6}}}}]}}, {'seriesAdWrapper': {'seriesId': 10724, 'seriesName': 'The Ford Trophy 2025-26', 'matches': [{'matchInfo': {'matchId': 132164, 'seriesId': 10724, 'seriesName': 'The Ford Trophy 2025-26', 'matchDesc': 'Final', 'matchFormat': 'ODI', 'startDate': '1771709400000', 'endDate': '1771738200000', 'state': 'Complete', 'status': 'Central Districts won by 6 wkts', 'team1': {'teamId': 312, 'teamName': 'Canterbury', 'teamSName': 'CNTBRY', 'imageId': 172362}, 'team2': {'teamId': 313, 'teamName': 'Central Districts', 'teamSName': 'CD', 'imageId': 172363}, 'venueInfo': {'id': 45, 'ground': 'Basin Reserve', 'city': 'Wellington', 'timezone': '+13:00', 'latitude': '-41.161720', 'longitude': '175.323914'}, 'currBatTeamId': 313, 'seriesStartDt': '1761350400000', 'seriesEndDt': '1771891200000', 'isTimeAnnounced': True, 'stateTitle': 'CD Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 302, 'wickets': 7, 'overs': 49.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 303, 'wickets': 4, 'overs': 47.5}}}}, {'matchInfo': {'matchId': 132120, 'seriesId': 10724, 'seriesName': 'The Ford Trophy 2025-26', 'matchDesc': '28th Match', 'matchFormat': 'ODI', 'startDate': '1771277400000', 'endDate': '1771306200000', 'state': 'Complete', 'status': 'Auckland won by 6 wkts', 'team1': {'teamId': 105, 'teamName': 'Otago', 'teamSName': 'OTG', 'imageId': 172197}, 'team2': {'teamId': 186, 'teamName': 'Auckland', 'teamSName': 'AKL', 'imageId': 172246}, 'venueInfo': {'id': 82, 'ground': 'John Davies Oval', 'city': 'Queenstown', 'timezone': '+13:00', 'latitude': '-45.016205', 'longitude': '168.738638'}, 'currBatTeamId': 186, 'seriesStartDt': '1761350400000', 'seriesEndDt': '1771891200000', 'isTimeAnnounced': True, 'stateTitle': 'AKL Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 158, 'wickets': 10, 'overs': 43.3}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 161, 'wickets': 4, 'overs': 23.4}}}}, {'matchInfo': {'matchId': 132153, 'seriesId': 10724, 'seriesName': 'The Ford Trophy 2025-26', 'matchDesc': 'Eliminator', 'matchFormat': 'ODI', 'startDate': '1771536600000', 'endDate': '1771565400000', 'state': 'Complete', 'status': 'Central Districts won by 211 runs', 'team1': {'teamId': 313, 'teamName': 'Central Districts', 'teamSName': 'CD', 'imageId': 172363}, 'team2': {'teamId': 314, 'teamName': 'Wellington', 'teamSName': 'WEL', 'imageId': 172364}, 'venueInfo': {'id': 45, 'ground': 'Basin Reserve', 'city': 'Wellington', 'timezone': '+13:00', 'latitude': '-41.161720', 'longitude': '175.323914'}, 'currBatTeamId': 313, 'seriesStartDt': '1761350400000', 'seriesEndDt': '1771891200000', 'isTimeAnnounced': True, 'stateTitle': 'CD Won'}, '

In [ ]:
# Question 2

# api call
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

recent_matches = response.json()

# getting readable information about recent matches
RecentMatches = []
for matchtype in recent_matches['typeMatches']:
    for seriesmatch in matchtype['seriesMatches']:
        if 'seriesAdWrapper' in seriesmatch:
            seriesmatch = seriesmatch['seriesAdWrapper']
            Series_ID = seriesmatch['seriesId']
            Series_Name = seriesmatch['seriesName']
            Matches = seriesmatch['matches']
            for match in Matches:
                match_info = match.get('matchInfo',[])

                # takeaways
                match_desc = match_info.get('matchDesc')
                team1 = match_info.get('team1').get('teamName')
                team2 = match_info.get('team2').get('teamName')
                venue = f"{match_info.get('venueInfo').get('ground')}, {match_info.get('venueInfo').get('city')}"
                dt = match_info.get('startDate')
                date = datetime.fromtimestamp(int(dt)/1000)
                
                RecentMatches.append({
                        'Match Description' : match_desc,
                        'Team 1' : team1,
                        'Team 2' : team2,
                        'Venue' : venue,
                        'Date' : date.strftime("%d-%m-%Y %H:%M:%S")
                    })             

# database implementation

cursor.execute("drop table if exists recent_matches")
cursor.execute("""
    create table recent_matches(
    Match_description varchar(100),
    Team1 varchar(30),
    Team2 varchar(50),
    Venue varchar(100),
    Match_date varchar(20)
    )
""")
query2 = """
    insert into recent_matches values
    (%s,%s,%s,%s,%s)
"""

for i in RecentMatches:
    row = (i.get('Match Description'), i.get('Team 1'), i.get('Team 2'), i.get('Venue'), i.get('Date'))
    cursor.execute(query2, row)

In [306]:
RecentMatches

[{'Match Description': '41st Match, Super 8 Group 2 (Y2 v Y3)',
  'Team 1': 'Pakistan',
  'Team 2': 'New Zealand',
  'Venue': 'R.Premadasa Stadium, Colombo',
  'Date': '21-02-2026 19:00:00'},
 {'Match Description': '43rd Match, Super 8 Group 1 (X1 v X4)',
  'Team 1': 'South Africa',
  'Team 2': 'India',
  'Venue': 'Narendra Modi Stadium, Ahmedabad',
  'Date': '22-02-2026 19:00:00'},
 {'Match Description': '32nd Match, Group B',
  'Team 1': 'Ireland',
  'Team 2': 'Zimbabwe',
  'Venue': 'Pallekele International Cricket Stadium, Pallekele',
  'Date': '17-02-2026 15:00:00'},
 {'Match Description': '37th Match, Group C',
  'Team 1': 'West Indies',
  'Team 2': 'Italy',
  'Venue': 'Eden Gardens, Kolkata',
  'Date': '19-02-2026 11:00:00'},
 {'Match Description': '42nd Match, Super 8 Group 2 (Y1 v Y4)',
  'Team 1': 'England',
  'Team 2': 'Sri Lanka',
  'Venue': 'Pallekele International Cricket Stadium, Pallekele',
  'Date': '22-02-2026 15:00:00'},
 {'Match Description': '36th Match, Group A',
  'Team 1': 'India',
  'Team 2': 'Netherlands',
  'Venue': 'Narendra Modi Stadium, Ahmedabad',
  'Date': '18-02-2026 19:00:00'},
 {'Match Description': '35th Match, Group A',
  'Team 1': 'Pakistan',
  'Team 2': 'Namibia',
  'Venue': 'Sinhalese Sports Club, Colombo',
  'Date': '18-02-2026 15:00:00'},
 {'Match Description': '40th Match, Group B',
  'Team 1': 'Oman',
  'Team 2': 'Australia',
  'Venue': 'Pallekele International Cricket Stadium, Pallekele',
  'Date': '20-02-2026 19:00:00'},
 {'Match Description': '30th Match, Group B',
  'Team 1': 'Australia',
  'Team 2': 'Sri Lanka',
  'Venue': 'Pallekele International Cricket Stadium, Pallekele',
  'Date': '16-02-2026 19:00:00'},
 {'Match Description': '33rd Match, Group C',
  'Team 1': 'Scotland',
  'Team 2': 'Nepal',
  'Venue': 'Wankhede Stadium, Mumbai',
  'Date': '17-02-2026 19:00:00'},
 {'Match Description': '34th Match, Group D',
  'Team 1': 'United Arab Emirates',
  'Team 2': 'South Africa',
  'Venue': 'Arun Jaitley Stadium, Delhi',
  'Date': '18-02-2026 11:00:00'},
 {'Match Description': '29th Match, Group C',
  'Team 1': 'England',
  'Team 2': 'Italy',
  'Venue': 'Eden Gardens, Kolkata',
  'Date': '16-02-2026 15:00:00'},
 {'Match Description': '38th Match, Group B',
  'Team 1': 'Sri Lanka',
  'Team 2': 'Zimbabwe',
  'Venue': 'R.Premadasa Stadium, Colombo',
  'Date': '19-02-2026 15:00:00'},
 {'Match Description': '31st Match, Group D',
  'Team 1': 'Canada',
  'Team 2': 'New Zealand',
  'Venue': 'MA Chidambaram Stadium, Chennai',
  'Date': '17-02-2026 11:00:00'},
 {'Match Description': '39th Match, Group D',
  'Team 1': 'Afghanistan',
  'Team 2': 'Canada',
  'Venue': 'MA Chidambaram Stadium, Chennai',
  'Date': '19-02-2026 19:00:00'},
 {'Match Description': '28th Match, Group D',
  'Team 1': 'United Arab Emirates',
  'Team 2': 'Afghanistan',
  'Venue': 'Arun Jaitley Stadium, Delhi',
  'Date': '16-02-2026 11:00:00'},
 {'Match Description': '2nd Semi Final',
  'Team 1': 'Bengal',
  'Team 2': 'Jammu and Kashmir',
  'Venue': 'Bengal Cricket Academy Ground, Kalyani',
  'Date': '15-02-2026 09:00:00'},
 {'Match Description': '1st Semi Final',
  'Team 1': 'Karnataka',
  'Team 2': 'Uttarakhand',
  'Venue': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
  'Date': '15-02-2026 09:30:00'},
 {'Match Description': 'Final',
  'Team 1': 'Canterbury',
  'Team 2': 'Central Districts',
  'Venue': 'Basin Reserve, Wellington',
  'Date': '22-02-2026 03:00:00'},
 {'Match Description': '28th Match',
  'Team 1': 'Otago',
  'Team 2': 'Auckland',
  'Venue': 'John Davies Oval, Queenstown',
  'Date': '17-02-2026 03:00:00'},
 {'Match Description': 'Eliminator',
  'Team 1': 'Central Districts',
  'Team 2': 'Wellington',
  'Venue': 'Basin Reserve, Wellington',
  'Date': '20-02-2026 03:00:00'},
 {'Match Description': '30th Match',
  'Team 1': 'Wellington',
  'Team 2': 'Northern Districts',
  'Venue': 'Basin Reserve, Wellington',
  'Date': '18-02-2026 03:00:00'},
 {'Match Description': '29th Match',
  'Team 1': 'Central Districts',
  'Team 2': 'Canterbury',
  'Venue': 'Saxton Oval, Nelson',
  'Date': '17-02-2026 03:00:00'},
 {'Match Description': '24th Match',
  'Team 1': 'Tasmania',
  'Team 2': 'New South Wales',
  'Venue': 'Bellerive Oval, Hobart',
  'Date': '16-02-2026 09:00:00'},
 {'Match Description': '22nd Match',
  'Team 1': 'Queensland',
  'Team 2': 'South Australia',
  'Venue': 'The Gabba, Brisbane',
  'Date': '16-02-2026 05:30:00'},
 {'Match Description': '23rd Match',
  'Team 1': 'Victoria',
  'Team 2': 'Western Australia',
  'Venue': 'W.A.C.A. Ground, Perth',
  'Date': '16-02-2026 08:00:00'},
 {'Match Description': '4th Match',
  'Team 1': 'Knights',
  'Team 2': 'Limpopo',
  'Venue': 'Polokwane Cricket Club, Polokwane',
  'Date': '22-02-2026 13:30:00'},
 {'Match Description': '3rd Match',
  'Team 1': 'South Africa Emerging Players',
  'Team 2': 'Border',
  'Venue': 'Buffalo Park, East London',
  'Date': '22-02-2026 13:30:00'},
 {'Match Description': '1st Match',
  'Team 1': 'Northern Cape',
  'Team 2': 'South Western Districts',
  'Venue': 'Recreation Ground, Oudtshoorn',
  'Date': '21-02-2026 13:30:00'},
 {'Match Description': '2nd Match',
  'Team 1': 'Mpumalanga Rhinos',
  'Team 2': 'Eastern Storm',
  'Venue': 'Willowmoore Park, Benoni',
  'Date': '21-02-2026 13:30:00'},
 {'Match Description': '20th Match',
  'Team 1': 'Tasmania',
  'Team 2': 'New South Wales',
  'Venue': 'Bellerive Oval, Hobart',
  'Date': '21-02-2026 08:30:00'},
 {'Match Description': '19th Match',
  'Team 1': 'Queensland',
  'Team 2': 'South Australia',
  'Venue': 'The Gabba, Brisbane',
  'Date': '21-02-2026 05:30:00'},
 {'Match Description': '21st Match',
  'Team 1': 'Victoria',
  'Team 2': 'Western Australia',
  'Venue': 'W.A.C.A. Ground, Perth',
  'Date': '21-02-2026 11:30:00'},
 {'Match Description': 'Final',
  'Team 1': 'Warriors',
  'Team 2': 'Lions',
  'Venue': 'The Wanderers Stadium, Johannesburg',
  'Date': '18-02-2026 13:30:00'},
 {'Match Description': '1st T20',
  'Team 1': 'Pakistan A',
  'Team 2': 'England Lions',
  'Venue': 'Sheikh Zayed Stadium, Abu Dhabi',
  'Date': '20-02-2026 15:30:00'},
 {'Match Description': '2nd T20',
  'Team 1': 'England Lions',
  'Team 2': 'Pakistan A',
  'Venue': 'Sheikh Zayed Stadium, Abu Dhabi',
  'Date': '22-02-2026 15:30:00'},
 {'Match Description': '3rd T20I',
  'Team 1': 'India Women',
  'Team 2': 'Australia Women',
  'Venue': 'Adelaide Oval, Adelaide',
  'Date': '21-02-2026 13:45:00'},
 {'Match Description': '2nd T20I',
  'Team 1': 'Australia Women',
  'Team 2': 'India Women',
  'Venue': 'Manuka Oval, Canberra',
  'Date': '19-02-2026 13:45:00'},
 {'Match Description': 'Final',
  'Team 1': 'India A Women',
  'Team 2': 'Bangladesh A Women',
  'Venue': 'Terdthai Cricket Ground, Bangkok',
  'Date': '22-02-2026 12:30:00'},
 {'Match Description': '11th Match, Group B',
  'Team 1': 'Bangladesh A Women',
  'Team 2': 'Malaysia Women',
  'Venue': 'Terdthai Cricket Ground, Bangkok',
  'Date': '18-02-2026 08:00:00'},
 {'Match Description': '8th Match, Group B',
  'Team 1': 'Thailand Women',
  'Team 2': 'Bangladesh A Women',
  'Venue': 'Terdthai Cricket Ground, Bangkok',
  'Date': '16-02-2026 12:30:00'},
 {'Match Description': 'Semi Final 1 (A1vB2)',
  'Team 1': 'Sri Lanka A Women',
  'Team 2': 'India A Women',
  'Venue': 'Terdthai Cricket Ground, Bangkok',
  'Date': '20-02-2026 08:00:00'},
 {'Match Description': '9th Match, Group A',
  'Team 1': 'Nepal Women',
  'Team 2': 'India A Women',
  'Venue': 'Terdthai Cricket Ground, Bangkok',
  'Date': '17-02-2026 08:00:00'},
 {'Match Description': '12th Match, Group B',
  'Team 1': 'Sri Lanka A Women',
  'Team 2': 'Thailand Women',
  'Venue': 'Terdthai Cricket Ground, Bangkok',
  'Date': '18-02-2026 12:30:00'},
 {'Match Description': 'Semi Final 2 (B1vA2)',
  'Team 1': 'Bangladesh A Women',
  'Team 2': 'Pakistan A Women',
  'Venue': 'Terdthai Cricket Ground, Bangkok',
  'Date': '20-02-2026 12:30:00'},
 {'Match Description': '10th Match, Group A',
  'Team 1': 'United Arab Emirates Women',
  'Team 2': 'Pakistan A Women',
  'Venue': 'Terdthai Cricket Ground, Bangkok',
  'Date': '17-02-2026 12:30:00'},
 {'Match Description': '2nd ODI',
  'Team 1': 'Sri Lanka Women',
  'Team 2': 'West Indies Women',
  'Venue': 'National Cricket Stadium, St Georges, Grenada',
  'Date': '22-02-2026 19:00:00'},
 {'Match Description': '1st ODI',
  'Team 1': 'Sri Lanka Women',
  'Team 2': 'West Indies Women',
  'Venue': 'National Cricket Stadium, St Georges, Grenada',
  'Date': '20-02-2026 19:00:00'},
 {'Match Description': '1st ODI',
  'Team 1': 'South Africa Women',
  'Team 2': 'Pakistan Women',
  'Venue': 'Mangaung Oval, Bloemfontein',
  'Date': '22-02-2026 13:30:00'},
 {'Match Description': '3rd T20I',
  'Team 1': 'Pakistan Women',
  'Team 2': 'South Africa Women',
  'Venue': 'Diamond Oval, Kimberley',
  'Date': '16-02-2026 21:30:00'}]

In [412]:
# question 3

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats/0"

querystring = {"statsType":"mostRuns", "matchType":"2"}

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

d_mostRuns = response.json()

{'filter': {'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'}, {'matchTypeId': '2', 'matchTypeDesc': 'odi'}, {'matchTypeId': '3', 'matchTypeDesc': 't20i'}], 'team': [{'id': '2', 'teamShortName': 'IND'}, {'id': '27', 'teamShortName': 'IRE'}, {'id': '3', 'teamShortName': 'PAK'}, {'id': '4', 'teamShortName': 'AUS'}, {'id': '5', 'teamShortName': 'SL'}, {'id': '6', 'teamShortName': 'BAN'}, {'id': '9', 'teamShortName': 'ENG'}, {'id': '10', 'teamShortName': 'WI'}, {'id': '11', 'teamShortName': 'RSA'}, {'id': '12', 'teamShortName': 'ZIM'}, {'id': '13', 'teamShortName': 'NZ'}, {'id': '96', 'teamShortName': 'AFG'}], 'selectedMatchType': 'odi'}, 'headers': ['Batter', 'M', 'I', 'R', 'Avg'], 'values': [{'values': ['25', 'Tendulkar', '463', '452', '18426', '44.83']}, {'values': ['1413', 'Virat Kohli', '311', '299', '14797', '58.72']}, {'values': ['104', 'Sangakkara', '404', '380', '14234', '41.99']}, {'values': ['38', 'R Ponting', '375', '365', '13704', '42.04']}, {'values': ['102', 'S Jayasuriya', '445', '433', '13430', '32.36']}, {'values': ['101', 'Mahela', '448', '418', '12650', '33.38']}, {'values': ['35', 'Inzamam-ul-Haq', '378', '350', '11739', '39.53']}, {'values': ['213', 'Kallis', '328', '314', '11579', '44.36']}, {'values': ['576', 'Rohit Sharma', '282', '274', '11577', '48.85']}, {'values': ['29', 'S Ganguly', '311', '300', '11363', '41.02']}, {'values': ['27', 'Dravid', '344', '318', '10889', '39.17']}, {'values': ['265', 'Dhoni', '350', '297', '10773', '50.58']}, {'values': ['247', 'Gayle', '301', '294', '10480', '37.83']}, {'values': ['240', 'B Lara', '299', '289', '10405', '40.49']}, {'values': ['105', 'Dilshan', '330', '303', '10290', '39.27']}, {'values': ['34', 'M Yousuf', '288', '273', '9720', '41.72']}, {'values': ['36', 'A Gilchrist', '287', '279', '9619', '35.89']}, {'values': ['370', 'de Villiers', '228', '218', '9577', '53.50']}, {'values': ['3864', 'M Azharuddin', '334', '308', '9378', '36.92']}, {'values': ['3531', 'A Silva', '308', '296', '9284', '34.90']}], 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com', 'webURL': 'www.cricbuzz.com'}}

In [419]:
d_mostRuns['values']

[{'values': ['25', 'Tendulkar', '463', '452', '18426', '44.83']},
 {'values': ['1413', 'Virat Kohli', '311', '299', '14797', '58.72']},
 {'values': ['104', 'Sangakkara', '404', '380', '14234', '41.99']},
 {'values': ['38', 'R Ponting', '375', '365', '13704', '42.04']},
 {'values': ['102', 'S Jayasuriya', '445', '433', '13430', '32.36']},
 {'values': ['101', 'Mahela', '448', '418', '12650', '33.38']},
 {'values': ['35', 'Inzamam-ul-Haq', '378', '350', '11739', '39.53']},
 {'values': ['213', 'Kallis', '328', '314', '11579', '44.36']},
 {'values': ['576', 'Rohit Sharma', '282', '274', '11577', '48.85']},
 {'values': ['29', 'S Ganguly', '311', '300', '11363', '41.02']},
 {'values': ['27', 'Dravid', '344', '318', '10889', '39.17']},
 {'values': ['265', 'Dhoni', '350', '297', '10773', '50.58']},
 {'values': ['247', 'Gayle', '301', '294', '10480', '37.83']},
 {'values': ['240', 'B Lara', '299', '289', '10405', '40.49']},
 {'values': ['105', 'Dilshan', '330', '303', '10290', '39.27']},
 {'values': ['34', 'M Yousuf', '288', '273', '9720', '41.72']},
 {'values': ['36', 'A Gilchrist', '287', '279', '9619', '35.89']},
 {'values': ['370', 'de Villiers', '228', '218', '9577', '53.50']},
 {'values': ['3864', 'M Azharuddin', '334', '308', '9378', '36.92']},
 {'values': ['3531', 'A Silva', '308', '296', '9284', '34.90']}]

In [ ]:
for i in d_mostRuns['values']:
    row  = i['values']
    print(row)

['25', 'Tendulkar', '463', '452', '18426', '44.83']
['1413', 'Virat Kohli', '311', '299', '14797', '58.72']
['104', 'Sangakkara', '404', '380', '14234', '41.99']
['38', 'R Ponting', '375', '365', '13704', '42.04']
['102', 'S Jayasuriya', '445', '433', '13430', '32.36']
['101', 'Mahela', '448', '418', '12650', '33.38']
['35', 'Inzamam-ul-Haq', '378', '350', '11739', '39.53']
['213', 'Kallis', '328', '314', '11579', '44.36']
['576', 'Rohit Sharma', '282', '274', '11577', '48.85']
['29', 'S Ganguly', '311', '300', '11363', '41.02']
['27', 'Dravid', '344', '318', '10889', '39.17']
['265', 'Dhoni', '350', '297', '10773', '50.58']
['247', 'Gayle', '301', '294', '10480', '37.83']
['240', 'B Lara', '299', '289', '10405', '40.49']
['105', 'Dilshan', '330', '303', '10290', '39.27']
['34', 'M Yousuf', '288', '273', '9720', '41.72']
['36', 'A Gilchrist', '287', '279', '9619', '35.89']
['370', 'de Villiers', '228', '218', '9577', '53.50']
['3864', 'M Azharuddin', '334', '308', '9378', '36.92']
['3531', 'A Silva', '308', '296', '9284', '34.90']

In [432]:
cursor.execute("drop table if exists toprunscorers")
cursor.execute("""
                create table toprunscorers(
                playerid varchar(30),
                name varchar(30),
                matches varchar(30),
                innings varchar(30),
                runs varchar(30),
                average varchar(30)
               )
            """)

In [ ]:
insert3 = """
    insert into toprunscorers values
    (%s,%s,%s,%s,%s,%s)
"""
for i in d_mostRuns['values']:
    row  = i['values']
    cursor.execute(insert3, row)

In [434]:
cursor.execute("""
        alter table toprunscorers
               alter column playerid type int using playerid::int,
               alter column matches type int using matches::int,
               alter column innings type int using innings::int,
               alter column runs type int using runs::int,
               alter column average type float using average::float
""")

In [321]:
# records filters
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

filters = response.json()

{'statsTypesList': [{'types': [{'value': 'mostRuns', 'header': 'Most Runs', 'category': 'Batting'}, {'value': 'highestScore', 'header': 'Highest Scores', 'category': 'Batting'}, {'value': 'highestAvg', 'header': 'Best Batting Average', 'category': 'Batting'}, {'value': 'highestSr', 'header': 'Best Batting Strike Rate', 'category': 'Batting'}, {'value': 'mostHundreds', 'header': 'Most Hundreds', 'category': 'Batting'}, {'value': 'mostFifties', 'header': 'Most Fifties', 'category': 'Batting'}, {'value': 'mostFours', 'header': 'Most Fours', 'category': 'Batting'}, {'value': 'mostSixes', 'header': 'Most Sixes', 'category': 'Batting'}, {'value': 'mostNineties', 'header': 'Most Nineties', 'category': 'Batting'}], 'category': 'Batting'}, {'types': [{'value': 'mostWickets', 'header': 'Most Wickets', 'category': 'Bowling'}, {'value': 'lowestAvg', 'header': 'Best Bowling Average', 'category': 'Bowling'}, {'value': 'bestBowlingInnings', 'header': 'Best Bowling ', 'category': 'Bowling'}, {'value': 'mostFiveWickets', 'header': 'Most 5 Wickets Haul', 'category': 'Bowling'}, {'value': 'lowestEcon', 'header': 'Best Economy', 'category': 'Bowling'}, {'value': 'lowestSr', 'header': 'Best Bowling Strike Rate', 'category': 'Bowling'}], 'category': 'Bowling'}]}

In [322]:
filters

{'statsTypesList': [{'types': [{'value': 'mostRuns',
     'header': 'Most Runs',
     'category': 'Batting'},
    {'value': 'highestScore',
     'header': 'Highest Scores',
     'category': 'Batting'},
    {'value': 'highestAvg',
     'header': 'Best Batting Average',
     'category': 'Batting'},
    {'value': 'highestSr',
     'header': 'Best Batting Strike Rate',
     'category': 'Batting'},
    {'value': 'mostHundreds',
     'header': 'Most Hundreds',
     'category': 'Batting'},
    {'value': 'mostFifties', 'header': 'Most Fifties', 'category': 'Batting'},
    {'value': 'mostFours', 'header': 'Most Fours', 'category': 'Batting'},
    {'value': 'mostSixes', 'header': 'Most Sixes', 'category': 'Batting'},
    {'value': 'mostNineties',
     'header': 'Most Nineties',
     'category': 'Batting'}],
   'category': 'Batting'},
  {'types': [{'value': 'mostWickets',
     'header': 'Most Wickets',
     'category': 'Bowling'},
    {'value': 'lowestAvg',
     'header': 'Best Bowling Average',
     'category': 'Bowling'},
    {'value': 'bestBowlingInnings',
     'header': 'Best Bowling ',
     'category': 'Bowling'},
    {'value': 'mostFiveWickets',
     'header': 'Most 5 Wickets Haul',
     'category': 'Bowling'},
    {'value': 'lowestEcon', 'header': 'Best Economy', 'category': 'Bowling'},
    {'value': 'lowestSr',
     'header': 'Best Bowling Strike Rate',
     'category': 'Bowling'}],
   'category': 'Bowling'}]}

In [340]:
# Question 4

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/venues/v1/45"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'ground': 'Basin Reserve', 'city': 'Wellington', 'country': 'New Zealand', 'timezone': '+13:00', 'capacity': '11,600', 'ends': 'Vance Stand End, Scoreboard End', 'homeTeam': 'Wellington', 'imageUrl': 'http://i.cricketcb.com/i/stats/fth/540x303/venue/images/45.jpg', 'imageId': '189174'}

In [341]:
venue_data = response.json()
venue_data

{'ground': 'Basin Reserve',
 'city': 'Wellington',
 'country': 'New Zealand',
 'timezone': '+13:00',
 'capacity': '11,600',
 'ends': 'Vance Stand End, Scoreboard End',
 'homeTeam': 'Wellington',
 'imageUrl': 'http://i.cricketcb.com/i/stats/fth/540x303/venue/images/45.jpg',
 'imageId': '189174'}

In [337]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time

base_url = "https://en.wikipedia.org"
list_url = "https://en.wikipedia.org/wiki/List_of_international_cricket_grounds"

response = requests.get(list_url)
soup = BeautifulSoup(response.text, "html.parser")

tables = soup.find_all("table", class_="wikitable")

grounds_data = []

for table in tables:
    rows = table.find_all("tr")[1:]

    for row in rows:
        cols = row.find_all("td")
        if len(cols) < 1:
            continue

        link = cols[0].find("a")
        if link:
            ground_name = link.text.strip()
            ground_link = base_url + link["href"]

            try:
                ground_page = requests.get(ground_link)
                ground_soup = BeautifulSoup(ground_page.text, "html.parser")

                info_box = ground_soup.find("table", class_="infobox")

                capacity = None
                city = None
                country = None

                if info_box:
                    rows_info = info_box.find_all("tr")
                    for r in rows_info:
                        header = r.find("th")
                        value = r.find("td")

                        if header and value:
                            header_text = header.text.strip()

                            if "Capacity" in header_text:
                                capacity_text = value.text.strip()
                                capacity = re.sub(r"\[.*?\]", "", capacity_text)

                            if "Location" in header_text:
                                location_text = value.text.strip()
                                location_text = re.sub(r"\[.*?\]", "", location_text)
                                city = location_text

                grounds_data.append({
                    "Ground": ground_name,
                    "Location": city,
                    "Capacity": capacity
                })

                print(f"Scraped: {ground_name}")
                time.sleep(1)

            except:
                print(f"Failed: {ground_name}")
                continue

df = pd.DataFrame(grounds_data)
print(df.head())

df.to_csv("cricket_grounds.csv", index=False)

Empty DataFrame
Columns: []
Index: []

In [367]:
venue_dataxl = pd.read_excel(r"D:\Guvi\Projects\Cricbuzz-livestats\venue_data.xlsx")
venue_dataxl

,Ground,Capacity,City,Country
0,Narendra Modi Stadium,132000,Ahmedabad,India
1,Melbourne Cricket Ground,100024,Melbourne,Australia
2,Eden Gardens,68000,Kolkata,India
3,Shaheed Veer Narayan Singh International Crick...,65000,Naya Raipur,India
4,Perth Stadium,61266,Perth,Australia
...,...,...,...,...
197,Mombasa Sports Club Ground,1000,Mombasa,Kenya
198,Ruaraka Sports Club Ground,1000,Nairobi,Kenya
199,White Hill Field,1000,Sandys Parish,Bermuda
200,Kowloon Cricket Club,1000,Kowloon,Hong Kong
201,Estadio Belgrano Athletic,500,Buenos Aires,Argentina

In [362]:
venue_dataxl

,Ground,Capacity,City,Country
0,Narendra Modi Stadium,"132,000",Ahmedabad,India
1,Melbourne Cricket Ground,"100,024",Melbourne,Australia
2,Eden Gardens,"68,000",Kolkata,India
3,Shaheed Veer Narayan Singh International Crick...,"65,000",Naya Raipur,India
4,Perth Stadium,"61,266",Perth,Australia
...,...,...,...,...
197,Mombasa Sports Club Ground,1000,Mombasa,Kenya
198,Ruaraka Sports Club Ground,1000,Nairobi,Kenya
199,White Hill Field,1000,Sandys Parish,Bermuda
200,Kowloon Cricket Club,1000,Kowloon,Hong Kong
201,Estadio Belgrano Athletic,500,Buenos Aires,Argentina

In [ ]:
# venue_dataxl.drop(index=venue_dataxl[(venue_dataxl['A/D/UC']=='D') | (venue_dataxl['A/D/UC']=='UC')].index, inplace=True)
# venue_dataxl

,Ground,Capacity,City,Country,A/D/UC
0,Ground,Capacity,City,Country,A
1,Narendra Modi Stadium,"132,000",Ahmedabad,India,A
2,Melbourne Cricket Ground,"100,024",Melbourne,Australia,A
3,Eden Gardens,"68,000",Kolkata,India,A
4,Shaheed Veer Narayan Singh International Crick...,"65,000",Naya Raipur,India,A
...,...,...,...,...,...
198,Mombasa Sports Club Ground,1000,Mombasa,Kenya,A
199,Ruaraka Sports Club Ground,1000,Nairobi,Kenya,A
200,White Hill Field,1000,Sandys Parish,Bermuda,A
201,Kowloon Cricket Club,1000,Kowloon,Hong Kong,A
202,Estadio Belgrano Athletic,500,Buenos Aires,Argentina,A

In [364]:
cursor.execute("""
    create table venue(
    ground text,
    capacity int,
    city text,
    country text)
""")

In [368]:
for _, row in venue_dataxl.iterrows():
    cursor.execute("""
        INSERT INTO venue (ground, capacity, city, country)
        VALUES (%s, %s, %s, %s)
    """, (row["Ground"], row["Capacity"], row["City"], row["Country"]))

In [369]:
# Question 5

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/teams/v1/international"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

q5_data = response.json()

{'list': [{'teamName': 'Test Teams'}, {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 776162, 'countryName': 'India'}, {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 776177}, {'teamId': 27, 'teamName': 'Ireland', 'teamSName': 'IRE', 'imageId': 839366}, {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 776308, 'countryName': 'Pakistan'}, {'teamId': 4, 'teamName': 'Australia', 'teamSName': 'AUS', 'imageId': 776202, 'countryName': 'Australia'}, {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 776254, 'countryName': 'Sri Lanka'}, {'teamId': 6, 'teamName': 'Bangladesh', 'teamSName': 'BAN', 'imageId': 776210}, {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 776237}, {'teamId': 10, 'teamName': 'West Indies', 'teamSName': 'WI', 'imageId': 776191}, {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 776287}, {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 776198, 'countryName': 'Zimbabwe'}, {'teamId': 13, 'teamName': 'New Zealand', 'teamSName': 'NZ', 'imageId': 776333}, {'teamName': 'Associate Teams'}, {'teamId': 71, 'teamName': 'Malaysia', 'teamSName': 'MLY', 'imageId': 776319}, {'teamId': 72, 'teamName': 'Nepal', 'teamSName': 'NEP', 'imageId': 776331}, {'teamId': 77, 'teamName': 'Germany', 'teamSName': 'GER', 'imageId': 776260}, {'teamId': 161, 'teamName': 'Namibia', 'teamSName': 'NAM', 'imageId': 776326}, {'teamId': 185, 'teamName': 'Denmark', 'teamSName': 'DEN', 'imageId': 776232}, {'teamId': 190, 'teamName': 'Singapore', 'teamSName': 'SIN', 'imageId': 776275}, {'teamId': 287, 'teamName': 'Papua New Guinea', 'teamSName': 'PNG', 'imageId': 776304}, {'teamId': 298, 'teamName': 'Kuwait', 'teamSName': 'KUW', 'imageId': 776312}, {'teamId': 300, 'teamName': 'Vanuatu', 'teamSName': 'VAN', 'imageId': 776229}, {'teamId': 303, 'teamName': 'Jersey', 'teamSName': 'JER', 'imageId': 776300}, {'teamId': 304, 'teamName': 'Oman', 'teamSName': 'OMAN', 'imageId': 776328}, {'teamId': 343, 'teamName': 'Fiji', 'teamSName': 'FIJI', 'imageId': 776251}, {'teamId': 527, 'teamName': 'Italy', 'teamSName': 'ITA', 'imageId': 776295}, {'teamId': 529, 'teamName': 'Botswana', 'teamSName': 'BW', 'imageId': 776225}, {'teamId': 541, 'teamName': 'Belgium', 'teamSName': 'BEL', 'imageId': 776219}, {'teamId': 44, 'teamName': 'Uganda', 'teamSName': 'UGA', 'imageId': 776233}, {'teamId': 26, 'teamName': 'Canada', 'teamSName': 'CAN', 'imageId': 776227}, {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 776242}, {'teamId': 8, 'teamName': 'Hong Kong, China', 'teamSName': 'HKC', 'imageId': 776271}, {'teamId': 14, 'teamName': 'Kenya', 'teamSName': 'KEN', 'imageId': 776303}, {'teamId': 15, 'teamName': 'United States of America', 'teamSName': 'USA', 'imageId': 776186, 'countryName': 'United States of America'}, {'teamId': 23, 'teamName': 'Scotland', 'teamSName': 'SCO', 'imageId': 776280}, {'teamId': 24, 'teamName': 'Netherlands', 'teamSName': 'NED', 'imageId': 776335}, {'teamId': 25, 'teamName': 'Bermuda', 'teamSName': 'BER', 'imageId': 776221}, {'teamId': 675, 'teamName': 'Iran', 'teamSName': 'IRN', 'imageId': 776282}], 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-team/'}}

In [373]:
q5_data['list']

[{'teamName': 'Test Teams'},
 {'teamId': 2,
  'teamName': 'India',
  'teamSName': 'IND',
  'imageId': 776162,
  'countryName': 'India'},
 {'teamId': 96,
  'teamName': 'Afghanistan',
  'teamSName': 'AFG',
  'imageId': 776177},
 {'teamId': 27, 'teamName': 'Ireland', 'teamSName': 'IRE', 'imageId': 839366},
 {'teamId': 3,
  'teamName': 'Pakistan',
  'teamSName': 'PAK',
  'imageId': 776308,
  'countryName': 'Pakistan'},
 {'teamId': 4,
  'teamName': 'Australia',
  'teamSName': 'AUS',
  'imageId': 776202,
  'countryName': 'Australia'},
 {'teamId': 5,
  'teamName': 'Sri Lanka',
  'teamSName': 'SL',
  'imageId': 776254,
  'countryName': 'Sri Lanka'},
 {'teamId': 6,
  'teamName': 'Bangladesh',
  'teamSName': 'BAN',
  'imageId': 776210},
 {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 776237},
 {'teamId': 10,
  'teamName': 'West Indies',
  'teamSName': 'WI',
  'imageId': 776191},
 {'teamId': 11,
  'teamName': 'South Africa',
  'teamSName': 'RSA',
  'imageId': 776287},
 {'teamId': 12,
  'teamName': 'Zimbabwe',
  'teamSName': 'ZIM',
  'imageId': 776198,
  'countryName': 'Zimbabwe'},
 {'teamId': 13,
  'teamName': 'New Zealand',
  'teamSName': 'NZ',
  'imageId': 776333},
 {'teamName': 'Associate Teams'},
 {'teamId': 71, 'teamName': 'Malaysia', 'teamSName': 'MLY', 'imageId': 776319},
 {'teamId': 72, 'teamName': 'Nepal', 'teamSName': 'NEP', 'imageId': 776331},
 {'teamId': 77, 'teamName': 'Germany', 'teamSName': 'GER', 'imageId': 776260},
 {'teamId': 161, 'teamName': 'Namibia', 'teamSName': 'NAM', 'imageId': 776326},
 {'teamId': 185, 'teamName': 'Denmark', 'teamSName': 'DEN', 'imageId': 776232},
 {'teamId': 190,
  'teamName': 'Singapore',
  'teamSName': 'SIN',
  'imageId': 776275},
 {'teamId': 287,
  'teamName': 'Papua New Guinea',
  'teamSName': 'PNG',
  'imageId': 776304},
 {'teamId': 298, 'teamName': 'Kuwait', 'teamSName': 'KUW', 'imageId': 776312},
 {'teamId': 300, 'teamName': 'Vanuatu', 'teamSName': 'VAN', 'imageId': 776229},
 {'teamId': 303, 'teamName': 'Jersey', 'teamSName': 'JER', 'imageId': 776300},
 {'teamId': 304, 'teamName': 'Oman', 'teamSName': 'OMAN', 'imageId': 776328},
 {'teamId': 343, 'teamName': 'Fiji', 'teamSName': 'FIJI', 'imageId': 776251},
 {'teamId': 527, 'teamName': 'Italy', 'teamSName': 'ITA', 'imageId': 776295},
 {'teamId': 529, 'teamName': 'Botswana', 'teamSName': 'BW', 'imageId': 776225},
 {'teamId': 541, 'teamName': 'Belgium', 'teamSName': 'BEL', 'imageId': 776219},
 {'teamId': 44, 'teamName': 'Uganda', 'teamSName': 'UGA', 'imageId': 776233},
 {'teamId': 26, 'teamName': 'Canada', 'teamSName': 'CAN', 'imageId': 776227},
 {'teamId': 7,
  'teamName': 'United Arab Emirates',
  'teamSName': 'UAE',
  'imageId': 776242},
 {'teamId': 8,
  'teamName': 'Hong Kong, China',
  'teamSName': 'HKC',
  'imageId': 776271},
 {'teamId': 14, 'teamName': 'Kenya', 'teamSName': 'KEN', 'imageId': 776303},
 {'teamId': 15,
  'teamName': 'United States of America',
  'teamSName': 'USA',
  'imageId': 776186,
  'countryName': 'United States of America'},
 {'teamId': 23, 'teamName': 'Scotland', 'teamSName': 'SCO', 'imageId': 776280},
 {'teamId': 24,
  'teamName': 'Netherlands',
  'teamSName': 'NED',
  'imageId': 776335},
 {'teamId': 25, 'teamName': 'Bermuda', 'teamSName': 'BER', 'imageId': 776221},
 {'teamId': 675, 'teamName': 'Iran', 'teamSName': 'IRN', 'imageId': 776282}]

In [377]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/team/2"

querystring = {"statsType":"mostRuns"}

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'filter': {'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'}, {'matchTypeId': '2', 'matchTypeDesc': 'odi'}, {'matchTypeId': '3', 'matchTypeDesc': 't20i'}], 'team': [{'id': '58', 'teamShortName': 'CSK'}, {'id': '97', 'teamShortName': 'INDW'}, {'id': '61', 'teamShortName': 'DC'}, {'id': '65', 'teamShortName': 'PBKS'}, {'id': '63', 'teamShortName': 'KKR'}, {'id': '62', 'teamShortName': 'MI'}, {'id': '59', 'teamShortName': 'RCB'}, {'id': '64', 'teamShortName': 'RR'}, {'id': '255', 'teamShortName': 'SRH'}, {'id': '971', 'teamShortName': 'GT'}, {'id': '966', 'teamShortName': 'LSG'}, {'id': '510', 'teamShortName': 'BTS'}, {'id': '506', 'teamShortName': 'VANW'}, {'id': '507', 'teamShortName': 'SKRW'}, {'id': '496', 'teamShortName': 'BELW'}, {'id': '508', 'teamShortName': 'DENW'}, {'id': '509', 'teamShortName': 'SINW'}, {'id': '518', 'teamShortName': 'AFGU23'}, {'id': '517', 'teamShortName': 'SIND'}, {'id': '516', 'teamShortName': 'RJP'}, {'id': '515', 'teamShortName': 'PL'}, {'id': '514', 'teamShortName': 'PAKHT'}, {'id': '513', 'teamShortName': 'NW'}, {'id': '512', 'teamShortName': 'MA'}, {'id': '511', 'teamShortName': 'KKS'}, {'id': '505', 'teamShortName': 'OMANW'}, {'id': '504', 'teamShortName': 'GERW'}, {'id': '503', 'teamShortName': 'NAMW'}, {'id': '490', 'teamShortName': 'SLEW'}, {'id': '489', 'teamShortName': 'ARGW'}, {'id': '488', 'teamShortName': 'BWAW'}, {'id': '487', 'teamShortName': 'JPNW'}, {'id': '486', 'teamShortName': 'CHNW'}, {'id': '485', 'teamShortName': 'QATW'}, {'id': '484', 'teamShortName': 'IDNW'}, {'id': '483', 'teamShortName': 'TANW'}, {'id': '491', 'teamShortName': 'BRAW'}, {'id': '492', 'teamShortName': 'FRAW'}, {'id': '493', 'teamShortName': 'MOZW'}, {'id': '502', 'teamShortName': 'HKC W'}, {'id': '501', 'teamShortName': 'KENW'}, {'id': '500', 'teamShortName': 'SWZW'}, {'id': '499', 'teamShortName': 'LSOW'}, {'id': '498', 'teamShortName': 'PERW'}, {'id': '497', 'teamShortName': 'CHLW'}, {'id': '495', 'teamShortName': 'MWIW'}, {'id': '494', 'teamShortName': 'ZMBW'}, {'id': '482', 'teamShortName': 'WSMW'}, {'id': '519', 'teamShortName': 'INDU19A'}, {'id': '520', 'teamShortName': 'INDU19B'}, {'id': '540', 'teamShortName': 'BLZ'}, {'id': '541', 'teamShortName': 'BEL'}, {'id': '542', 'teamShortName': 'PER'}, {'id': '543', 'teamShortName': 'BHR'}, {'id': '544', 'teamShortName': 'MEX'}, {'id': '545', 'teamShortName': 'WSM'}, {'id': '546', 'teamShortName': 'PAN'}, {'id': '547', 'teamShortName': 'JPN'}, {'id': '548', 'teamShortName': 'CRI'}, {'id': '549', 'teamShortName': 'ARG'}, {'id': '550', 'teamShortName': 'HUN'}, {'id': '551', 'teamShortName': 'MOZ'}, {'id': '552', 'teamShortName': 'CHL'}, {'id': '553', 'teamShortName': 'MWI'}, {'id': '554', 'teamShortName': 'ISR'}, {'id': '555', 'teamShortName': 'BTN'}, {'id': '556', 'teamShortName': 'FIN'}, {'id': '539', 'teamShortName': 'FRA'}, {'id': '538', 'teamShortName': 'PHI'}, {'id': '521', 'teamShortName': 'ESTXI'}, {'id': '522', 'teamShortName': 'Malta'}, {'id': '523', 'teamShortName': 'ESP'}, {'id': '524', 'teamShortName': 'CHN'}, {'id': '525', 'teamShortName': 'QAT'}, {'id': '526', 'teamShortName': 'EST'}, {'id': '527', 'teamShortName': 'ITA'}, {'id': '528', 'teamShortName': 'ZIMCXI'}, {'id': '529', 'teamShortName': 'BW'}, {'id': '530', 'teamShortName': 'VEL'}, {'id': '531', 'teamShortName': 'GH'}, {'id': '532', 'teamShortName': 'AUT'}, {'id': '533', 'teamShortName': 'GGY'}, {'id': '534', 'teamShortName': 'SWE'}, {'id': '535', 'teamShortName': 'TAN'}, {'id': '536', 'teamShortName': 'NGA'}, {'id': '537', 'teamShortName': 'LUX'}, {'id': '557', 'teamShortName': 'IOM'}, {'id': '404', 'teamShortName': 'MCCWXI'}, {'id': '425', 'teamShortName': 'WXI'}, {'id': '426', 'teamShortName': 'BZ'}, {'id': '427', 'teamShortName': 'BLCB'}, {'id': '428', 'teamShortName': 'CTKR'}, {'id': '429', 'teamShortName': 'DW'}, {'id': '430', 'teamShortName': 'JG'}, {'id': '431', 'teamShortName': 'NMBS'}, {'id': '432', 'teamShortName': 'PM'}, {'id': '433', 'teamShortName': 'SK'}, {'id': '434', 'teamShortName': 'SYL'}, {'id': '435', 'teamShortName': 'IREA'}, {'id': '436', 'teamShortName': 'WAXI'}, {'id': '437', 'teamShortName': 'MS'}, {'id': '438', 'teamShortName': 'HKIU'}, {'id': '439', 'teamShortName': 'SAEW'}, {'id': '440', 'teamShortName': 'INDWA'}, {'id': '441', 'teamShortName': 'COL'}, {'id': '424', 'teamShortName': 'KENU19'}, {'id': '423', 'teamShortName': 'BLB'}, {'id': '405', 'teamShortName': 'INDU23'}, {'id': '406', 'teamShortName': 'PAKU23'}, {'id': '407', 'teamShortName': 'SLU23'}, {'id': '408', 'teamShortName': 'BANU23'}, {'id': '410', 'teamShortName': 'Trichy'}, {'id': '411', 'teamShortName': 'SIKAR'}, {'id': '412', 'teamShortName': 'UDE'}, {'id': '413', 'teamShortName': 'JAIPUR'}, {'id': '414', 'teamShortName': 'JL'}, {'id': '415', 'teamShortName': 'BWS'}, {'id': '416', 'teamShortName': 'APS'}, {'id': '417', 'teamShortName': 'SV'}, {'id': '418', 'teamShortName': 'WS'}, {'id': '419', 'teamShortName': 'YD'}, {'id': '420', 'teamShortName': 'LT'}, {'id': '421', 'teamShortName': 'LBL'}, {'id': '422', 'teamShortName': 'SST'}, {'id': '442', 'teamShortName': 'KAN'}, {'id': '443', 'teamShortName': 'GAL'}, {'id': '444', 'teamShortName': 'DAM'}, {'id': '464', 'teamShortName': 'NGL'}, {'id': '465', 'teamShortName': 'PDC'}, {'id': '466', 'teamShortName': 'SKM'}, {'id': '467', 'teamShortName': 'UTK'}, {'id': '468', 'teamShortName': 'ARNP'}, {'id': '469', 'teamShortName': 'HKCU19'}, {'id': '470', 'teamShortName': 'KZ'}, {'id': '471', 'teamShortName': 'PP'}, {'id': '472', 'teamShortName': 'KDK'}, {'id': '473', 'teamShortName': 'NL'}, {'id': '474', 'teamShortName': 'BL'}, {'id': '475', 'teamShortName': 'CTB'}, {'id': '476', 'teamShortName': 'DH'}, {'id': '477', 'teamShortName': 'JS'}, {'id': '478', 'teamShortName': 'NMBG'}, {'id': '479', 'teamShortName': 'PLR'}, {'id': '480', 'teamShortName': 'TSP'}, {'id': '463', 'teamShortName': 'MIZ'}, {'id': '462', 'teamShortName': 'MGLY'}, {'id': '445', 'teamShortName': 'MLYW'}, {'id': '446', 'teamShortName': 'TRL'}, {'id': '447', 'teamShortName': 'SPN'}, {'id': '448', 'teamShortName': 'UGAW'}, {'id': '449', 'teamShortName': 'UAEW'}, {'id': '450', 'teamShortName': 'TTN'}, {'id': '451', 'teamShortName': 'MNT'}, {'id': '452', 'teamShortName': 'EDR'}, {'id': '453', 'teamShortName': 'VCK'}, {'id': '454', 'teamShortName': 'WPH'}, {'id': '455', 'teamShortName': 'VKV'}, {'id': '456', 'teamShortName': 'CWIB'}, {'id': '457', 'teamShortName': 'INDWR'}, {'id': '458', 'teamShortName': 'INDWB'}, {'id': '459', 'teamShortName': 'INDWG'}, {'id': '460', 'teamShortName': 'BIH'}, {'id': '461', 'teamShortName': 'MNP'}, {'id': '481', 'teamShortName': 'INDC'}, {'id': '558', 'teamShortName': 'BGR'}, {'id': '657', 'teamShortName': 'PTXI'}, {'id': '770', 'teamShortName': 'TV'}, {'id': '775', 'teamShortName': 'AUTW'}, {'id': '779', 'teamShortName': 'FINXI'}, {'id': '784', 'teamShortName': 'CUMXI'}, {'id': '789', 'teamShortName': 'CLK'}, {'id': '794', 'teamShortName': 'DVK'}, {'id': '799', 'teamShortName': 'GGD'}, {'id': '800', 'teamShortName': 'JST'}, {'id': '805', 'teamShortName': 'KDT'}, {'id': '807', 'teamShortName': 'BRSAL'}, {'id': '812', 'teamShortName': 'KHULN'}, {'id': '817', 'teamShortName': 'RJSHI'}, {'id': '822', 'teamShortName': 'CTGRM'}, {'id': '827', 'teamShortName': 'DHAKA'}, {'id': '832', 'teamShortName': 'Root'}, {'id': '838', 'teamShortName': 'NZWXI'}, {'id': '843', 'teamShortName': 'BANE'}, {'id': '768', 'teamShortName': 'TC'}, {'id': '763', 'teamShortName': 'TR'}, {'id': '666', 'teamShortName': 'GCXI'}, {'id': '675', 'teamShortName': 'IRN'}, {'id': '682', 'teamShortName': 'INDL'}, {'id': '691', 'teamShortName': 'WIL'}, {'id': '700', 'teamShortName': 'AUSL'}, {'id': '709', 'teamShortName': 'SLL'}, {'id': '718', 'teamShortName': 'RSAL'}, {'id': '720', 'teamShortName': 'RWAW'}, {'id': '729', 'teamShortName': 'SLCXI'}, {'id': '733', 'teamShortName': 'WIHOXI'}, {'id': '738', 'teamShortName': 'WIBRXI'}, {'id': '743', 'teamShortName': 'TS'}, {'id': '748', 'teamShortName': 'TBR'}, {'id': '749', 'teamShortName': 'PAKWT'}, {'id': '754', 'teamShortName': 'PAKGR'}, {'id': '758', 'teamShortName': 'TMG'}, {'id': '759', 'teamShortName': 'TMO'}, {'id': '848', 'teamShortName': 'BANL'}, {'id': '853', 'teamShortName': 'ENGL'}, {'id': '861', 'teamShortName': 'ITT'}, {'id': '928', 'teamShortName': 'ROCKS'}, {'id': '933', 'teamShortName': 'ESTORM'}, {'id': '941', 'teamShortName': 'CBJ'}, {'id': '943', 'teamShortName': 'CLS'}, {'id': '946', 'teamShortName': 'DAS'}, {'id': '948', 'teamShortName': 'JKS'}, {'id': '953', 'teamShortName': 'KDW'}, {'id': '956', 'teamShortName': 'UGAU19'}, {'id': '961', 'teamShortName': 'INDWD'}, {'id': '976', 'teamShortName': 'MGD'}, {'id': '981', 'teamShortName': 'SYSR'}, {'id': '986', 'teamShortName': 'IMR'}, {'id': '991', 'teamShortName': 'ALN'}, {'id': '996', 'teamShortName': 'WGS'}, {'id': '1011', 'teamShortName': 'BAW'}, {'id': '1018', 'teamShortName': 'BHM'}, {'id': '1020', 'teamShortName': 'CAYM'}, {'id': '927', 'teamShortName': 'ECAPE'}, {'id': '923', 'teamShortName': 'NCAPE'}, {'id': '866', 'teamShortName': 'NRK'}, {'id': '867', 'teamShortName': 'SLST'}, {'id': '872', 'teamShortName': 'TLAT'}, {'id': '876', 'teamShortName': 'TWS'}, {'id': '881', 'teamShortName': 'ZIMSXI'}, {'id': '886', 'teamShortName': 'PCCSXI'}, {'id': '1032', 'teamShortName': 'JERW'}, {'id': '887', 'teamShortName': 'A1'}, {'id': '892', 'teamShortName': 'A2'}, {'id': '897', 'teamShortName': 'TKY'}, {'id': '902', 'teamShortName': 'TRKW'}, {'id': '903', 'teamShortName': 'MPR'}, {'id': '908', 'teamShortName': 'TUSKS'}, {'id': '912', 'teamShortName': 'LIMPO'}, {'id': '917', 'teamShortName': 'WPR'}, {'id': '918', 'teamShortName': 'GRB'}, {'id': '922', 'teamShortName': 'NWEST'}, {'id': '1027', 'teamShortName': 'NOR'}, {'id': '559', 'teamShortName': 'SLE'}, {'id': '579', 'teamShortName': 'TKMNE'}, {'id': '580', 'teamShortName': 'ETS'}, {'id': '581', 'teamShortName': 'NMP'}, {'id': '582', 'teamShortName': 'SBS'}, {'id': '583', 'teamShortName': 'SPL'}, {'id': '584', 'teamShortName': 'NBB'}, {'id': '585', 'teamShortName': 'AA'}, {'id': '586', 'teamShortName': 'SOL'}, {'id': '587', 'teamShortName': 'GGS'}, {'id': '588', 'teamShortName': 'HHS'}, {'id': '589', 'teamShortName': 'ZR'}, {'id': '590', 'teamShortName': 'KUTW'}, {'id': '591', 'teamShortName': 'BTW'}, {'id': '592', 'teamShortName': 'USAW'}, {'id': '593', 'teamShortName': 'KUWU19'}, {'id': '594', 'teamShortName': 'INDWBPXI'}, {'id': '595', 'teamShortName': 'CDG'}, {'id': '578', 'teamShortName': 'ATMWS'}, {'id': '577', 'teamShortName': 'BFT'}, {'id': '560', 'teamShortName': 'BRAZIL'}, {'id': '561', 'teamShortName': 'CZE'}, {'id': '562', 'teamShortName': 'SHN'}, {'id': '563', 'teamShortName': 'MDV'}, {'id': '564', 'teamShortName': 'GIB'}, {'id': '565', 'teamShortName': 'MMR'}, {'id': '566', 'teamShortName': 'IDN'}, {'id': '567', 'teamShortName': 'GM'}, {'id': '568', 'teamShortName': 'SWZ'}, {'id': '569', 'teamShortName': 'RWA'}, {'id': '570', 'teamShortName': 'LSO'}, {'id': '571', 'teamShortName': 'SAU'}, {'id': '572', 'teamShortName': 'ADK'}, {'id': '573', 'teamShortName': 'RDR'}, {'id': '574', 'teamShortName': 'EBR'}, {'id': '575', 'teamShortName': 'GGG'}, {'id': '576', 'teamShortName': 'DBC'}, {'id': '596', 'teamShortName': 'PORT'}, {'id': '597', 'teamShortName': 'DEG'}, {'id': '598', 'teamShortName': 'UBL'}, {'id': '618', 'teamShortName': 'TREW'}, {'id': '619', 'teamShortName': 'SULW'}, {'id': '620', 'teamShortName': 'SOUW'}, {'id': '621', 'teamShortName': 'SLT'}, {'id': '622', 'teamShortName': 'CGC'}, {'id': '623', 'teamShortName': 'CW'}, {'id': '624', 'teamShortName': 'RPR'}, {'id': '625', 'teamShortName': 'DP'}, {'id': '626', 'teamShortName': 'RSR'}, {'id': '627', 'teamShortName': 'KLT'}, {'id': '628', 'teamShortName': 'FLH'}, {'id': '629', 'teamShortName': 'FYO'}, {'id': '630', 'teamShortName': 'DSR'}, {'id': '631', 'teamShortName': 'PGR'}, {'id': '632', 'teamShortName': 'HSR'}, {'id': '633', 'teamShortName': 'SGP'}, {'id': '639', 'teamShortName': 'INDWC'}, {'id': '617', 'teamShortName': 'MSGW'}, {'id': '616', 'teamShortName': 'LDNW'}, {'id': '599', 'teamShortName': 'QLD'}, {'id': '600', 'teamShortName': 'BGT'}, {'id': '601', 'teamShortName': 'AD'}, {'id': '602', 'teamShortName': 'PD'}, {'id': '603', 'teamShortName': 'JPNU19'}, {'id': '604', 'teamShortName': 'NGAU19'}, {'id': '605', 'teamShortName': 'MIL'}, {'id': '606', 'teamShortName': 'WEF'}, {'id': '607', 'teamShortName': 'BRM'}, {'id': '608', 'teamShortName': 'LDN'}, {'id': '609', 'teamShortName': 'MSG'}, {'id': '610', 'teamShortName': 'SUL'}, {'id': '611', 'teamShortName': 'SOU'}, {'id': '612', 'teamShortName': 'TRE'}, {'id': '613', 'teamShortName': 'MILW'}, {'id': '614', 'teamShortName': 'WELW'}, {'id': '615', 'teamShortName': 'BRMW'}, {'id': '648', 'teamShortName': 'INDIAWB'}, {'id': '403', 'teamShortName': 'SOUTH'}, {'id': '149', 'teamShortName': 'GLAM'}, {'id': '170', 'teamShortName': 'BRD'}, {'id': '171', 'teamShortName': 'RAJ'}, {'id': '172', 'teamShortName': 'SLU19'}, {'id': '173', 'teamShortName': 'ENGU19'}, {'id': '183', 'teamShortName': 'PWI'}, {'id': '184', 'teamShortName': 'KTK'}, {'id': '185', 'teamShortName': 'DEN'}, {'id': '186', 'teamShortName': 'AKL'}, {'id': '187', 'teamShortName': 'RUH'}, {'id': '188', 'teamShortName': 'NEDW'}, {'id': '189', 'teamShortName': 'IREW'}, {'id': '190', 'teamShortName': 'SIN'}, {'id': '191', 'teamShortName': 'CACXI'}, {'id': '192', 'teamShortName': 'SYT'}, {'id': '193', 'teamShortName': 'BRH'}, {'id': '194', 'teamShortName': 'HBH'}, {'id': '195', 'teamShortName': 'MLR'}, {'id': '168', 'teamShortName': 'NCC'}, {'id': '167', 'teamShortName': 'MP'}, {'id': '150', 'teamShortName': 'KENT'}, {'id': '151', 'teamShortName': 'GLOUCS'}, {'id': '152', 'teamShortName': 'ESS'}, {'id': '153', 'teamShortName': 'HAM'}, {'id': '154', 'teamShortName': 'SLCPXI'}, {'id': '155', 'teamShortName': 'WAR'}, {'id': '156', 'teamShortName': 'CEN'}, {'id': '157', 'teamShortName': 'LIONS'}, {'id': '158', 'teamShortName': 'SAUS'}, {'id': '159', 'teamShortName': 'GAW'}, {'id': '160', 'teamShortName': 'EA'}, {'id': '161', 'teamShortName': 'NAM'}, {'id': '162', 'teamShortName': 'ASM'}, {'id': '163', 'teamShortName': 'GUJ'}, {'id': '164', 'teamShortName': 'QL'}, {'id': '165', 'teamShortName': 'ECBXI'}, {'id': '166', 'teamShortName': 'TAS'}, {'id': '196', 'teamShortName': 'MLS'}, {'id': '197', 'teamShortName': 'PRS'}, {'id': '198', 'teamShortName': 'SYS'}, {'id': '223', 'teamShortName': 'AFGU19'}, {'id': '224', 'teamShortName': 'BANU19'}, {'id': '226', 'teamShortName': 'IREU19'}, {'id': '228', 'teamShortName': 'SCOU19'}, {'id': '229', 'teamShortName': 'NPLU19'}, {'id': '230', 'teamShortName': 'NAMU19'}, {'id': '231', 'teamShortName': 'INDB'}, {'id': '232', 'teamShortName': 'BEN'}, {'id': '233', 'teamShortName': 'NZONE'}, {'id': '234', 'teamShortName': 'WZONE'}, {'id': '235', 'teamShortName': 'EZONE'}, {'id': '236', 'teamShortName': 'SZONE'}, {'id': '237', 'teamShortName': 'CZONE'}, {'id': '238', 'teamShortName': 'PASXI'}, {'id': '239', 'teamShortName': 'IWXI'}, {'id': '240', 'teamShortName': 'MUMA'}, {'id': '241', 'teamShortName': 'AP'}, {'id': '222', 'teamShortName': 'PNGU19'}, {'id': '221', 'teamShortName': 'ZIMU19'}, {'id': '199', 'teamShortName': 'ADS'}, {'id': '200', 'teamShortName': 'HAR'}, {'id': '201', 'teamShortName': 'BB'}, {'id': '202', 'teamShortName': 'CK'}, {'id': '203', 'teamShortName': 'DG'}, {'id': '204', 'teamShortName': 'DR'}, {'id': '205', 'teamShortName': 'KRB'}, {'id': '206', 'teamShortName': 'SR'}, {'id': '207', 'teamShortName': 'WIA'}, {'id': '208', 'teamShortName': 'BCD'}, {'id': '209', 'teamShortName': 'KW'}, {'id': '210', 'teamShortName': 'NN'}, {'id': '211', 'teamShortName': 'RUR'}, {'id': '212', 'teamShortName': 'UR'}, {'id': '213', 'teamShortName': 'WU'}, {'id': '214', 'teamShortName': 'UN'}, {'id': '220', 'teamShortName': 'WIU19'}, {'id': '242', 'teamShortName': 'HYD'}, {'id': '148', 'teamShortName': 'SUR'}, {'id': '2', 'teamShortName': 'IND'}, {'id': '26', 'teamShortName': 'CAN'}, {'id': '27', 'teamShortName': 'IRE'}, {'id': '36', 'teamShortName': 'INDBLUE'}, {'id': '41', 'teamShortName': 'SUS'}, {'id': '42', 'teamShortName': 'ENGA'}, {'id': '43', 'teamShortName': 'SLA'}, {'id': '44', 'teamShortName': 'UGA'}, {'id': '52', 'teamShortName': 'VIC'}, {'id': '53', 'teamShortName': 'ACTXI'}, {'id': '54', 'teamShortName': 'INDU19'}, {'id': '55', 'teamShortName': 'NZU19'}, {'id': '56', 'teamShortName': 'PAKU19'}, {'id': '57', 'teamShortName': 'RSAU19'}, {'id': '71', 'teamShortName': 'MLY'}, {'id': '72', 'teamShortName': 'NEP'}, {'id': '74', 'teamShortName': 'MDX'}, {'id': '77', 'teamShortName': 'GER'}, {'id': '25', 'teamShortName': 'BER'}, {'id': '24', 'teamShortName': 'NED'}, {'id': '3', 'teamShortName': 'PAK'}, {'id': '4', 'teamShortName': 'AUS'}, {'id': '5', 'teamShortName': 'SL'}, {'id': '6', 'teamShortName': 'BAN'}, {'id': '7', 'teamShortName': 'UAE'}, {'id': '8', 'teamShortName': 'HKC'}, {'id': '9', 'teamShortName': 'ENG'}, {'id': '10', 'teamShortName': 'WI'}, {'id': '11', 'teamShortName': 'RSA'}, {'id': '12', 'teamShortName': 'ZIM'}, {'id': '13', 'teamShortName': 'NZ'}, {'id': '14', 'teamShortName': 'KEN'}, {'id': '15', 'teamShortName': 'USA'}, {'id': '18', 'teamShortName': 'INDSR'}, {'id': '20', 'teamShortName': 'INDGREEN'}, {'id': '21', 'teamShortName': 'INDRED'}, {'id': '23', 'teamShortName': 'SCO'}, {'id': '78', 'teamShortName': 'INDA'}, {'id': '79', 'teamShortName': 'AUSA'}, {'id': '80', 'teamShortName': 'NZA'}, {'id': '105', 'teamShortName': 'OTG'}, {'id': '119', 'teamShortName': 'SOM'}, {'id': '122', 'teamShortName': 'MD'}, {'id': '123', 'teamShortName': 'BP'}, {'id': '125', 'teamShortName': 'BIJ'}, {'id': '128', 'teamShortName': 'KAR'}, {'id': '129', 'teamShortName': 'AUSU19'}, {'id': '130', 'teamShortName': 'WIS'}, {'id': '134', 'teamShortName': 'RGR'}, {'id': '139', 'teamShortName': 'NOTTS'}, {'id': '140', 'teamShortName': 'WARKS'}, {'id': '141', 'teamShortName': 'DUR'}, {'id': '142', 'teamShortName': 'NHNTS'}, {'id': '143', 'teamShortName': 'LANCS'}, {'id': '144', 'teamShortName': 'DERBY'}, {'id': '145', 'teamShortName': 'LEIC'}, {'id': '146', 'teamShortName': 'YORKS'}, {'id': '104', 'teamShortName': 'NSW'}, {'id': '103', 'teamShortName': 'WAY'}, {'id': '81', 'teamShortName': 'DEL'}, {'id': '82', 'teamShortName': 'ROI'}, {'id': '84', 'teamShortName': 'TT'}, {'id': '86', 'teamShortName': 'BPXI'}, {'id': '87', 'teamShortName': 'WA'}, {'id': '88', 'teamShortName': 'SKST'}, {'id': '89', 'teamShortName': 'TIT'}, {'id': '90', 'teamShortName': 'DOL'}, {'id': '92', 'teamShortName': 'TN'}, {'id': '93', 'teamShortName': 'UP'}, {'id': '94', 'teamShortName': 'SAUR'}, {'id': '95', 'teamShortName': 'MUM'}, {'id': '96', 'teamShortName': 'AFG'}, {'id': '98', 'teamShortName': 'NZW'}, {'id': '99', 'teamShortName': 'ENGW'}, {'id': '100', 'teamShortName': 'AUSW'}, {'id': '101', 'teamShortName': 'COB'}, {'id': '147', 'teamShortName': 'WORCS'}, {'id': '323', 'teamShortName': 'BCBXI'}, {'id': '347', 'teamShortName': 'HPCAXI'}, {'id': '348', 'teamShortName': 'TNCAU17'}, {'id': '349', 'teamShortName': 'MUMCAXI'}, {'id': '350', 'teamShortName': 'WICBPXI'}, {'id': '351', 'teamShortName': 'HHJ'}, {'id': '352', 'teamShortName': 'IW'}, {'id': '353', 'teamShortName': 'KC'}, {'id': '354', 'teamShortName': 'LGR'}, {'id': '355', 'teamShortName': 'ADSW'}, {'id': '356', 'teamShortName': 'BRHW'}, {'id': '357', 'teamShortName': 'HBHW'}, {'id': '358', 'teamShortName': 'MLRW'}, {'id': '359', 'teamShortName': 'MLSW'}, {'id': '360', 'teamShortName': 'PRSW'}, {'id': '361', 'teamShortName': 'SYSW'}, {'id': '362', 'teamShortName': 'SYTW'}, {'id': '363', 'teamShortName': 'MB'}, {'id': '344', 'teamShortName': 'SS'}, {'id': '343', 'teamShortName': 'FIJI'}, {'id': '324', 'teamShortName': 'NZBPXI'}, {'id': '325', 'teamShortName': 'PAKA'}, {'id': '326', 'teamShortName': 'FijiU19'}, {'id': '329', 'teamShortName': 'BANW'}, {'id': '330', 'teamShortName': 'ISU'}, {'id': '331', 'teamShortName': 'QTG'}, {'id': '332', 'teamShortName': 'KRK'}, {'id': '333'

In [378]:
teamR = response.json()

In [379]:
teamR

{'filter': {'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'},
   {'matchTypeId': '2', 'matchTypeDesc': 'odi'},
   {'matchTypeId': '3', 'matchTypeDesc': 't20i'}],
  'team': [{'id': '58', 'teamShortName': 'CSK'},
   {'id': '97', 'teamShortName': 'INDW'},
   {'id': '61', 'teamShortName': 'DC'},
   {'id': '65', 'teamShortName': 'PBKS'},
   {'id': '63', 'teamShortName': 'KKR'},
   {'id': '62', 'teamShortName': 'MI'},
   {'id': '59', 'teamShortName': 'RCB'},
   {'id': '64', 'teamShortName': 'RR'},
   {'id': '255', 'teamShortName': 'SRH'},
   {'id': '971', 'teamShortName': 'GT'},
   {'id': '966', 'teamShortName': 'LSG'},
   {'id': '510', 'teamShortName': 'BTS'},
   {'id': '506', 'teamShortName': 'VANW'},
   {'id': '507', 'teamShortName': 'SKRW'},
   {'id': '496', 'teamShortName': 'BELW'},
   {'id': '508', 'teamShortName': 'DENW'},
   {'id': '509', 'teamShortName': 'SINW'},
   {'id': '518', 'teamShortName': 'AFGU23'},
   {'id': '517', 'teamShortName': 'SIND'},
   {'id': '516', 'teamShortName': 'RJP'},
   {'id': '515', 'teamShortName': 'PL'},
   {'id': '514', 'teamShortName': 'PAKHT'},
   {'id': '513', 'teamShortName': 'NW'},
   {'id': '512', 'teamShortName': 'MA'},
   {'id': '511', 'teamShortName': 'KKS'},
   {'id': '505', 'teamShortName': 'OMANW'},
   {'id': '504', 'teamShortName': 'GERW'},
   {'id': '503', 'teamShortName': 'NAMW'},
   {'id': '490', 'teamShortName': 'SLEW'},
   {'id': '489', 'teamShortName': 'ARGW'},
   {'id': '488', 'teamShortName': 'BWAW'},
   {'id': '487', 'teamShortName': 'JPNW'},
   {'id': '486', 'teamShortName': 'CHNW'},
   {'id': '485', 'teamShortName': 'QATW'},
   {'id': '484', 'teamShortName': 'IDNW'},
   {'id': '483', 'teamShortName': 'TANW'},
   {'id': '491', 'teamShortName': 'BRAW'},
   {'id': '492', 'teamShortName': 'FRAW'},
   {'id': '493', 'teamShortName': 'MOZW'},
   {'id': '502', 'teamShortName': 'HKC W'},
   {'id': '501', 'teamShortName': 'KENW'},
   {'id': '500', 'teamShortName': 'SWZW'},
   {'id': '499', 'teamShortName': 'LSOW'},
   {'id': '498', 'teamShortName': 'PERW'},
   {'id': '497', 'teamShortName': 'CHLW'},
   {'id': '495', 'teamShortName': 'MWIW'},
   {'id': '494', 'teamShortName': 'ZMBW'},
   {'id': '482', 'teamShortName': 'WSMW'},
   {'id': '519', 'teamShortName': 'INDU19A'},
   {'id': '520', 'teamShortName': 'INDU19B'},
   {'id': '540', 'teamShortName': 'BLZ'},
   {'id': '541', 'teamShortName': 'BEL'},
   {'id': '542', 'teamShortName': 'PER'},
   {'id': '543', 'teamShortName': 'BHR'},
   {'id': '544', 'teamShortName': 'MEX'},
   {'id': '545', 'teamShortName': 'WSM'},
   {'id': '546', 'teamShortName': 'PAN'},
   {'id': '547', 'teamShortName': 'JPN'},
   {'id': '548', 'teamShortName': 'CRI'},
   {'id': '549', 'teamShortName': 'ARG'},
   {'id': '550', 'teamShortName': 'HUN'},
   {'id': '551', 'teamShortName': 'MOZ'},
   {'id': '552', 'teamShortName': 'CHL'},
   {'id': '553', 'teamShortName': 'MWI'},
   {'id': '554', 'teamShortName': 'ISR'},
   {'id': '555', 'teamShortName': 'BTN'},
   {'id': '556', 'teamShortName': 'FIN'},
   {'id': '539', 'teamShortName': 'FRA'},
   {'id': '538', 'teamShortName': 'PHI'},
   {'id': '521', 'teamShortName': 'ESTXI'},
   {'id': '522', 'teamShortName': 'Malta'},
   {'id': '523', 'teamShortName': 'ESP'},
   {'id': '524', 'teamShortName': 'CHN'},
   {'id': '525', 'teamShortName': 'QAT'},
   {'id': '526', 'teamShortName': 'EST'},
   {'id': '527', 'teamShortName': 'ITA'},
   {'id': '528', 'teamShortName': 'ZIMCXI'},
   {'id': '529', 'teamShortName': 'BW'},
   {'id': '530', 'teamShortName': 'VEL'},
   {'id': '531', 'teamShortName': 'GH'},
   {'id': '532', 'teamShortName': 'AUT'},
   {'id': '533', 'teamShortName': 'GGY'},
   {'id': '534', 'teamShortName': 'SWE'},
   {'id': '535', 'teamShortName': 'TAN'},
   {'id': '536', 'teamShortName': 'NGA'},
   {'id': '537', 'teamShortName': 'LUX'},
   {'id': '557', 'teamShortName': 'IOM'},
   {'id': '404', 'teamShortName': 'MCCWXI'},
   {'id': '425', 'teamShortName': 'WXI'},
   {'id': '426', 'teamShortName': 'BZ'},
   {'id': '427', 'teamShortName': 'BLCB'},
   {'id': '428', 'teamShortName': 'CTKR'},
   {'id': '429', 'teamShortName': 'DW'},
   {'id': '430', 'teamShortName': 'JG'},
   {'id': '431', 'teamShortName': 'NMBS'},
   {'id': '432', 'teamShortName': 'PM'},
   {'id': '433', 'teamShortName': 'SK'},
   {'id': '434', 'teamShortName': 'SYL'},
   {'id': '435', 'teamShortName': 'IREA'},
   {'id': '436', 'teamShortName': 'WAXI'},
   {'id': '437', 'teamShortName': 'MS'},
   {'id': '438', 'teamShortName': 'HKIU'},
   {'id': '439', 'teamShortName': 'SAEW'},
   {'id': '440', 'teamShortName': 'INDWA'},
   {'id': '441', 'teamShortName': 'COL'},
   {'id': '424', 'teamShortName': 'KENU19'},
   {'id': '423', 'teamShortName': 'BLB'},
   {'id': '405', 'teamShortName': 'INDU23'},
   {'id': '406', 'teamShortName': 'PAKU23'},
   {'id': '407', 'teamShortName': 'SLU23'},
   {'id': '408', 'teamShortName': 'BANU23'},
   {'id': '410', 'teamShortName': 'Trichy'},
   {'id': '411', 'teamShortName': 'SIKAR'},
   {'id': '412', 'teamShortName': 'UDE'},
   {'id': '413', 'teamShortName': 'JAIPUR'},
   {'id': '414', 'teamShortName': 'JL'},
   {'id': '415', 'teamShortName': 'BWS'},
   {'id': '416', 'teamShortName': 'APS'},
   {'id': '417', 'teamShortName': 'SV'},
   {'id': '418', 'teamShortName': 'WS'},
   {'id': '419', 'teamShortName': 'YD'},
   {'id': '420', 'teamShortName': 'LT'},
   {'id': '421', 'teamShortName': 'LBL'},
   {'id': '422', 'teamShortName': 'SST'},
   {'id': '442', 'teamShortName': 'KAN'},
   {'id': '443', 'teamShortName': 'GAL'},
   {'id': '444', 'teamShortName': 'DAM'},
   {'id': '464', 'teamShortName': 'NGL'},
   {'id': '465', 'teamShortName': 'PDC'},
   {'id': '466', 'teamShortName': 'SKM'},
   {'id': '467', 'teamShortName': 'UTK'},
   {'id': '468', 'teamShortName': 'ARNP'},
   {'id': '469', 'teamShortName': 'HKCU19'},
   {'id': '470', 'teamShortName': 'KZ'},
   {'id': '471', 'teamShortName': 'PP'},
   {'id': '472', 'teamShortName': 'KDK'},
   {'id': '473', 'teamShortName': 'NL'},
   {'id': '474', 'teamShortName': 'BL'},
   {'id': '475', 'teamShortName': 'CTB'},
   {'id': '476', 'teamShortName': 'DH'},
   {'id': '477', 'teamShortName': 'JS'},
   {'id': '478', 'teamShortName': 'NMBG'},
   {'id': '479', 'teamShortName': 'PLR'},
   {'id': '480', 'teamShortName': 'TSP'},
   {'id': '463', 'teamShortName': 'MIZ'},
   {'id': '462', 'teamShortName': 'MGLY'},
   {'id': '445', 'teamShortName': 'MLYW'},
   {'id': '446', 'teamShortName': 'TRL'},
   {'id': '447', 'teamShortName': 'SPN'},
   {'id': '448', 'teamShortName': 'UGAW'},
   {'id': '449', 'teamShortName': 'UAEW'},
   {'id': '450', 'teamShortName': 'TTN'},
   {'id': '451', 'teamShortName': 'MNT'},
   {'id': '452', 'teamShortName': 'EDR'},
   {'id': '453', 'teamShortName': 'VCK'},
   {'id': '454', 'teamShortName': 'WPH'},
   {'id': '455', 'teamShortName': 'VKV'},
   {'id': '456', 'teamShortName': 'CWIB'},
   {'id': '457', 'teamShortName': 'INDWR'},
   {'id': '458', 'teamShortName': 'INDWB'},
   {'id': '459', 'teamShortName': 'INDWG'},
   {'id': '460', 'teamShortName': 'BIH'},
   {'id': '461', 'teamShortName': 'MNP'},
   {'id': '481', 'teamShortName': 'INDC'},
   {'id': '558', 'teamShortName': 'BGR'},
   {'id': '657', 'teamShortName': 'PTXI'},
   {'id': '770', 'teamShortName': 'TV'},
   {'id': '775', 'teamShortName': 'AUTW'},
   {'id': '779', 'teamShortName': 'FINXI'},
   {'id': '784', 'teamShortName': 'CUMXI'},
   {'id': '789', 'teamShortName': 'CLK'},
   {'id': '794', 'teamShortName': 'DVK'},
   {'id': '799', 'teamShortName': 'GGD'},
   {'id': '800', 'teamShortName': 'JST'},
   {'id': '805', 'teamShortName': 'KDT'},
   {'id': '807', 'teamShortName': 'BRSAL'},
   {'id': '812', 'teamShortName': 'KHULN'},
   {'id': '817', 'teamShortName': 'RJSHI'},
   {'id': '822', 'teamShortName': 'CTGRM'},
   {'id': '827', 'teamShortName': 'DHAKA'},
   {'id': '832', 'teamShortName': 'Root'},
   {'id': '838', 'teamShortName': 'NZWXI'},
   {'id': '843', 'teamShortName': 'BANE'},
   {'id': '768', 'teamShortName': 'TC'},
   {'id': '763', 'teamShortName': 'TR'},
   {'id': '666', 'teamShortName': 'GCXI'},
   {'id': '675', 'teamShortName': 'IRN'},
   {'id': '682', 'teamShortName': 'INDL'},
   {'id': '691', 'teamShortName': 'WIL'},
   {'id': '700', 'teamShortName': 'AUSL'},
   {'id': '709', 'teamShortName': 'SLL'},
   {'id': '718', 'teamShortName': 'RSAL'},
   {'id': '720', 'teamShortName': 'RWAW'},
   {'id': '729', 'teamShortName': 'SLCXI'},
   {'id': '733', 'teamShortName': 'WIHOXI'},
   {'id': '738', 'teamShortName': 'WIBRXI'},
   {'id': '743', 'teamShortName': 'TS'},
   {'id': '748', 'teamShortName': 'TBR'},
   {'id': '749', 'teamShortName': 'PAKWT'},
   {'id': '754', 'teamShortName': 'PAKGR'},
   {'id': '758', 'teamShortName': 'TMG'},
   {'id': '759', 'teamShortName': 'TMO'},
   {'id': '848', 'teamShortName': 'BANL'},
   {'id': '853', 'teamShortName': 'ENGL'},
   {'id': '861', 'teamShortName': 'ITT'},
   {'id': '928', 'teamShortName': 'ROCKS'},
   {'id': '933', 'teamShortName': 'ESTORM'},
   {'id': '941', 'teamShortName': 'CBJ'},
   {'id': '943', 'teamShortName': 'CLS'},
   {'id': '946', 'teamShortName': 'DAS'},
   {'id': '948', 'teamShortName': 'JKS'},
   {'id': '953', 'teamShortName': 'KDW'},
   {'id': '956', 'teamShortName': 'UGAU19'},
   {'id': '961', 'teamShortName': 'INDWD'},
   {'id': '976', 'teamShortName': 'MGD'},
   {'id': '981', 'teamShortName': 'SYSR'},
   {'id': '986', 'teamShortName': 'IMR'},
   {'id': '991', 'teamShortName': 'ALN'},
   {'id': '996', 'teamShortName': 'WGS'},
   {'id': '1011', 'teamShortName': 'BAW'},
   {'id': '1018', 'teamShortName': 'BHM'},
   {'id': '1020', 'teamShortName': 'CAYM'},
   {'id': '927', 'teamShortName': 'ECAPE'},
   {'id': '923', 'teamShortName': 'NCAPE'},
   {'id': '866', 'teamShortName': 'NRK'},
   {'id': '867', 'teamShortName': 'SLST'},
   {'id': '872', 'teamShortName': 'TLAT'},
   {'id': '876', 'teamShortName': 'TWS'},
   {'id': '881', 'teamShortName': 'ZIMSXI'},
   {'id': '886', 'teamShortName': 'PCCSXI'},
   {'id': '1032', 'teamShortName': 'JERW'},
   {'id': '887', 'teamShortName': 'A1'},
   {'id': '892', 'teamShortName': 'A2'},
   {'id': '897', 'teamShortName': 'TKY'},
   {'id': '902', 'teamShortName': 'TRKW'},
   {'id': '903', 'teamShortName': 'MPR'},
   {'id': '908', 'teamShortName': 'TUSKS'},
   {'id': '912', 'teamShortName': 'LIMPO'},
   {'id': '917', 'teamShortName': 'WPR'},
   {'id': '918', 'teamShortName': 'GRB'},
   {'id': '922', 'teamShortName': 'NWEST'},
   {'id': '1027', 'teamShortName': 'NOR'},
   {'id': '559', 'teamShortName': 'SLE'},
   {'id': '579', 'teamShortName': 'TKMNE'},
   {'id': '580', 'teamShortName': 'ETS'},
   {'id': '581', 'teamShortName': 'NMP'},
   {'id': '582', 'teamShortName': 'SBS'},
   {'id': '583', 'teamShortName': 'SPL'},
   {'id': '584', 'teamShortName': 'NBB'},
   {'id': '585', 'teamShortName': 'AA'},
   {'id': '586', 'teamShortName': 'SOL'},
   {'id': '587', 'teamShortName': 'GGS'},
   {'id': '588', 'teamShortName': 'HHS'},
   {'id': '589', 'teamShortName': 'ZR'},
   {'id': '590', 'teamShortName': 'KUTW'},
   {'id': '591', 'teamShortName': 'BTW'},
   {'id': '592', 'teamShortName': 'USAW'},
   {'id': '593', 'teamShortName': 'KUWU19'},
   {'id': '594', 'teamShortName': 'INDWBPXI'},
   {'id': '595', 'teamShortName': 'CDG'},
   {'id': '578', 'teamShortName': 'ATMWS'},
   {'id': '577', 'teamShortName': 'BFT'},
   {'id': '560', 'teamShortName': 'BRAZIL'},
   {'id': '561', 'teamShortName': 'CZE'},
   {'id': '562', 'teamShortName': 'SHN'},
   {'id': '563', 'teamShortName': 'MDV'},
   {'id': '564', 'teamShortName': 'GIB'},
   {'id': '565', 'teamShortName': 'MMR'},
   {'id': '566', 'teamShortName': 'IDN'},
   {'id': '567', 'teamShortName': 'GM'},
   {'id': '568', 'teamShortName': 'SWZ'},
   {'id': '569', 'teamShortName': 'RWA'},
   {'id': '570', 'teamShortName': 'LSO'},
   {'id': '571', 'teamShortName': 'SAU'},
   {'id': '572', 'teamShortName': 'ADK'},
   {'id': '573', 'teamShortName': 'RDR'},
   {'id': '574', 'teamShortName': 'EBR'},
   {'id': '575', 'teamShortName': 'GGG'},
   {'id': '576', 'teamShortName': 'DBC'},
   {'id': '596', 'teamShortName': 'PORT'},
   {'id': '597', 'teamShortName': 'DEG'},
   {'id': '598', 'teamShortName': 'UBL'},
   {'id': '618', 'teamShortName': 'TREW'},
   {'id': '619', 'teamShortName': 'SULW'},
   {'id': '620', 'teamShortName': 'SOUW'},
   {'id': '621', 'teamShortName': 'SLT'},
   {'id': '622', 'teamShortName': 'CGC'},
   {'id': '623', 'teamShortName': 'CW'},
   {'id': '624', 'teamShortName': 'RPR'},
   {'id': '625', 'teamShortName': 'DP'},
   {'id': '626', 'teamShortName': 'RSR'},
   {'id': '627', 'teamShortName': 'KLT'},
   {'id': '628', 'teamShortName': 'FLH'},
   {'id': '629', 'teamShortName': 'FYO'},
   {'id': '630', 'teamShortName': 'DSR'},
   {'id': '631', 'teamShortName': 'PGR'},
   {'id': '632', 'teamShortName': 'HSR'},
   {'id': '633', 'teamShortName': 'SGP'},
   {'id': '639', 'teamShortName': 'INDWC'},
   {'id': '617', 'teamShortName': 'MSGW'},
   {'id': '616', 'teamShortName': 'LDNW'},
   {'id': '599', 'teamShortName': 'QLD'},
   {'id': '600', 'teamShortName': 'BGT'},
   {'id': '601', 'teamShortName': 'AD'},
   {'id': '602', 'teamShortName': 'PD'},
   {'id': '603', 'teamShortName': 'JPNU19'},
   {'id': '604', 'teamShortName': 'NGAU19'},
   {'id': '605', 'teamShortName': 'MIL'},
   {'id': '606', 'teamShortName': 'WEF'},
   {'id': '607', 'teamShortName': 'BRM'},
   {'id': '608', 'teamShortName': 'LDN'},
   {'id': '609', 'teamShortName': 'MSG'},
   {'id': '610', 'teamShortName': 'SUL'},
   {'id': '611', 'teamShortName': 'SOU'},
   {'id': '612', 'teamShortName': 'TRE'},
   {'id': '613', 'teamShortName': 'MILW'},
   {'id': '614', 'teamShortName': 'WELW'},
   {'id': '615', 'teamShortName': 'BRMW'},
   {'id': '648', 'teamShortName': 'INDIAWB'},
   {'id': '403', 'teamShortName': 'SOUTH'},
   {'id': '149', 'teamShortName': 'GLAM'},
   {'id': '170', 'teamShortName': 'BRD'},
   {'id': '171', 'teamShortName': 'RAJ'},
   {'id': '172', 'teamShortName': 'SLU19'},
   {'id': '173', 'teamShortName': 'ENGU19'},
   {'id': '183', 'teamShortName': 'PWI'},
   {'id': '184', 'teamShortName': 'KTK'},
   {'id': '185', 'teamShortName': 'DEN'},
   {'id': '186', 'teamShortName': 'AKL'},
   {'id': '187', 'teamShortName': 'RUH'},
   {'id': '188', 'teamShortName': 'NEDW'},
   {'id': '189', 'teamShortName': 'IREW'},
   {'id': '190', 'teamShortName': 'SIN'},
   {'id': '191', 'teamShortName': 'CACXI'},
   {'id': '192', 'teamShortName': 'SYT'},
   {'id': '193', 'teamShortName': 'BRH'},
   {'id': '194', 'teamShortName': 'HBH'},
   {'id': '195', 'teamShortName': 'MLR'},
   {'id': '168', 'teamShortName': 'NCC'},
   {'id': '167', 'teamShortName': 'MP'},
   {'id': '150', 'teamShortName': 'KENT'},
   {'id': '151', 'teamShortName': 'GLOUCS'},
   {'id': '152', 'teamShortName': 'ESS'},
   {'id': '153', 'teamShortName': 'HAM'},
   {'id': '154', 'teamShortName': 'SLCPXI'},
   {'id': '155', 'teamShortName': 'WAR'},
   {'id': '156', 'teamShortName': 'CEN'},
   {'id': '157', 'teamShortName': 'LIONS'},
   {'id': '158', 'teamShortName': 'SAUS'},
   {'id': '159', 'teamShortName': 'GAW'},
   {'id': '160', 'teamShortName': 'EA'},
   {'id': '161', 'teamShortName': 'NAM'},
   {'id': '162', 'teamShortName': 'ASM'},
   {'id': '163', 'teamShortName': 'GUJ'},
   {'id': '164', 'teamShortName': 'QL'},
   {'id': '165', 'teamShortName': 'ECBXI'},
   {'id': '166', 'teamShortName': 'TAS'},
   {'id': '196', 'teamShortName': 'MLS'},
   {'id': '197', 'teamShortName': 'PRS'},
   {'id': '198', 'teamShortName': 'SYS'},
   {'id': '223', 'teamShortName': 'AFGU19'},
   {'id': '224', 'teamShortName': 'BANU19'},
   {'id': '226', 'teamShortName': 'IREU19'},
   {'id': '228', 'teamShortName': 'SCOU19'},
   {'id': '229', 'teamShortName': 'NPLU19'},
   {'id': '230', 'teamShortName': 'NAMU19'},
   {'id': '231', 'teamShortName': 'INDB'},
   {'id': '232', 'teamShortName': 'BEN'},
   {'id': '233', 'teamShortName': 'NZONE'},
   {'id': '234', 'teamShortName': 'WZONE'},
   {'id': '235', 'teamShortName': 'EZONE'},
   {'id': '236', 'teamShortName': 'SZONE'},
   {'id': '237', 'teamShortName': 'CZONE'},
   {'id': '238', 'teamShortName': 'PASXI'},
   {'id': '239', 'teamShortName': 'IWXI'},
   {'id': '240', 'teamShortName': 'MUMA'},
   {'id': '241', 'teamShortName': 'AP'},
   {'id': '222', 'teamShortName': 'PNGU19'},
   {'id': '221', 'teamShortName': 'ZIMU19'},
   {'id': '199', 'teamShortName': 'ADS'},
   {'id': '200', 'teamShortName': 'HAR'},
   {'id': '201', 'teamShortName': 'BB'},
   {'id': '202', 'teamShortName': 'CK'},
   {'id': '203', 'teamShortName': 'DG'},
   {'id': '204', 'teamShortName': 'DR'},
   {'id': '205', 'teamShortName': 'KRB'},
   {'id': '206', 'teamShortName': 'SR'},
   {'id': '207', 'teamShortName': 'WIA'},
   {'id': '208', 'teamShortName': 'BCD'},
   {'id': '209', 'teamShortName': 'KW'},
   {'id': '210', 'teamShortName': 'NN'},
   {'id': '211', 'teamShortName': 'RUR'},
   {'id': '212', 'teamShortName': 'UR'},
   {'id': '213', 'teamShortName': 'WU'},
   {'id': '214', 'teamShortName': 'UN'},
   {'id': '220', 'teamShortName': 'WIU19'},
   {'id': '242', 'teamShortName': 'HYD'},
   {'id': '148', 'teamShortName': 'SUR'},
   {'id': '2', 'teamShortName': 'IND'},
   {'id': '26', 'teamShortName': 'CAN'},
   {'id': '27', 'teamShortName': 'IRE'},
   {'id': '36', 'teamShortName': 'INDBLUE'},
   {'id': '41', 'teamShortName': 'SUS'},
   {'id': '42', 'teamShortName': 'ENGA'},
   {'id': '43', 'teamShortName': 'SLA'},
   {'id': '44', 'teamShortName': 'UGA'},
   {'id': '52', 'teamShortName': 'VIC'},
   {'id': '53', 'teamShortName': 'ACTXI'},
   {'id': '54', 'teamShortName': 'INDU19'},
   {'id': '55', 'teamShortName': 'NZU19'},
   {'id': '56', 'teamShortName': 'PAKU19'},
   {'id': '57', 'teamShortName': 'RSAU19'},
   {'id': '71', 'teamShortName': 'MLY'},
   {'id': '72', 'teamShortName': 'NEP'},
   {'id': '74', 'teamShortName': 'MDX'},
   {'id': '77', 'teamShortName': 'GER'},
   {'id': '25', 'teamShortName': 'BER'},
   {'id': '24', 'teamShortName': 'NED'},
   {'id': '3', 'teamShortName': 'PAK'},
   {'id': '4', 'teamShortName': 'AUS'},
   {'id': '5', 'teamShortName': 'SL'},
   {'id': '6', 'teamShortName': 'BAN'},
   {'id': '7', 'teamShortName': 'UAE'},
   {'id': '8', 'teamShortName': 'HKC'},
   {'id': '9', 'teamShortName': 'ENG'},
   {'id': '10', 'teamShortName': 'WI'},
   {'id': '11', 'teamShortName': 'RSA'},
   {'id': '12', 'teamShortName': 'ZIM'},
   {'id': '13', 'teamShortName': 'NZ'},
   {'id': '14', 'teamShortName': 'KEN'},
   {'id': '15', 'teamShortName': 'USA'},
   {'id': '18', 'teamShortName': 'INDSR'},
   {'id': '20', 'teamShortName': 'INDGREEN'},
   {'id': '21', 'teamShortName': 'INDRED'},
   {'id': '23', 'teamShortName': 'SCO'},
   {'id': '78', 'teamShortName': 'INDA'},
   {'id': '79', 'teamShortName': 'AUSA'},
   {'id': '80', 'teamShortName': 'NZA'},
   {'id': '105', 'teamShortName': 'OTG'},
   {'id': '119', 'teamShortName': 'SOM'},
   {'id': '122', 'teamShortName': 'MD'},
   {'id': '123', 'teamShortName': 'BP'},
   {'id': '125', 'teamShortName': 'BIJ'},
   {'id': '128', 'teamShortName': 'KAR'},
   {'id': '129', 'teamShortName': 'AUSU19'},
   {'id': '130', 'teamShortName': 'WIS'},
   {'id': '134', 'teamShortName': 'RGR'},
   {'id': '139', 'teamShortName': 'NOTTS'},
   {'id': '140', 'teamShortName': 'WARKS'},
   {'id': '141', 'teamShortName': 'DUR'},
   {'id': '142', 'teamShortName': 'NHNTS'},
   {'id': '143', 'teamShortName': 'LANCS'},
   {'id': '144', 'teamShortName': 'DERBY'},
   {'id': '145', 'teamShortName': 'LEIC'},
   {'id': '146', 'teamShortName': 'YORKS'},
   {'id': '104', 'teamShortName': 'NSW'},
   {'id': '103', 'teamShortName': 'WAY'},
   {'id': '81', 'teamShortName': 'DEL'},
   {'id': '82', 'teamShortName': 'ROI'},
   {'id': '84', 'teamShortName': 'TT'},
   {'id': '86', 'teamShortName': 'BPXI'},
   {'id': '87', 'teamShortName': 'WA'},
   {'id': '88', 'teamShortName': 'SKST'},
   {'id': '89', 'teamShortName': 'TIT'},
   {'id': '90', 'teamShortName': 'DOL'},
   {'id': '92', 'teamShortName': 'TN'},
   {'id': '93', 'teamShortName': 'UP'},

In [380]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/team/2"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'types': [{'header': 'Batting'}, {'value': 'mostRuns', 'header': 'Most Runs', 'category': 'Batting'}, {'value': 'highestScore', 'header': 'Highest Scores', 'category': 'Batting'}, {'value': 'highestAvg', 'header': 'Best Batting Average', 'category': 'Batting'}, {'value': 'highestSr', 'header': 'Best Batting Strike Rate', 'category': 'Batting'}, {'value': 'mostHundreds', 'header': 'Most Hundreds', 'category': 'Batting'}, {'value': 'mostFifties', 'header': 'Most Fifties', 'category': 'Batting'}, {'value': 'mostFours', 'header': 'Most Fours', 'category': 'Batting'}, {'value': 'mostSixes', 'header': 'Most Sixes', 'category': 'Batting'}, {'value': 'mostNineties', 'header': 'Most Nineties', 'category': 'Batting'}, {'header': 'Bowling'}, {'value': 'mostWickets', 'header': 'Most Wickets', 'category': 'Bowling'}, {'value': 'lowestAvg', 'header': 'Best Bowling Average', 'category': 'Bowling'}, {'value': 'bestBowlingInnings', 'header': 'Best Bowling ', 'category': 'Bowling'}, {'value': 'mostFiveWickets', 'header': 'Most 5 Wickets Haul', 'category': 'Bowling'}, {'value': 'lowestEcon', 'header': 'Best Economy', 'category': 'Bowling'}, {'value': 'lowestSr', 'header': 'Best Bowling Strike Rate', 'category': 'Bowling'}], 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com', 'webURL': 'www.cricbuzz.com'}}

In [381]:
response.json()

{'types': [{'header': 'Batting'},
  {'value': 'mostRuns', 'header': 'Most Runs', 'category': 'Batting'},
  {'value': 'highestScore', 'header': 'Highest Scores', 'category': 'Batting'},
  {'value': 'highestAvg',
   'header': 'Best Batting Average',
   'category': 'Batting'},
  {'value': 'highestSr',
   'header': 'Best Batting Strike Rate',
   'category': 'Batting'},
  {'value': 'mostHundreds', 'header': 'Most Hundreds', 'category': 'Batting'},
  {'value': 'mostFifties', 'header': 'Most Fifties', 'category': 'Batting'},
  {'value': 'mostFours', 'header': 'Most Fours', 'category': 'Batting'},
  {'value': 'mostSixes', 'header': 'Most Sixes', 'category': 'Batting'},
  {'value': 'mostNineties', 'header': 'Most Nineties', 'category': 'Batting'},
  {'header': 'Bowling'},
  {'value': 'mostWickets', 'header': 'Most Wickets', 'category': 'Bowling'},
  {'value': 'lowestAvg',
   'header': 'Best Bowling Average',
   'category': 'Bowling'},
  {'value': 'bestBowlingInnings',
   'header': 'Best Bowling ',
   'category': 'Bowling'},
  {'value': 'mostFiveWickets',
   'header': 'Most 5 Wickets Haul',
   'category': 'Bowling'},
  {'value': 'lowestEcon', 'header': 'Best Economy', 'category': 'Bowling'},
  {'value': 'lowestSr',
   'header': 'Best Bowling Strike Rate',
   'category': 'Bowling'}],
 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com'}}

In [400]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/international"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'seriesMapProto': [{'date': 'FEBRUARY 2024', 'series': [{'id': 7572, 'name': 'ICC Cricket World Cup League Two 2023-27', 'startDt': '1707955200000', 'endDt': '1806364800000'}]}, {'date': 'FEBRUARY 2026', 'series': [{'id': 11253, 'name': "ICC Men's T20 World Cup 2026", 'startDt': '1770422400000', 'endDt': '1772928000000'}, {'id': 11542, 'name': 'Quadrangular T20I Series in Thailand 2026 ', 'startDt': '1771977600000', 'endDt': '1772236800000'}, {'id': 11581, 'name': 'Kuwait tour of Hong Kong, China, 2026', 'startDt': '1771977600000', 'endDt': '1772323200000'}]}, {'date': 'MARCH 2026', 'series': [{'id': 11570, 'name': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026", 'startDt': '1772928000000', 'endDt': '1773619200000'}, {'id': 11584, 'name': 'Pakistan tour of Bangladesh, 2026', 'startDt': '1773187200000', 'endDt': '1773532800000'}, {'id': 11617, 'name': 'Afghanistan v Sri Lanka in UAE, 2026', 'startDt': '1773360000000', 'endDt': '1774396800000'}, {'id': 10234, 'name': 'South Africa tour of New Zealand, 2026', 'startDt': '1773532800000', 'endDt': '1774396800000'}]}, {'date': 'JUNE 2026', 'series': [{'id': 10559, 'name': 'New Zealand tour of England, 2026', 'startDt': '1780531200000', 'endDt': '1782691200000'}, {'id': 10532, 'name': 'India tour of England, 2026', 'startDt': '1782864000000', 'endDt': '1784419200000'}]}, {'date': 'AUGUST 2026', 'series': [{'id': 10565, 'name': 'Pakistan tour of England 2026', 'startDt': '1787097600000', 'endDt': '1788912000000'}]}, {'date': 'SEPTEMBER 2026', 'series': [{'id': 10576, 'name': 'Sri Lanka tour of England, 2026', 'startDt': '1789430400000', 'endDt': '1790467200000'}, {'id': 11595, 'name': 'Australia tour of South Africa, 2026', 'startDt': '1790208000000', 'endDt': '1793404800000'}]}, {'date': 'NOVEMBER 2026', 'series': [{'id': 11606, 'name': 'Bangladesh tour of South Africa, 2026', 'startDt': '1794700800000', 'endDt': '1797120000000'}]}, {'date': 'DECEMBER 2026', 'series': [{'id': 11612, 'name': 'England tour of South Africa, 2026-27', 'startDt': '1797465600000', 'endDt': '1799971200000'}]}], 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [401]:
series_data = response.json()
series_data

{'seriesMapProto': [{'date': 'FEBRUARY 2024',
   'series': [{'id': 7572,
     'name': 'ICC Cricket World Cup League Two 2023-27',
     'startDt': '1707955200000',
     'endDt': '1806364800000'}]},
  {'date': 'FEBRUARY 2026',
   'series': [{'id': 11253,
     'name': "ICC Men's T20 World Cup 2026",
     'startDt': '1770422400000',
     'endDt': '1772928000000'},
    {'id': 11542,
     'name': 'Quadrangular T20I Series in Thailand 2026 ',
     'startDt': '1771977600000',
     'endDt': '1772236800000'},
    {'id': 11581,
     'name': 'Kuwait tour of Hong Kong, China, 2026',
     'startDt': '1771977600000',
     'endDt': '1772323200000'}]},
  {'date': 'MARCH 2026',
   'series': [{'id': 11570,
     'name': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026",
     'startDt': '1772928000000',
     'endDt': '1773619200000'},
    {'id': 11584,
     'name': 'Pakistan tour of Bangladesh, 2026',
     'startDt': '1773187200000',
     'endDt': '1773532800000'},
    {'id': 11617,
     'name': 'Afghanistan v Sri Lanka in UAE, 2026',
     'startDt': '1773360000000',
     'endDt': '1774396800000'},
    {'id': 10234,
     'name': 'South Africa tour of New Zealand, 2026',
     'startDt': '1773532800000',
     'endDt': '1774396800000'}]},
  {'date': 'JUNE 2026',
   'series': [{'id': 10559,
     'name': 'New Zealand tour of England, 2026',
     'startDt': '1780531200000',
     'endDt': '1782691200000'},
    {'id': 10532,
     'name': 'India tour of England, 2026',
     'startDt': '1782864000000',
     'endDt': '1784419200000'}]},
  {'date': 'AUGUST 2026',
   'series': [{'id': 10565,
     'name': 'Pakistan tour of England 2026',
     'startDt': '1787097600000',
     'endDt': '1788912000000'}]},
  {'date': 'SEPTEMBER 2026',
   'series': [{'id': 10576,
     'name': 'Sri Lanka tour of England, 2026',
     'startDt': '1789430400000',
     'endDt': '1790467200000'},
    {'id': 11595,
     'name': 'Australia tour of South Africa, 2026',
     'startDt': '1790208000000',
     'endDt': '1793404800000'}]},
  {'date': 'NOVEMBER 2026',
   'series': [{'id': 11606,
     'name': 'Bangladesh tour of South Africa, 2026',
     'startDt': '1794700800000',
     'endDt': '1797120000000'}]},
  {'date': 'DECEMBER 2026',
   'series': [{'id': 11612,
     'name': 'England tour of South Africa, 2026-27',
     'startDt': '1797465600000',
     'endDt': '1799971200000'}]}],
 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [402]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

series_data_archive = response.json()

{'seriesMapProto': [{'date': '2026', 'series': [{'id': 11528, 'name': 'Bahrain tour of Qatar 2026', 'startDt': '1770681600000', 'endDt': '1771113600000', 'thumborImageId': 379130}, {'id': 11253, 'name': "ICC Men's T20 World Cup 2026", 'startDt': '1770422400000', 'endDt': '1772928000000', 'thumborImageId': 868238}, {'id': 11429, 'name': 'Australia tour of Pakistan, 2026', 'startDt': '1769644800000', 'endDt': '1769904000000', 'thumborImageId': 839065}, {'id': 11273, 'name': 'Ireland tour of United Arab Emirates 2026', 'startDt': '1769644800000', 'endDt': '1769817600000', 'thumborImageId': 841768}, {'id': 9551, 'name': 'West Indies tour of South Africa, 2026', 'startDt': '1769472000000', 'endDt': '1769817600000', 'thumborImageId': 839068}, {'id': 11331, 'name': 'Ireland vs Italy in UAE, 2026', 'startDt': '1769126400000', 'endDt': '1769385600000', 'thumborImageId': 379130}, {'id': 10774, 'name': 'England tour of Sri Lanka 2026', 'startDt': '1769040000000', 'endDt': '1770076800000', 'thumborImageId': 840993}, {'id': 11176, 'name': 'Afghanistan v West Indies in UAE, 2026', 'startDt': '1768780800000', 'endDt': '1769040000000', 'thumborImageId': 379130}, {'id': 10102, 'name': 'New Zealand tour of India, 2026', 'startDt': '1768089600000', 'endDt': '1769817600000', 'thumborImageId': 820663}, {'id': 11317, 'name': 'Pakistan tour of Sri Lanka, 2026', 'startDt': '1767744000000', 'endDt': '1768089600000', 'thumborImageId': 379130}]}, {'date': '2025', 'series': [{'id': 11377, 'name': 'Cambodia tour of Indonesia, 2025', 'startDt': '1766448000000', 'endDt': '1766880000000', 'thumborImageId': 379130}, {'id': 11141, 'name': 'Myanmar tour of Bhutan, 2025', 'startDt': '1766448000000', 'endDt': '1766966400000', 'thumborImageId': 379130}, {'id': 11363, 'name': 'SEA Games Mens Twenty20 Cricket Competition 2025', 'startDt': '1765238400000', 'endDt': '1765584000000', 'thumborImageId': 379130}, {'id': 11132, 'name': 'Bahrain tour of Bhutan, 2025', 'startDt': '1765152000000', 'endDt': '1765670400000', 'thumborImageId': 379130}, {'id': 11364, 'name': 'Croatia tour of Spain, 2025', 'startDt': '1764892800000', 'endDt': '1765065600000', 'thumborImageId': 379130}, {'id': 11295, 'name': 'West Africa Trophy 2025', 'startDt': '1764806400000', 'endDt': '1765670400000', 'thumborImageId': 379130}, {'id': 11220, 'name': 'Brazil tour of Argentina 2025', 'startDt': '1764288000000', 'endDt': '1764460800000', 'thumborImageId': 379130}, {'id': 11234, 'name': 'Mini SEA Mens Twenty20 Cricket Competition 2025', 'startDt': '1763942400000', 'endDt': '1764547200000', 'thumborImageId': 379130}, {'id': 9107, 'name': 'The Ashes, 2025-26', 'startDt': '1763683200000', 'endDt': '1767830400000', 'thumborImageId': 784768}, {'id': 11198, 'name': 'Bahrain tour of Indonesia, 2025', 'startDt': '1763424000000', 'endDt': '1763683200000', 'thumborImageId': 379130}]}], 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [403]:
series_data_archive

{'seriesMapProto': [{'date': '2026',
   'series': [{'id': 11528,
     'name': 'Bahrain tour of Qatar 2026',
     'startDt': '1770681600000',
     'endDt': '1771113600000',
     'thumborImageId': 379130},
    {'id': 11253,
     'name': "ICC Men's T20 World Cup 2026",
     'startDt': '1770422400000',
     'endDt': '1772928000000',
     'thumborImageId': 868238},
    {'id': 11429,
     'name': 'Australia tour of Pakistan, 2026',
     'startDt': '1769644800000',
     'endDt': '1769904000000',
     'thumborImageId': 839065},
    {'id': 11273,
     'name': 'Ireland tour of United Arab Emirates 2026',
     'startDt': '1769644800000',
     'endDt': '1769817600000',
     'thumborImageId': 841768},
    {'id': 9551,
     'name': 'West Indies tour of South Africa, 2026',
     'startDt': '1769472000000',
     'endDt': '1769817600000',
     'thumborImageId': 839068},
    {'id': 11331,
     'name': 'Ireland vs Italy in UAE, 2026',
     'startDt': '1769126400000',
     'endDt': '1769385600000',
     'thumborImageId': 379130},
    {'id': 10774,
     'name': 'England tour of Sri Lanka 2026',
     'startDt': '1769040000000',
     'endDt': '1770076800000',
     'thumborImageId': 840993},
    {'id': 11176,
     'name': 'Afghanistan v West Indies in UAE, 2026',
     'startDt': '1768780800000',
     'endDt': '1769040000000',
     'thumborImageId': 379130},
    {'id': 10102,
     'name': 'New Zealand tour of India, 2026',
     'startDt': '1768089600000',
     'endDt': '1769817600000',
     'thumborImageId': 820663},
    {'id': 11317,
     'name': 'Pakistan tour of Sri Lanka, 2026',
     'startDt': '1767744000000',
     'endDt': '1768089600000',
     'thumborImageId': 379130}]},
  {'date': '2025',
   'series': [{'id': 11377,
     'name': 'Cambodia tour of Indonesia, 2025',
     'startDt': '1766448000000',
     'endDt': '1766880000000',
     'thumborImageId': 379130},
    {'id': 11141,
     'name': 'Myanmar tour of Bhutan, 2025',
     'startDt': '1766448000000',
     'endDt': '1766966400000',
     'thumborImageId': 379130},
    {'id': 11363,
     'name': 'SEA Games Mens Twenty20 Cricket Competition 2025',
     'startDt': '1765238400000',
     'endDt': '1765584000000',
     'thumborImageId': 379130},
    {'id': 11132,
     'name': 'Bahrain tour of Bhutan, 2025',
     'startDt': '1765152000000',
     'endDt': '1765670400000',
     'thumborImageId': 379130},
    {'id': 11364,
     'name': 'Croatia tour of Spain, 2025',
     'startDt': '1764892800000',
     'endDt': '1765065600000',
     'thumborImageId': 379130},
    {'id': 11295,
     'name': 'West Africa Trophy 2025',
     'startDt': '1764806400000',
     'endDt': '1765670400000',
     'thumborImageId': 379130},
    {'id': 11220,
     'name': 'Brazil tour of Argentina 2025',
     'startDt': '1764288000000',
     'endDt': '1764460800000',
     'thumborImageId': 379130},
    {'id': 11234,
     'name': 'Mini SEA Mens Twenty20 Cricket Competition 2025',
     'startDt': '1763942400000',
     'endDt': '1764547200000',
     'thumborImageId': 379130},
    {'id': 9107,
     'name': 'The Ashes, 2025-26',
     'startDt': '1763683200000',
     'endDt': '1767830400000',
     'thumborImageId': 784768},
    {'id': 11198,
     'name': 'Bahrain tour of Indonesia, 2025',
     'startDt': '1763424000000',
     'endDt': '1763683200000',
     'thumborImageId': 379130}]}],
 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [436]:
import requests
from collections import defaultdict

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
    "x-rapidapi-key": "653885c323mshe1e1aa5b237fceep198239jsn9190fe02c92f",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)
data5 = response.json()

In [ ]:
win_count = defaultdict(int)  # dictionary to store win count
for typematch in data5.get('typeMatches', []):
    for seriesmatch in typematch.get('seriesMatches', []):
        series_info = seriesmatch.get('seriesAdWrapper', {})
        for match in series_info.get('matches', []):
            matchinfo = match.get('matchInfo', {})
            status = matchinfo.get('status', '')

            if 'won by' in status:
                winner = status.split('won')[0]
                win_count[winner] += 1

# sorting

sorted_win = sorted(win_count.items(), key=lambda x:x[1], reverse=True)

# display win result

for i,j in win_count.items():
    print(f"{i} - {j}")

South Africa  - 2
West Indies  - 2
England  - 1
Afghanistan  - 1
India  - 1
Zimbabwe  - 1
Pakistan  - 1
Nepal  - 1
Australia  - 1
Jammu and Kashmir  - 1
Central Districts  - 2
Wellington  - 1
South Australia  - 1
Victoria  - 1
South Africa Emerging Players  - 1
Knights  - 1
South Western Districts  - 1
Western Australia  - 1
Queensland  - 1
New South Wales  - 1
Lions  - 1
England Lions  - 2
Australia Women  - 2
India Women  - 1
Sri Lanka Women  - 2
South Africa Women  - 1
India A Women  - 2
Sri Lanka A Women  - 1
Bangladesh A Women  - 2

In [466]:
cursor .execute("""
                create table wins (
                team varchar(30),
                wincount smallint)
            """)
q5 = """
    insert into wins values
    (%s,%s)
"""
for i,j in win_count.items():
    row = (i,j)
    cursor.execute(q5, row)

In [463]:
win_count

defaultdict(int,
            {'South Africa ': 2,
             'West Indies ': 2,
             'England ': 1,
             'Afghanistan ': 1,
             'India ': 1,
             'Zimbabwe ': 1,
             'Pakistan ': 1,
             'Nepal ': 1,
             'Australia ': 1,
             'Jammu and Kashmir ': 1,
             'Central Districts ': 2,
             'Wellington ': 1,
             'South Australia ': 1,
             'Victoria ': 1,
             'South Africa Emerging Players ': 1,
             'Knights ': 1,
             'South Western Districts ': 1,
             'Western Australia ': 1,
             'Queensland ': 1,
             'New South Wales ': 1,
             'Lions ': 1,
             'England Lions ': 2,
             'Australia Women ': 2,
             'India Women ': 1,
             'Sri Lanka Women ': 2,
             'South Africa Women ': 1,
             'India A Women ': 2,
             'Sri Lanka A Women ': 1,
             'Bangladesh A Women ': 2})

In [451]:
data5['typeMatches'][0]['seriesMatches'][0]['seriesAdWrapper']['matches']

[{'matchInfo': {'matchId': 139362,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '41st Match, Super 8 Group 2 (Y2 v Y3)',
   'matchFormat': 'T20',
   'startDate': '1771680600000',
   'endDate': '1771693200000',
   'state': 'Complete',
   'status': 'Match abandoned without a ball bowled',
   'team1': {'teamId': 3,
    'teamName': 'Pakistan',
    'teamSName': 'PAK',
    'imageId': 776308},
   'team2': {'teamId': 13,
    'teamName': 'New Zealand',
    'teamSName': 'NZ',
    'imageId': 776333},
   'venueInfo': {'id': 15,
    'ground': 'R.Premadasa Stadium',
    'city': 'Colombo',
    'timezone': '+05:30',
    'latitude': '6.939966',
    'longitude': '79.872222'},
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'Abandon',
   'isFantasyEnabled': True}},
 {'matchInfo': {'matchId': 139263,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '32nd Match, Group B',
   'matchFormat': 'T20',
   'startDate': '1771320600000',
   'endDate': '1771333200000',
   'state': 'Complete',
   'status': 'Match abandoned due to rain (no toss)',
   'team1': {'teamId': 27,
    'teamName': 'Ireland',
    'teamSName': 'IRE',
    'imageId': 839366},
   'team2': {'teamId': 12,
    'teamName': 'Zimbabwe',
    'teamSName': 'ZIM',
    'imageId': 776198},
   'venueInfo': {'id': 254,
    'ground': 'Pallekele International Cricket Stadium',
    'city': 'Pallekele',
    'timezone': '+05:30',
    'latitude': '7.280691',
    'longitude': '80.722493'},
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'Abandon',
   'isFantasyEnabled': True}},
 {'matchInfo': {'matchId': 139381,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '43rd Match, Super 8 Group 1 (X1 v X4)',
   'matchFormat': 'T20',
   'startDate': '1771767000000',
   'endDate': '1771779600000',
   'state': 'Complete',
   'status': 'South Africa won by 76 runs',
   'team1': {'teamId': 11,
    'teamName': 'South Africa',
    'teamSName': 'RSA',
    'imageId': 776287},
   'team2': {'teamId': 2,
    'teamName': 'India',
    'teamSName': 'IND',
    'imageId': 776162},
   'venueInfo': {'id': 50,
    'ground': 'Narendra Modi Stadium',
    'city': 'Ahmedabad',
    'timezone': '+05:30',
    'latitude': '23.091785',
    'longitude': '72.597465'},
   'currBatTeamId': 11,
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'RSA Won',
   'isFantasyEnabled': True},
  'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
     'runs': 187,
     'wickets': 7,
     'overs': 19.6}},
   'team2Score': {'inngs1': {'inningsId': 2,
     'runs': 111,
     'wickets': 10,
     'overs': 18.5}}}},
 {'matchInfo': {'matchId': 139382,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '44th Match, Super 8 Group 1 (X2 v X3)',
   'matchFormat': 'T20',
   'startDate': '1771853400000',
   'endDate': '1771866000000',
   'state': 'Complete',
   'status': 'West Indies won by 107 runs',
   'team1': {'teamId': 10,
    'teamName': 'West Indies',
    'teamSName': 'WI',
    'imageId': 776191},
   'team2': {'teamId': 12,
    'teamName': 'Zimbabwe',
    'teamSName': 'ZIM',
    'imageId': 776198},
   'venueInfo': {'id': 81,
    'ground': 'Wankhede Stadium',
    'city': 'Mumbai',
    'timezone': '+05:30',
    'latitude': '18.938956',
    'longitude': '72.825719'},
   'currBatTeamId': 10,
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'WI Won',
   'isFantasyEnabled': True},
  'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
     'runs': 254,
     'wickets': 6,
     'overs': 19.6}},
   'team2Score': {'inngs1': {'inningsId': 2,
     'runs': 147,
     'wickets': 10,
     'overs': 17.4}}}},
 {'matchInfo': {'matchId': 139373,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '42nd Match, Super 8 Group 2 (Y1 v Y4)',
   'matchFormat': 'T20',
   'startDate': '1771752600000',
   'endDate': '1771765200000',
   'state': 'Complete',
   'status': 'England won by 51 runs',
   'team1': {'teamId': 9,
    'teamName': 'England',
    'teamSName': 'ENG',
    'imageId': 776237},
   'team2': {'teamId': 5,
    'teamName': 'Sri Lanka',
    'teamSName': 'SL',
    'imageId': 776254},
   'venueInfo': {'id': 254,
    'ground': 'Pallekele International Cricket Stadium',
    'city': 'Pallekele',
    'timezone': '+05:30',
    'latitude': '7.280691',
    'longitude': '80.722493'},
   'currBatTeamId': 9,
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'ENG Won',
   'isFantasyEnabled': True},
  'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
     'runs': 146,
     'wickets': 9,
     'overs': 19.6}},
   'team2Score': {'inngs1': {'inningsId': 2,
     'runs': 95,
     'wickets': 10,
     'overs': 16.4}}}},
 {'matchInfo': {'matchId': 139340,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '39th Match, Group D',
   'matchFormat': 'T20',
   'startDate': '1771507800000',
   'endDate': '1771520400000',
   'state': 'Complete',
   'status': 'Afghanistan won by 82 runs',
   'team1': {'teamId': 96,
    'teamName': 'Afghanistan',
    'teamSName': 'AFG',
    'imageId': 776177},
   'team2': {'teamId': 26,
    'teamName': 'Canada',
    'teamSName': 'CAN',
    'imageId': 776227},
   'venueInfo': {'id': 11,
    'ground': 'MA Chidambaram Stadium',
    'city': 'Chennai',
    'timezone': '+05:30',
    'latitude': '13.06282',
    'longitude': '80.279274'},
   'currBatTeamId': 96,
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'AFG Won'},
  'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
     'runs': 200,
     'wickets': 4,
     'overs': 19.6}},
   'team2Score': {'inngs1': {'inningsId': 2,
     'runs': 118,
     'wickets': 8,
     'overs': 19.6}}}},
 {'matchInfo': {'matchId': 139307,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '36th Match, Group A',
   'matchFormat': 'T20',
   'startDate': '1771421400000',
   'endDate': '1771434000000',
   'state': 'Complete',
   'status': 'India won by 17 runs',
   'team1': {'teamId': 2,
    'teamName': 'India',
    'teamSName': 'IND',
    'imageId': 776162},
   'team2': {'teamId': 24,
    'teamName': 'Netherlands',
    'teamSName': 'NED',
    'imageId': 776335},
   'venueInfo': {'id': 50,
    'ground': 'Narendra Modi Stadium',
    'city': 'Ahmedabad',
    'timezone': '+05:30',
    'latitude': '23.091785',
    'longitude': '72.597465'},
   'currBatTeamId': 2,
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'IND Won',
   'isFantasyEnabled': True},
  'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
     'runs': 193,
     'wickets': 6,
     'overs': 19.6}},
   'team2Score': {'inngs1': {'inningsId': 2,
     'runs': 176,
     'wickets': 7,
     'overs': 19.6}}}},
 {'matchInfo': {'matchId': 139329,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '38th Match, Group B',
   'matchFormat': 'T20',
   'startDate': '1771493400000',
   'endDate': '1771506000000',
   'state': 'Complete',
   'status': 'Zimbabwe won by 6 wkts',
   'team1': {'teamId': 5,
    'teamName': 'Sri Lanka',
    'teamSName': 'SL',
    'imageId': 776254},
   'team2': {'teamId': 12,
    'teamName': 'Zimbabwe',
    'teamSName': 'ZIM',
    'imageId': 776198},
   'venueInfo': {'id': 15,
    'ground': 'R.Premadasa Stadium',
    'city': 'Colombo',
    'timezone': '+05:30',
    'latitude': '6.939966',
    'longitude': '79.872222'},
   'currBatTeamId': 12,
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'ZIM Won',
   'isFantasyEnabled': True},
  'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
     'runs': 178,
     'wickets': 7,
     'overs': 19.6}},
   'team2Score': {'inngs1': {'inningsId': 2,
     'runs': 182,
     'wickets': 4,
     'overs': 19.3}}}},
 {'matchInfo': {'matchId': 139296,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '35th Match, Group A',
   'matchFormat': 'T20',
   'startDate': '1771407000000',
   'endDate': '1771419600000',
   'state': 'Complete',
   'status': 'Pakistan won by 102 runs',
   'team1': {'teamId': 3,
    'teamName': 'Pakistan',
    'teamSName': 'PAK',
    'imageId': 776308},
   'team2': {'teamId': 161,
    'teamName': 'Namibia',
    'teamSName': 'NAM',
    'imageId': 776326},
   'venueInfo': {'id': 14,
    'ground': 'Sinhalese Sports Club',
    'city': 'Colombo',
    'timezone': '+05:30',
    'latitude': '6.905929',
    'longitude': '79.869403'},
   'currBatTeamId': 3,
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'PAK Won',
   'isFantasyEnabled': True},
  'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
     'runs': 199,
     'wickets': 3,
     'overs': 19.6}},
   'team2Score': {'inngs1': {'inningsId': 2,
     'runs': 97,
     'wickets': 10,
     'overs': 17.3}}}},
 {'matchInfo': {'matchId': 139285,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '34th Match, Group D',
   'matchFormat': 'T20',
   'startDate': '1771392600000',
   'endDate': '1771405200000',
   'state': 'Complete',
   'status': 'South Africa won by 6 wkts',
   'team1': {'teamId': 7,
    'teamName': 'United Arab Emirates',
    'teamSName': 'UAE',
    'imageId': 776242},
   'team2': {'teamId': 11,
    'teamName': 'South Africa',
    'teamSName': 'RSA',
    'imageId': 776287},
   'venueInfo': {'id': 51,
    'ground': 'Arun Jaitley Stadium',
    'city': 'Delhi',
    'timezone': '+05:30',
    'latitude': '28.637891',
    'longitude': '77.243073'},
   'currBatTeamId': 11,
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'RSA Won'},
  'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
     'runs': 122,
     'wickets': 6,
     'overs': 19.6}},
   'team2Score': {'inngs1': {'inningsId': 2,
     'runs': 123,
     'wickets': 4,
     'overs': 13.2}}}},
 {'matchInfo': {'matchId': 139274,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '33rd Match, Group C',
   'matchFormat': 'T20',
   'startDate': '1771335000000',
   'endDate': '1771347600000',
   'state': 'Complete',
   'status': 'Nepal won by 7 wkts',
   'team1': {'teamId': 23,
    'teamName': 'Scotland',
    'teamSName': 'SCO',
    'imageId': 776280},
   'team2': {'teamId': 72,
    'teamName': 'Nepal',
    'teamSName': 'NEP',
    'imageId': 776331},
   'venueInfo': {'id': 81,
    'ground': 'Wankhede Stadium',
    'city': 'Mumbai',
    'timezone': '+05:30',
    'latitude': '18.938956',
    'longitude': '72.825719'},
   'currBatTeamId': 72,
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'NEP Won'},
  'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
     'runs': 170,
     'wickets': 7,
     'overs': 19.6}},
   'team2Score': {'inngs1': {'inningsId': 2,
     'runs': 171,
     'wickets': 3,
     'overs': 19.2}}}},
 {'matchInfo': {'matchId': 139318,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '37th Match, Group C',
   'matchFormat': 'T20',
   'startDate': '1771479000000',
   'endDate': '1771491600000',
   'state': 'Complete',
   'status': 'West Indies won by 42 runs',
   'team1': {'teamId': 10,
    'teamName': 'West Indies',
    'teamSName': 'WI',
    'imageId': 776191},
   'team2': {'teamId': 527,
    'teamName': 'Italy',
    'teamSName': 'ITA',
    'imageId': 776295},
   'venueInfo': {'id': 31,
    'ground': 'Eden Gardens',
    'city': 'Kolkata',
    'timezone': '+05:30',
    'latitude': '22.564527',
    'longitude': '88.343247'},
   'currBatTeamId': 10,
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'WI Won'},
  'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
     'runs': 165,
     'wickets': 6,
     'overs': 19.6}},
   'team2Score': {'inngs1': {'inningsId': 2,
     'runs': 123,
     'wickets': 10,
     'overs': 17.6}}}},
 {'matchInfo': {'matchId': 139351,
   'seriesId': 11253,
   'seriesName': "ICC Men's T20 World Cup 2026",
   'matchDesc': '40th Match, Group B',
   'matchFormat': 'T20',
   'startDate': '1771594200000',
   'endDate': '1771606800000',
   'state': 'Complete',
   'status': 'Australia won by 9 wkts',
   'team1': {'teamId': 304,
    'teamName': 'Oman',
    'teamSName': 'OMAN',
    'imageId': 776328},
   'team2': {'teamId': 4,
    'teamName': 'Australia',
    'teamSName': 'AUS',
    'imageId': 776202},
   'venueInfo': {'id': 254,
    'ground': 'Pallekele International Cricket Stadium',
    'city': 'Pallekele',
    'timezone': '+05:30',
    'latitude': '7.280691',
    'longitude': '80.722493'},
   'currBatTeamId': 4,
   'seriesStartDt': '1770422400000',
   'seriesEndDt': '1773100800000',
   'isTimeAnnounced': True,
   'stateTitle': 'AUS Won'},
  'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
     'runs': 104,
     'wickets': 10,
     'overs': 16.2}},
   'team2Score': {'inngs1': {'inningsId': 2,
     'runs': 108,
     'wickets': 1,
     'overs': 9.4}}}}]

In [441]:
data5['typeMatches'][1]

{'matchType': 'Domestic',
 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10317,
    'seriesName': 'Ranji Trophy Elite 2025-26',
    'matches': [{'matchInfo': {'matchId': 125074,
       'seriesId': 10317,
       'seriesName': 'Ranji Trophy Elite 2025-26',
       'matchDesc': '2nd Semi Final',
       'matchFormat': 'TEST',
       'startDate': '1771126200000',
       'endDate': '1771497000000',
       'state': 'Complete',
       'status': 'Jammu and Kashmir won by 6 wkts',
       'team1': {'teamId': 232,
        'teamName': 'Bengal',
        'teamSName': 'BEN',
        'imageId': 172285},
       'team2': {'teamId': 252,
        'teamName': 'Jammu and Kashmir',
        'teamSName': 'JK',
        'imageId': 172305},
       'venueInfo': {'id': 437,
        'ground': 'Bengal Cricket Academy Ground',
        'city': 'Kalyani',
        'timezone': '+05:30',
        'latitude': '22.9792675',
        'longitude': '88.4416824'},
       'currBatTeamId': 252,
       'seriesStartDt': '1760486400000',
       'seriesEndDt': '1772409600000',
       'isTimeAnnounced': True,
       'stateTitle': 'JK Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 328,
         'wickets': 10,
         'overs': 97.1},
        'inngs2': {'inningsId': 3, 'runs': 99, 'wickets': 10, 'overs': 25.1}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 302,
         'wickets': 10,
         'overs': 76.1},
        'inngs2': {'inningsId': 4,
         'runs': 126,
         'wickets': 4,
         'overs': 34.4}}}},
     {'matchInfo': {'matchId': 125069,
       'seriesId': 10317,
       'seriesName': 'Ranji Trophy Elite 2025-26',
       'matchDesc': '1st Semi Final',
       'matchFormat': 'TEST',
       'startDate': '1771128000000',
       'endDate': '1771498800000',
       'state': 'Complete',
       'status': 'Match drawn',
       'team1': {'teamId': 128,
        'teamName': 'Karnataka',
        'teamSName': 'KAR',
        'imageId': 776345},
       'team2': {'teamId': 467,
        'teamName': 'Uttarakhand',
        'teamSName': 'UTK',
        'imageId': 172515},
       'venueInfo': {'id': 485,
        'ground': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
        'city': 'Lucknow',
        'timezone': '+05:30',
        'latitude': '26.846694',
        'longitude': '80.946166'},
       'seriesStartDt': '1760486400000',
       'seriesEndDt': '1772409600000',
       'isTimeAnnounced': True,
       'stateTitle': 'Complete'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 736,
         'wickets': 10,
         'overs': 194.4},
        'inngs2': {'inningsId': 3, 'runs': 323, 'wickets': 10, 'overs': 74.3}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 233,
         'wickets': 10,
         'overs': 88.5},
        'inngs2': {'inningsId': 4,
         'runs': 260,
         'wickets': 6,
         'overs': 61.6}}}}]}},
  {'seriesAdWrapper': {'seriesId': 10724,
    'seriesName': 'The Ford Trophy 2025-26',
    'matches': [{'matchInfo': {'matchId': 132164,
       'seriesId': 10724,
       'seriesName': 'The Ford Trophy 2025-26',
       'matchDesc': 'Final',
       'matchFormat': 'ODI',
       'startDate': '1771709400000',
       'endDate': '1771738200000',
       'state': 'Complete',
       'status': 'Central Districts won by 6 wkts',
       'team1': {'teamId': 312,
        'teamName': 'Canterbury',
        'teamSName': 'CNTBRY',
        'imageId': 172362},
       'team2': {'teamId': 313,
        'teamName': 'Central Districts',
        'teamSName': 'CD',
        'imageId': 172363},
       'venueInfo': {'id': 45,
        'ground': 'Basin Reserve',
        'city': 'Wellington',
        'timezone': '+13:00',
        'latitude': '-41.161720',
        'longitude': '175.323914'},
       'currBatTeamId': 313,
       'seriesStartDt': '1761350400000',
       'seriesEndDt': '1771891200000',
       'isTimeAnnounced': True,
       'stateTitle': 'CD Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 302,
         'wickets': 7,
         'overs': 49.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 303,
         'wickets': 4,
         'overs': 47.5}}}},
     {'matchInfo': {'matchId': 132153,
       'seriesId': 10724,
       'seriesName': 'The Ford Trophy 2025-26',
       'matchDesc': 'Eliminator',
       'matchFormat': 'ODI',
       'startDate': '1771536600000',
       'endDate': '1771565400000',
       'state': 'Complete',
       'status': 'Central Districts won by 211 runs',
       'team1': {'teamId': 313,
        'teamName': 'Central Districts',
        'teamSName': 'CD',
        'imageId': 172363},
       'team2': {'teamId': 314,
        'teamName': 'Wellington',
        'teamSName': 'WEL',
        'imageId': 172364},
       'venueInfo': {'id': 45,
        'ground': 'Basin Reserve',
        'city': 'Wellington',
        'timezone': '+13:00',
        'latitude': '-41.161720',
        'longitude': '175.323914'},
       'currBatTeamId': 313,
       'seriesStartDt': '1761350400000',
       'seriesEndDt': '1771891200000',
       'isTimeAnnounced': True,
       'stateTitle': 'CD Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 349,
         'wickets': 5,
         'overs': 49.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 138,
         'wickets': 10,
         'overs': 32.2}}}},
     {'matchInfo': {'matchId': 132142,
       'seriesId': 10724,
       'seriesName': 'The Ford Trophy 2025-26',
       'matchDesc': '30th Match',
       'matchFormat': 'ODI',
       'startDate': '1771363800000',
       'endDate': '1771392600000',
       'state': 'Complete',
       'status': 'Wellington won by 118 runs',
       'team1': {'teamId': 314,
        'teamName': 'Wellington',
        'teamSName': 'WEL',
        'imageId': 172364},
       'team2': {'teamId': 294,
        'teamName': 'Northern Districts',
        'teamSName': 'ND',
        'imageId': 172343},
       'venueInfo': {'id': 45,
        'ground': 'Basin Reserve',
        'city': 'Wellington',
        'timezone': '+13:00',
        'latitude': '-41.161720',
        'longitude': '175.323914'},
       'currBatTeamId': 314,
       'seriesStartDt': '1761350400000',
       'seriesEndDt': '1771891200000',
       'isTimeAnnounced': True,
       'stateTitle': 'WEL Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 281,
         'wickets': 7,
         'overs': 49.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 163,
         'wickets': 10,
         'overs': 36.1}}}}]}},
  {'seriesAdWrapper': {'seriesId': 10823,
    'seriesName': 'Sheffield Shield 2025-26',
    'matches': [{'matchInfo': {'matchId': 133380,
       'seriesId': 10823,
       'seriesName': 'Sheffield Shield 2025-26',
       'matchDesc': '24th Match',
       'matchFormat': 'TEST',
       'startDate': '1771212600000',
       'endDate': '1771497000000',
       'state': 'Complete',
       'status': 'Match drawn',
       'team1': {'teamId': 166,
        'teamName': 'Tasmania',
        'teamSName': 'TAS',
        'imageId': 172235},
       'team2': {'teamId': 104,
        'teamName': 'New South Wales',
        'teamSName': 'NSW',
        'imageId': 172196},
       'venueInfo': {'id': 39,
        'ground': 'Bellerive Oval',
        'city': 'Hobart',
        'timezone': '+11:00',
        'latitude': '-42.877296',
        'longitude': '147.374013'},
       'seriesStartDt': '1759536000000',
       'seriesEndDt': '1774915200000',
       'isTimeAnnounced': True,
       'stateTitle': 'Complete'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 136,
         'wickets': 10,
         'overs': 41.3},
        'inngs2': {'inningsId': 3,
         'runs': 454,
         'wickets': 10,
         'overs': 137.5}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 356,
         'wickets': 10,
         'overs': 112.4},
        'inngs2': {'inningsId': 4,
         'runs': 128,
         'wickets': 5,
         'overs': 36.6}}}},
     {'matchInfo': {'matchId': 133363,
       'seriesId': 10823,
       'seriesName': 'Sheffield Shield 2025-26',
       'matchDesc': '22nd Match',
       'matchFormat': 'TEST',
       'startDate': '1771200000000',
       'endDate': '1771484400000',
       'state': 'Complete',
       'status': 'South Australia won by 7 wkts',
       'team1': {'teamId': 164,
        'teamName': 'Queensland',
        'teamSName': 'QL',
        'imageId': 172233},
       'team2': {'teamId': 158,
        'teamName': 'South Australia',
        'teamSName': 'SAUS',
        'imageId': 172225},
       'venueInfo': {'id': 35,
        'ground': 'The Gabba',
        'city': 'Brisbane',
        'timezone': '+10:00',
        'latitude': '-27.485829',
        'longitude': '153.038055'},
       'currBatTeamId': 158,
       'seriesStartDt': '1759536000000',
       'seriesEndDt': '1774915200000',
       'isTimeAnnounced': True,
       'stateTitle': 'SAUS Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 185,
         'wickets': 10,
         'overs': 66.5},
        'inngs2': {'inningsId': 3, 'runs': 119, 'wickets': 10, 'overs': 50.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 214,
         'wickets': 10,
         'overs': 72.1},
        'inngs2': {'inningsId': 4, 'runs': 91, 'wickets': 3, 'overs': 36.6}}}},
     {'matchInfo': {'matchId': 133369,
       'seriesId': 10823,
       'seriesName': 'Sheffield Shield 2025-26',
       'matchDesc': '23rd Match',
       'matchFormat': 'TEST',
       'startDate': '1771209000000',
       'endDate': '1771493400000',
       'state': 'Complete',
       'status': 'Victoria won by 353 runs',
       'team1': {'teamId': 52,
        'teamName': 'Victoria',
        'teamSName': 'VIC',
        'imageId': 172153},
       'team2': {'teamId': 87,
        'teamName': 'Western Australia',
        'teamSName': 'WA',
        'imageId': 172180},
       'venueInfo': {'id': 38,
        'ground': 'W.A.C.A. Ground',
        'city': 'Perth',
        'timezone': '+08:00',
        'latitude': '-31.959806',
        'longitude': '115.879585'},
       'currBatTeamId': 52,
       'seriesStartDt': '1759536000000',
       'seriesEndDt': '1774915200000',
       'isTimeAnnounced': True,
       'stateTitle': 'VIC Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 431,
         'wickets': 9,
         'overs': 116.5,
         'isDeclared': True},
        'inngs2': {'inningsId': 3,
         'runs': 274,
         'wickets': 4,
         'overs': 58.6,
         'isDeclared': True}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 238,
         'wickets': 10,
         'overs': 80.2},
        'inngs2': {'inningsId': 4,
         'runs': 114,
         'wickets': 10,
         'overs': 44.5}}}}]}},
  {'ad': {'name': 'native_matches', 'layout': 'native_large', 'position': 4}},
  {'seriesAdWrapper': {'seriesId': 11559,
    'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
    'matches': [{'matchInfo': {'matchId': 147082,
       'seriesId': 11559,
       'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
       'matchDesc': '3rd Match',
       'matchFormat': 'ODI',
       'startDate': '1771747200000',
       'endDate': '1771776000000',
       'state': 'Complete',
       'status': 'South Africa Emerging Players won by 83 runs',
       'team1': {'teamId': 1782,
        'teamName': 'South Africa Emerging Players',
        'teamSName': 'SAEP',
        'imageId': 776290},
       'team2': {'teamId': 1775,
        'teamName': 'Border',
        'teamSName': 'BOR',
        'imageId': 349602},
       'venueInfo': {'id': 99,
        'ground': 'Buffalo Park',
        'city': 'East London',
        'timezone': '+02:00',
        'latitude': '-33.006727',
        'longitude': '27.919465'},
       'currBatTeamId': 1782,
       'seriesStartDt': '1771632000000',
       'seriesEndDt': '1774310400000',
       'isTimeAnnounced': True,
       'stateTitle': 'SAEP Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 270,
         'wickets': 7,
         'overs': 50.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 187,
         'wickets': 10,
         'overs': 46.0}}}},
     {'matchInfo': {'matchId': 147148,
       'seriesId': 11559,
       'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
       'matchDesc': '4th Match',
       'matchFormat': 'ODI',
       'startDate': '1771747200000',
       'endDate': '1771776000000',
       'state': 'Complete',
       'status': 'Knights won by 82 runs',
       'team1': {'teamId': 281,
        'teamName': 'Knights',
        'teamSName': 'KNG',
        'imageId': 172331},
       'team2': {'teamId': 912,
        'teamName': 'Limpopo',
        'teamSName': 'LIMPO',
        'imageId': 248430},
       'venueInfo': {'id': 772,
        'ground': 'Polokwane Cricket Club',
        'city': 'Polokwane',
        'timezone': '+02:00',
        'latitude': '-23.912260',
        'longitude': '29.453550'},
       'currBatTeamId': 281,
       'seriesStartDt': '1771632000000',
       'seriesEndDt': '1774310400000',
       'isTimeAnnounced': True,
       'stateTitle': 'KNG Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 328,
         'wickets': 4,
         'overs': 50.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 246,
         'wickets': 9,
         'overs': 50.0}}}},
     {'matchInfo': {'matchId': 147049,
       'seriesId': 11559,
       'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
       'matchDesc': '1st Match',
       'matchFormat': 'ODI',
       'startDate': '1771660800000',
       'endDate': '1771689600000',
       'state': 'Complete',
       'status': 'South Western Districts won by 7 wkts',
       'team1': {'teamId': 923,
        'teamName': 'Northern Cape',
        'teamSName': 'NCAPE',
        'imageId': 248438},
       'team2': {'teamId': 1768,
        'teamName': 'South Western Districts',
        'teamSName': 'SWD',
        'imageId': 349609},
       'venueInfo': {'id': 468,
        'ground': 'Recreation Ground',
        'city': 'Oudtshoorn',
        'timezone': '+02:00',
        'latitude': '22.1970307',
        'longitude': '-33.5934657'},
       'currBatTeamId': 1768,
       'seriesStartDt': '1771632000000',
       'seriesEndDt': '1774310400000',
       'isTimeAnnounced': True,
       'stateTitle': 'SWD Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 270,
         'wickets': 7,
         'overs': 50.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 275,
         'wickets': 3,
         'overs': 47.5}}}},
     {'matchInfo': {'matchId': 147060,
       'seriesId': 11559,
       'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
       'matchDesc': '2nd Match',
       'matchFormat': 'ODI',
       'startDate': '1771660800000',
       'endDate': '1771689600000',
       'state': 'Complete',
       'status': 'No result due to rain',
       'team1': {'teamId': 903,
        'teamName': 'Mpumalanga Rhinos',
        'teamSName': 'MPR',
        'imageId': 248434},
       'team2': {'teamId': 933,
        'teamName': 'Eastern Storm',
        'teamSName': 'ESTORM',
        'imageId': 248407},
       'venueInfo': {'id': 135,
        'ground': 'Willowmoore Park',
        'city': 'Benoni',
        'timezone': '+02:00',
        'latitude': '55.430751',
        'longitude': '-4.634697'},
       'seriesStartDt': '1771632000000',
       'seriesEndDt': '1774310400000',
       'isTimeAnnounced': True,
       'stateTitle': 'Complete'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 286,
         'wickets': 7,
         'overs': 50.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 16,
         'overs': 4.2}}}}]}},
  {'seriesAdWrapper': {'seriesId': 10829,
    'seriesName': 'Australia Domestic One-Day Cup 2025-26',
    'matches': [{'matchInfo': {'matchId': 133633,
       'seriesId': 10829,
       'seriesName': 'Australia Domestic One-Day Cup 2025-26',
       'matchDesc': '21st Match',
       'matchFormat': 'ODI',
       'startDate': '1771653600000',
       'endDate': '1771682400000',
       'state': 'Complete',
       'status': 'Western Australia won by 8 wkts',
       'team1': {'teamId': 52,
        'teamName': 'Victoria',
        'teamSName': 'VIC',
        'imageId': 172153},
       'team2': {'teamId': 87,
        'teamName': 'Western Australia',
        'teamSName': 'WA',
        'imageId': 172180},
       'venueInfo': {'id': 38,
        'ground': 'W.A.C.A. Ground',
        'city': 'Perth',
        'timezone': '+08:00',
        'latitude': '-31.959806',
        'longitude': '115.879585'},
       'currBatTeamId': 87,
       'seriesStartDt': '1757980800000',
       'seriesEndDt': '1773360000000',
       'isTimeAnnounced': True,
       'stateTitle': 'WA Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 230,
         'wickets': 9,
         'overs': 49.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 233,
         'wickets': 2,
         'overs': 39.5}}}},
     {'matchInfo': {'matchId': 133611,
       'seriesId': 10829,
       'seriesName': 'Australia Domestic One-Day Cup 2025-26',
       'matchDesc': '19th Match',
       'matchFormat': 'ODI',
       'startDate': '1771632000000',
       'endDate': '1771660800000',
       'state': 'Complete',
       'status': 'Queensland won by 125 runs',
       'team1': {'teamId': 164,
        'teamName': 'Queensland',
        'teamSName': 'QL',
        'imageId': 172233},
       'team2': {'teamId': 158,
        'teamName': 'South Australia',
        'teamSName': 'SAUS',
        'imageId': 172225},
       'venueInfo': {'id': 35,
        'ground': 'The Gabba',
        'city': 'Brisbane',
        'timezone': '+10:00',
        'latitude': '-27.485829',
        'longitude': '153.038055'},
       'currBatTeamId': 164,
       'seriesStartDt': '1757980800000',
       'seriesEndDt': '1773360000000',
       'isTimeAnnounced': True,
       'stateTitle': 'QL Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 260,
         'wickets': 10,
         'overs': 49.2}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 135,
         'wickets': 10,
         'overs': 26.1}}}},
     {'matchInfo': {'matchId': 133622,
       'seriesId': 10829,
       'seriesName': 'Australia Domestic One-Day Cup 2025-26',
       'matchDesc': '20th Match',
       'matchFormat': 'ODI',
       'startDate': '1771642800000',
       'endDate': '1771671600000',
       'state': 'Complete',
       'status': 'New South Wales won by 7 wkts',
       'team1': {'teamId': 166,
        'teamName': 'Tasmania',
        'teamSName': 'TAS',
        'imageId': 172235},
       'team2': {'teamId': 104,
        'teamName': 'New South Wales',
        'teamSName': 'NSW',
        'imageId': 172196},
       'venueInfo': {'id': 39,
        'ground': 'Bellerive Oval',
        'city': 'Hobart',
        'timezone': '+11:00',
        'latitude': '-42.877296',
        'longitude': '147.374013'},
       'currBatTeamId': 104,
       'seriesStartDt': '1757980800000',
       'seriesEndDt': '1773360000000',
       'isTimeAnnounced': True,
       'stateTitle': 'NSW Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 274,
         'wickets': 10,
         'overs': 49.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 275,
         'wickets': 3,
         'overs': 30.6}}}}]}},
  {'seriesAdWrapper': {'seriesId': 10878,
    'seriesName': 'CSA Four-Day Series Division One 2025-26',
    'matches': [{'matchInfo': {'matchId': 134089,
       'seriesId': 10878,

In [442]:
data5['typeMatches'][2]

{'matchType': 'Women',
 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 9611,
    'seriesName': 'India Women tour of Australia, 2026',
    'matches': [{'matchInfo': {'matchId': 117047,
       'seriesId': 9611,
       'seriesName': 'India Women tour of Australia, 2026',
       'matchDesc': '1st ODI',
       'matchFormat': 'ODI',
       'startDate': '1771905000000',
       'endDate': '1771933800000',
       'state': 'Complete',
       'status': 'Australia Women won by 6 wkts',
       'team1': {'teamId': 97,
        'teamName': 'India Women',
        'teamSName': 'INDW',
        'imageId': 776182},
       'team2': {'teamId': 100,
        'teamName': 'Australia Women',
        'teamSName': 'AUSW',
        'imageId': 776205},
       'venueInfo': {'id': 300,
        'ground': 'Allan Border Field',
        'city': 'Brisbane',
        'timezone': '+10:00',
        'latitude': '-27.435145',
        'longitude': '153.046143'},
       'currBatTeamId': 100,
       'seriesStartDt': '1771113600000',
       'seriesEndDt': '1772928000000',
       'isTimeAnnounced': True,
       'stateTitle': 'Complete'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 214,
         'wickets': 10,
         'overs': 48.3}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 217,
         'wickets': 4,
         'overs': 38.2}}}},
     {'matchInfo': {'matchId': 117035,
       'seriesId': 9611,
       'seriesName': 'India Women tour of Australia, 2026',
       'matchDesc': '2nd T20I',
       'matchFormat': 'T20',
       'startDate': '1771488900000',
       'endDate': '1771501500000',
       'state': 'Complete',
       'status': 'Australia Women won by 19 runs',
       'team1': {'teamId': 100,
        'teamName': 'Australia Women',
        'teamSName': 'AUSW',
        'imageId': 776205},
       'team2': {'teamId': 97,
        'teamName': 'India Women',
        'teamSName': 'INDW',
        'imageId': 776182},
       'venueInfo': {'id': 123,
        'ground': 'Manuka Oval',
        'city': 'Canberra',
        'timezone': '+11:00',
        'latitude': '-35.318630',
        'longitude': '149.136703'},
       'currBatTeamId': 100,
       'seriesStartDt': '1771113600000',
       'seriesEndDt': '1772928000000',
       'isTimeAnnounced': True,
       'stateTitle': 'AUSW Won',
       'isFantasyEnabled': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 163,
         'wickets': 5,
         'overs': 19.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 144,
         'wickets': 9,
         'overs': 19.6}}}},
     {'matchInfo': {'matchId': 117044,
       'seriesId': 9611,
       'seriesName': 'India Women tour of Australia, 2026',
       'matchDesc': '3rd T20I',
       'matchFormat': 'T20',
       'startDate': '1771661700000',
       'endDate': '1771674300000',
       'state': 'Complete',
       'status': 'India Women won by 17 runs',
       'team1': {'teamId': 97,
        'teamName': 'India Women',
        'teamSName': 'INDW',
        'imageId': 776182},
       'team2': {'teamId': 100,
        'teamName': 'Australia Women',
        'teamSName': 'AUSW',
        'imageId': 776205},
       'venueInfo': {'id': 40,
        'ground': 'Adelaide Oval',
        'city': 'Adelaide',
        'timezone': '+10:30',
        'latitude': '-34.915516',
        'longitude': '138.596115'},
       'currBatTeamId': 97,
       'seriesStartDt': '1771113600000',
       'seriesEndDt': '1772928000000',
       'isTimeAnnounced': True,
       'stateTitle': 'INDW Won',
       'isFantasyEnabled': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 176,
         'wickets': 6,
         'overs': 19.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 159,
         'wickets': 9,
         'overs': 19.6}}}}]}},
  {'seriesAdWrapper': {'seriesId': 11487,
    'seriesName': 'Sri Lanka Women tour of West Indies 2026',
    'matches': [{'matchInfo': {'matchId': 144620,
       'seriesId': 11487,
       'seriesName': 'Sri Lanka Women tour of West Indies 2026',
       'matchDesc': '2nd ODI',
       'matchFormat': 'ODI',
       'startDate': '1771767000000',
       'endDate': '1771795800000',
       'state': 'Complete',
       'status': 'Sri Lanka Women won by 14 runs',
       'team1': {'teamId': 258,
        'teamName': 'Sri Lanka Women',
        'teamSName': 'SLW',
        'imageId': 776267},
       'team2': {'teamId': 257,
        'teamName': 'West Indies Women',
        'teamSName': 'WIW',
        'imageId': 776194},
       'venueInfo': {'id': 101,
        'ground': 'National Cricket Stadium',
        'city': 'St Georges, Grenada',
        'timezone': '-04:00',
        'latitude': '12.059044',
        'longitude': '-61.752212'},
       'currBatTeamId': 258,
       'seriesStartDt': '1771545600000',
       'seriesEndDt': '1772668800000',
       'isTimeAnnounced': True,
       'stateTitle': 'SLW Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 208,
         'wickets': 10,
         'overs': 47.1}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 194,
         'wickets': 10,
         'overs': 47.6}}}},
     {'matchInfo': {'matchId': 144618,
       'seriesId': 11487,
       'seriesName': 'Sri Lanka Women tour of West Indies 2026',
       'matchDesc': '1st ODI',
       'matchFormat': 'ODI',
       'startDate': '1771594200000',
       'endDate': '1771623000000',
       'state': 'Complete',
       'status': 'Sri Lanka Women won by 10 runs',
       'team1': {'teamId': 258,
        'teamName': 'Sri Lanka Women',
        'teamSName': 'SLW',
        'imageId': 776267},
       'team2': {'teamId': 257,
        'teamName': 'West Indies Women',
        'teamSName': 'WIW',
        'imageId': 776194},
       'venueInfo': {'id': 101,
        'ground': 'National Cricket Stadium',
        'city': 'St Georges, Grenada',
        'timezone': '-04:00',
        'latitude': '12.059044',
        'longitude': '-61.752212'},
       'currBatTeamId': 258,
       'seriesStartDt': '1771545600000',
       'seriesEndDt': '1772668800000',
       'isTimeAnnounced': True,
       'stateTitle': 'SLW Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 240,
         'wickets': 6,
         'overs': 49.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 230,
         'wickets': 10,
         'overs': 49.4}}}}]}},
  {'seriesAdWrapper': {'seriesId': 10146,
    'seriesName': 'Pakistan Women tour of South Africa, 2026',
    'matches': [{'matchInfo': {'matchId': 122181,
       'seriesId': 10146,
       'seriesName': 'Pakistan Women tour of South Africa, 2026',
       'matchDesc': '1st ODI',
       'matchFormat': 'ODI',
       'startDate': '1771747200000',
       'endDate': '1771776000000',
       'state': 'Complete',
       'status': 'South Africa Women won by 37 runs (41 overs game due to rain)',
       'team1': {'teamId': 260,
        'teamName': 'South Africa Women',
        'teamSName': 'RSAW',
        'imageId': 776293},
       'team2': {'teamId': 259,
        'teamName': 'Pakistan Women',
        'teamSName': 'PAKW',
        'imageId': 776311},
       'venueInfo': {'id': 72,
        'ground': 'Mangaung Oval',
        'city': 'Bloemfontein',
        'timezone': '+02:00',
        'latitude': '-29.116752',
        'longitude': '26.20519'},
       'currBatTeamId': 260,
       'seriesStartDt': '1770681600000',
       'seriesEndDt': '1772496000000',
       'isTimeAnnounced': True,
       'stateTitle': 'RSAW Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 260,
         'wickets': 6,
         'overs': 40.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 223,
         'wickets': 10,
         'overs': 38.5}}}}]}},
  {'seriesAdWrapper': {'seriesId': 11452,
    'seriesName': "ACC Women's Asia Cup Rising Stars 2026",
    'matches': [{'matchInfo': {'matchId': 144362,
       'seriesId': 11452,
       'seriesName': "ACC Women's Asia Cup Rising Stars 2026",
       'matchDesc': 'Semi Final 1 (A1vB2)',
       'matchFormat': 'T20',
       'startDate': '1771554600000',
       'endDate': '1771567200000',
       'state': 'Complete',
       'status': 'India A Women won by 5 wkts',
       'team1': {'teamId': 1556,
        'teamName': 'Sri Lanka A Women',
        'teamSName': 'SLWA',
        'imageId': 776273},
       'team2': {'teamId': 440,
        'teamName': 'India A Women',
        'teamSName': 'INDWA',
        'imageId': 776184},
       'venueInfo': {'id': 474,
        'ground': 'Terdthai Cricket Ground',
        'city': 'Bangkok',
        'timezone': '+07:00',
        'latitude': '13.756331',
        'longitude': '100.501765'},
       'currBatTeamId': 440,
       'seriesStartDt': '1770940800000',
       'seriesEndDt': '1771891200000',
       'isTimeAnnounced': True,
       'stateTitle': 'INDWA Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 118,
         'wickets': 10,
         'overs': 19.4}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 119,
         'wickets': 5,
         'overs': 13.3}}}},
     {'matchInfo': {'matchId': 144384,
       'seriesId': 11452,
       'seriesName': "ACC Women's Asia Cup Rising Stars 2026",
       'matchDesc': 'Final',
       'matchFormat': 'T20',
       'startDate': '1771743600000',
       'endDate': '1771756200000',
       'state': 'Complete',
       'status': 'India A Women won by 46 runs',
       'team1': {'teamId': 440,
        'teamName': 'India A Women',
        'teamSName': 'INDWA',
        'imageId': 776184},
       'team2': {'teamId': 1549,
        'teamName': 'Bangladesh A Women',
        'teamSName': 'BANWA',
        'imageId': 776216},
       'venueInfo': {'id': 474,
        'ground': 'Terdthai Cricket Ground',
        'city': 'Bangkok',
        'timezone': '+07:00',
        'latitude': '13.756331',
        'longitude': '100.501765'},
       'currBatTeamId': 440,
       'seriesStartDt': '1770940800000',
       'seriesEndDt': '1771891200000',
       'isTimeAnnounced': True,
       'stateTitle': 'INDWA Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 134,
         'wickets': 7,
         'overs': 19.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 88,
         'wickets': 10,
         'overs': 19.1}}}},
     {'matchInfo': {'matchId': 144351,
       'seriesId': 11452,
       'seriesName': "ACC Women's Asia Cup Rising Stars 2026",
       'matchDesc': '12th Match, Group B',
       'matchFormat': 'T20',
       'startDate': '1771398000000',
       'endDate': '1771410600000',
       'state': 'Complete',
       'status': 'Sri Lanka A Women won by 23 runs',
       'team1': {'teamId': 1556,
        'teamName': 'Sri Lanka A Women',
        'teamSName': 'SLWA',
        'imageId': 776273},
       'team2': {'teamId': 382,
        'teamName': 'Thailand Women',
        'teamSName': 'THAIW',
        'imageId': 172435},
       'venueInfo': {'id': 474,
        'ground': 'Terdthai Cricket Ground',
        'city': 'Bangkok',
        'timezone': '+07:00',
        'latitude': '13.756331',
        'longitude': '100.501765'},
       'currBatTeamId': 1556,
       'seriesStartDt': '1770940800000',
       'seriesEndDt': '1771891200000',
       'isTimeAnnounced': True,
       'stateTitle': 'SLWA Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 133,
         'wickets': 5,
         'overs': 19.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 110,
         'wickets': 10,
         'overs': 19.2}}}},
     {'matchInfo': {'matchId': 144373,
       'seriesId': 11452,
       'seriesName': "ACC Women's Asia Cup Rising Stars 2026",
       'matchDesc': 'Semi Final 2 (B1vA2)',
       'matchFormat': 'T20',
       'startDate': '1771570800000',
       'endDate': '1771583400000',
       'state': 'Complete',
       'status': 'Bangladesh A Women won by 54 runs',
       'team1': {'teamId': 1549,
        'teamName': 'Bangladesh A Women',
        'teamSName': 'BANWA',
        'imageId': 776216},
       'team2': {'teamId': 1552,
        'teamName': 'Pakistan A Women',
        'teamSName': 'PAKWA',
        'imageId': 776324},
       'venueInfo': {'id': 474,
        'ground': 'Terdthai Cricket Ground',
        'city': 'Bangkok',
        'timezone': '+07:00',
        'latitude': '13.756331',
        'longitude': '100.501765'},
       'currBatTeamId': 1549,
       'seriesStartDt': '1770940800000',
       'seriesEndDt': '1771891200000',
       'isTimeAnnounced': True,
       'stateTitle': 'BANWA Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 110,
         'wickets': 8,
         'overs': 19.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 56,
         'wickets': 10,
         'overs': 16.4}}}},
     {'matchInfo': {'matchId': 144340,
       'seriesId': 11452,
       'seriesName': "ACC Women's Asia Cup Rising Stars 2026",
       'matchDesc': '11th Match, Group B',
       'matchFormat': 'T20',
       'startDate': '1771381800000',
       'endDate': '1771394400000',
       'state': 'Complete',
       'status': 'Bangladesh A Women won by 90 runs',
       'team1': {'teamId': 1549,
        'teamName': 'Bangladesh A Women',
        'teamSName': 'BANWA',
        'imageId': 776216},
       'team2': {'teamId': 445,
        'teamName': 'Malaysia Women',
        'teamSName': 'MLYW',
        'imageId': 776323},
       'venueInfo': {'id': 474,
        'ground': 'Terdthai Cricket Ground',
        'city': 'Bangkok',
        'timezone': '+07:00',
        'latitude': '13.756331',
        'longitude': '100.501765'},
       'currBatTeamId': 1549,
       'seriesStartDt': '1770940800000',
       'seriesEndDt': '1771891200000',
       'isTimeAnnounced': True,
       'stateTitle': 'BANWA Won'},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 151,
         'wickets': 7,
         'overs': 19.6}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 61,
         'wickets': 9,
         'overs': 19.6}}}}]}}]}

In [27]:
# Question 7

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats/0"

querystring = {"statsType":"highestScore", "matchType":"1"}

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

test_data = response.json()

{'filter': {'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'}, {'matchTypeId': '2', 'matchTypeDesc': 'odi'}, {'matchTypeId': '3', 'matchTypeDesc': 't20i'}], 'team': [{'id': '2', 'teamShortName': 'IND'}, {'id': '27', 'teamShortName': 'IRE'}, {'id': '3', 'teamShortName': 'PAK'}, {'id': '4', 'teamShortName': 'AUS'}, {'id': '5', 'teamShortName': 'SL'}, {'id': '6', 'teamShortName': 'BAN'}, {'id': '9', 'teamShortName': 'ENG'}, {'id': '10', 'teamShortName': 'WI'}, {'id': '11', 'teamShortName': 'RSA'}, {'id': '12', 'teamShortName': 'ZIM'}, {'id': '13', 'teamShortName': 'NZ'}, {'id': '96', 'teamShortName': 'AFG'}], 'selectedMatchType': 'test'}, 'headers': ['Batter', 'HS', 'Balls', 'SR', 'Vs'], 'values': [{'values': ['240', 'B Lara', '400', '582', '68.73', 'ENG']}, {'values': ['157', 'Matthew Hayden', '380', '437', '86.96', 'ZIM']}, {'values': ['240', 'B Lara', '375', '538', '69.70', 'ENG']}, {'values': ['101', 'Mahela', '374', '572', '65.38', 'RSA']}, {'values': ['11200', 'Mulder', '367', '334', '109.88', 'ZIM']}, {'values': ['4160', 'G Sobers', '365', '', '', 'PAK']}, {'values': ['5141', 'S Hutton', '364', '847', '42.98', 'AUS']}, {'values': ['102', 'S Jayasuriya', '340', '578', '58.82', 'IND']}, {'values': ['5759', 'H Mohammad', '337', '', '', 'WI']}, {'values': ['5074', 'W Hammond', '336', '', '', 'NZ']}, {'values': ['1739', 'Warner', '335', '418', '80.14', 'PAK']}, {'values': ['5945', 'DG Bradman', '334', '448', '74.55', 'ENG']}, {'values': ['4729', 'M Taylor', '334', '564', '59.22', 'PAK']}, {'values': ['247', 'Gayle', '333', '437', '76.20', 'SL']}, {'values': ['5308', 'G Gooch', '333', '485', '68.66', 'IND']}, {'values': ['35', 'Inzamam-ul-Haq', '329', '436', '75.46', 'NZ']}, {'values': ['138', 'Clarke', '329', '468', '70.30', 'IND']}, {'values': ['5052', 'A Sandham', '325', '640', '50.78', 'WI']}, {'values': ['26', 'Sehwag', '319', '304', '104.93', 'RSA']}, {'values': ['104', 'Sangakkara', '319', '482', '66.18', 'BAN']}, {'values': ['12201', 'Harry Brook', '317', '322', '98.45', 'PAK']}, {'values': ['247', 'Gayle', '317', '483', '65.63', 'RSA']}, {'values': ['130', 'Younis Khan', '313', '568', '55.11', 'SL']}, {'values': ['314', 'Amla', '311', '529', '58.79', 'ENG']}, {'values': ['4667', 'B Simpson', '311', '740', '42.03', 'ENG']}, {'values': ['5262', 'J Edrich', '310', '450', '68.89', 'NZ']}, {'values': ['26', 'Sehwag', '309', '375', '82.40', 'PAK']}, {'values': ['6045', 'B Cowper', '307', '589', '52.12', 'ENG']}, {'values': ['5945', 'DG Bradman', '304', '473', '64.27', 'ENG']}, {'values': ['8257', 'Karun Nair', '303', '381', '79.53', 'ENG']}], 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com', 'webURL': 'www.cricbuzz.com'}}

In [ ]:
for values in test_data.get('values'):
    row = values['values']
    rowt = row.append('test')
    print(row)

['240', 'B Lara', '400', '582', '68.73', 'ENG', 'test', 'test']
['157', 'Matthew Hayden', '380', '437', '86.96', 'ZIM', 'test', 'test']
['240', 'B Lara', '375', '538', '69.70', 'ENG', 'test', 'test']
['101', 'Mahela', '374', '572', '65.38', 'RSA', 'test', 'test']
['11200', 'Mulder', '367', '334', '109.88', 'ZIM', 'test', 'test']
['4160', 'G Sobers', '365', '', '', 'PAK', 'test', 'test']
['5141', 'S Hutton', '364', '847', '42.98', 'AUS', 'test', 'test']
['102', 'S Jayasuriya', '340', '578', '58.82', 'IND', 'test', 'test']
['5759', 'H Mohammad', '337', '', '', 'WI', 'test', 'test']
['5074', 'W Hammond', '336', '', '', 'NZ', 'test', 'test']
['1739', 'Warner', '335', '418', '80.14', 'PAK', 'test', 'test']
['5945', 'DG Bradman', '334', '448', '74.55', 'ENG', 'test', 'test']
['4729', 'M Taylor', '334', '564', '59.22', 'PAK', 'test', 'test']
['247', 'Gayle', '333', '437', '76.20', 'SL', 'test', 'test']
['5308', 'G Gooch', '333', '485', '68.66', 'IND', 'test', 'test']
['35', 'Inzamam-ul-Haq', '329', '436', '75.46', 'NZ', 'test', 'test']
['138', 'Clarke', '329', '468', '70.30', 'IND', 'test', 'test']
['5052', 'A Sandham', '325', '640', '50.78', 'WI', 'test', 'test']
['26', 'Sehwag', '319', '304', '104.93', 'RSA', 'test', 'test']
['104', 'Sangakkara', '319', '482', '66.18', 'BAN', 'test', 'test']
['12201', 'Harry Brook', '317', '322', '98.45', 'PAK', 'test', 'test']
['247', 'Gayle', '317', '483', '65.63', 'RSA', 'test', 'test']
['130', 'Younis Khan', '313', '568', '55.11', 'SL', 'test', 'test']
['314', 'Amla', '311', '529', '58.79', 'ENG', 'test', 'test']
['4667', 'B Simpson', '311', '740', '42.03', 'ENG', 'test', 'test']
['5262', 'J Edrich', '310', '450', '68.89', 'NZ', 'test', 'test']
['26', 'Sehwag', '309', '375', '82.40', 'PAK', 'test', 'test']
['6045', 'B Cowper', '307', '589', '52.12', 'ENG', 'test', 'test']
['5945', 'DG Bradman', '304', '473', '64.27', 'ENG', 'test', 'test']
['8257', 'Karun Nair', '303', '381', '79.53', 'ENG', 'test', 'test']

In [18]:
test_data['values']

[{'values': ['240', 'B Lara', '400', '582', '68.73', 'ENG']},
 {'values': ['157', 'Matthew Hayden', '380', '437', '86.96', 'ZIM']},
 {'values': ['240', 'B Lara', '375', '538', '69.70', 'ENG']},
 {'values': ['101', 'Mahela', '374', '572', '65.38', 'RSA']},
 {'values': ['11200', 'Mulder', '367', '334', '109.88', 'ZIM']},
 {'values': ['4160', 'G Sobers', '365', '', '', 'PAK']},
 {'values': ['5141', 'S Hutton', '364', '847', '42.98', 'AUS']},
 {'values': ['102', 'S Jayasuriya', '340', '578', '58.82', 'IND']},
 {'values': ['5759', 'H Mohammad', '337', '', '', 'WI']},
 {'values': ['5074', 'W Hammond', '336', '', '', 'NZ']},
 {'values': ['1739', 'Warner', '335', '418', '80.14', 'PAK']},
 {'values': ['5945', 'DG Bradman', '334', '448', '74.55', 'ENG']},
 {'values': ['4729', 'M Taylor', '334', '564', '59.22', 'PAK']},
 {'values': ['247', 'Gayle', '333', '437', '76.20', 'SL']},
 {'values': ['5308', 'G Gooch', '333', '485', '68.66', 'IND']},
 {'values': ['35', 'Inzamam-ul-Haq', '329', '436', '75.46', 'NZ']},
 {'values': ['138', 'Clarke', '329', '468', '70.30', 'IND']},
 {'values': ['5052', 'A Sandham', '325', '640', '50.78', 'WI']},
 {'values': ['26', 'Sehwag', '319', '304', '104.93', 'RSA']},
 {'values': ['104', 'Sangakkara', '319', '482', '66.18', 'BAN']},
 {'values': ['12201', 'Harry Brook', '317', '322', '98.45', 'PAK']},
 {'values': ['247', 'Gayle', '317', '483', '65.63', 'RSA']},
 {'values': ['130', 'Younis Khan', '313', '568', '55.11', 'SL']},
 {'values': ['314', 'Amla', '311', '529', '58.79', 'ENG']},
 {'values': ['4667', 'B Simpson', '311', '740', '42.03', 'ENG']},
 {'values': ['5262', 'J Edrich', '310', '450', '68.89', 'NZ']},
 {'values': ['26', 'Sehwag', '309', '375', '82.40', 'PAK']},
 {'values': ['6045', 'B Cowper', '307', '589', '52.12', 'ENG']},
 {'values': ['5945', 'DG Bradman', '304', '473', '64.27', 'ENG']},
 {'values': ['8257', 'Karun Nair', '303', '381', '79.53', 'ENG']}]

In [4]:
# Question 7

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats/0"

querystring = {"statsType":"highestScore", "matchType":"2"}

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

odi_data = response.json()

{'filter': {'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'}, {'matchTypeId': '2', 'matchTypeDesc': 'odi'}, {'matchTypeId': '3', 'matchTypeDesc': 't20i'}], 'team': [{'id': '2', 'teamShortName': 'IND'}, {'id': '27', 'teamShortName': 'IRE'}, {'id': '3', 'teamShortName': 'PAK'}, {'id': '4', 'teamShortName': 'AUS'}, {'id': '5', 'teamShortName': 'SL'}, {'id': '6', 'teamShortName': 'BAN'}, {'id': '9', 'teamShortName': 'ENG'}, {'id': '10', 'teamShortName': 'WI'}, {'id': '11', 'teamShortName': 'RSA'}, {'id': '12', 'teamShortName': 'ZIM'}, {'id': '13', 'teamShortName': 'NZ'}, {'id': '96', 'teamShortName': 'AFG'}], 'selectedMatchType': 'odi'}, 'headers': ['Batter', 'HS', 'Balls', 'SR', 'Vs'], 'values': [{'values': ['576', 'Rohit Sharma', '264', '173', '152.60', 'SL']}, {'values': ['1457', 'Martin Guptill', '237', '163', '145.40', 'WI']}, {'values': ['11855', 'Amelia Kerr', '232', '145', '160.00', 'IREW']}, {'values': ['26', 'Sehwag', '219', '149', '146.98', 'WI']}, {'values': ['247', 'Gayle', '215', '147', '146.26', 'ZIM']}, {'values': ['10276', 'Ishan Kishan', '210', '131', '160.31', 'BAN']}, {'values': ['13682', 'Pathum Nissanka', '210', '139', '151.08', 'AFG']}, {'values': ['10863', 'Fakhar Zaman', '210', '156', '134.62', 'ZIM']}, {'values': ['576', 'Rohit Sharma', '209', '158', '132.28', 'AUS']}, {'values': ['11808', 'Shubman Gill', '208', '149', '139.60', 'NZ']}, {'values': ['576', 'Rohit Sharma', '208', '153', '135.95', 'SL']}, {'values': ['7662', 'Glenn Maxwell', '201', '128', '157.03', 'AFG']}, {'values': ['25', 'Tendulkar', '200', '147', '136.05', 'RSA']}, {'values': ['9149', 'Chamari Athapaththu', '195', '139', '140.29', 'RSAW']}, {'values': ['3703', 'S Anwar', '194', '146', '132.88', 'IND']}, {'values': ['3460', 'C Coventry', '194', '156', '124.36', 'BAN']}, {'values': ['10863', 'Fakhar Zaman', '193', '155', '124.52', 'RSA']}, {'values': ['10103', 'George Munsey', '191', '150', '127.33', 'NED']}, {'values': ['1457', 'Martin Guptill', '189', '155', '121.94', 'ENG']}, {'values': ['102', 'S Jayasuriya', '189', '161', '117.39', 'IND']}, {'values': ['4163', 'Viv Richards', '189', '170', '111.18', 'ENG']}, {'values': ['4601', 'G Kirsten', '188', '159', '118.24', 'UAE']}, {'values': ['11098', 'Deepti Sharma', '188', '160', '117.50', 'IREW']}, {'values': ['25', 'Tendulkar', '186', '150', '124.00', 'NZ']}, {'values': ['158', 'Watson', '185', '96', '192.71', 'BAN']}, {'values': ['7825', 'du Plessis', '185', '141', '131.21', 'SL']}, {'values': ['11374', 'Laura Wolvaardt', '184', '147', '125.17', 'SLW']}, {'values': ['265', 'Dhoni', '183', '145', '126.21', 'SL']}, {'values': ['1413', 'Virat Kohli', '183', '148', '123.65', 'PAK']}, {'values': ['29', 'S Ganguly', '183', '158', '115.82', 'SL']}], 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com', 'webURL': 'www.cricbuzz.com'}}

In [5]:
odi_data

{'filter': {'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'},
   {'matchTypeId': '2', 'matchTypeDesc': 'odi'},
   {'matchTypeId': '3', 'matchTypeDesc': 't20i'}],
  'team': [{'id': '2', 'teamShortName': 'IND'},
   {'id': '27', 'teamShortName': 'IRE'},
   {'id': '3', 'teamShortName': 'PAK'},
   {'id': '4', 'teamShortName': 'AUS'},
   {'id': '5', 'teamShortName': 'SL'},
   {'id': '6', 'teamShortName': 'BAN'},
   {'id': '9', 'teamShortName': 'ENG'},
   {'id': '10', 'teamShortName': 'WI'},
   {'id': '11', 'teamShortName': 'RSA'},
   {'id': '12', 'teamShortName': 'ZIM'},
   {'id': '13', 'teamShortName': 'NZ'},
   {'id': '96', 'teamShortName': 'AFG'}],
  'selectedMatchType': 'odi'},
 'headers': ['Batter', 'HS', 'Balls', 'SR', 'Vs'],
 'values': [{'values': ['576', 'Rohit Sharma', '264', '173', '152.60', 'SL']},
  {'values': ['1457', 'Martin Guptill', '237', '163', '145.40', 'WI']},
  {'values': ['11855', 'Amelia Kerr', '232', '145', '160.00', 'IREW']},
  {'values': ['26', 'Sehwag', '219', '149', '146.98', 'WI']},
  {'values': ['247', 'Gayle', '215', '147', '146.26', 'ZIM']},
  {'values': ['10276', 'Ishan Kishan', '210', '131', '160.31', 'BAN']},
  {'values': ['13682', 'Pathum Nissanka', '210', '139', '151.08', 'AFG']},
  {'values': ['10863', 'Fakhar Zaman', '210', '156', '134.62', 'ZIM']},
  {'values': ['576', 'Rohit Sharma', '209', '158', '132.28', 'AUS']},
  {'values': ['11808', 'Shubman Gill', '208', '149', '139.60', 'NZ']},
  {'values': ['576', 'Rohit Sharma', '208', '153', '135.95', 'SL']},
  {'values': ['7662', 'Glenn Maxwell', '201', '128', '157.03', 'AFG']},
  {'values': ['25', 'Tendulkar', '200', '147', '136.05', 'RSA']},
  {'values': ['9149', 'Chamari Athapaththu', '195', '139', '140.29', 'RSAW']},
  {'values': ['3703', 'S Anwar', '194', '146', '132.88', 'IND']},
  {'values': ['3460', 'C Coventry', '194', '156', '124.36', 'BAN']},
  {'values': ['10863', 'Fakhar Zaman', '193', '155', '124.52', 'RSA']},
  {'values': ['10103', 'George Munsey', '191', '150', '127.33', 'NED']},
  {'values': ['1457', 'Martin Guptill', '189', '155', '121.94', 'ENG']},
  {'values': ['102', 'S Jayasuriya', '189', '161', '117.39', 'IND']},
  {'values': ['4163', 'Viv Richards', '189', '170', '111.18', 'ENG']},
  {'values': ['4601', 'G Kirsten', '188', '159', '118.24', 'UAE']},
  {'values': ['11098', 'Deepti Sharma', '188', '160', '117.50', 'IREW']},
  {'values': ['25', 'Tendulkar', '186', '150', '124.00', 'NZ']},
  {'values': ['158', 'Watson', '185', '96', '192.71', 'BAN']},
  {'values': ['7825', 'du Plessis', '185', '141', '131.21', 'SL']},
  {'values': ['11374', 'Laura Wolvaardt', '184', '147', '125.17', 'SLW']},
  {'values': ['265', 'Dhoni', '183', '145', '126.21', 'SL']},
  {'values': ['1413', 'Virat Kohli', '183', '148', '123.65', 'PAK']},
  {'values': ['29', 'S Ganguly', '183', '158', '115.82', 'SL']}],
 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com'}}

In [24]:
for values in odi_data.get('values'):
    row = values['values']
    rowt = row.append('odi')
    print(row)

['576', 'Rohit Sharma', '264', '173', '152.60', 'SL', 'test', 'odi']
['1457', 'Martin Guptill', '237', '163', '145.40', 'WI', 'test', 'odi']
['11855', 'Amelia Kerr', '232', '145', '160.00', 'IREW', 'test', 'odi']
['26', 'Sehwag', '219', '149', '146.98', 'WI', 'test', 'odi']
['247', 'Gayle', '215', '147', '146.26', 'ZIM', 'test', 'odi']
['10276', 'Ishan Kishan', '210', '131', '160.31', 'BAN', 'test', 'odi']
['13682', 'Pathum Nissanka', '210', '139', '151.08', 'AFG', 'test', 'odi']
['10863', 'Fakhar Zaman', '210', '156', '134.62', 'ZIM', 'test', 'odi']
['576', 'Rohit Sharma', '209', '158', '132.28', 'AUS', 'test', 'odi']
['11808', 'Shubman Gill', '208', '149', '139.60', 'NZ', 'test', 'odi']
['576', 'Rohit Sharma', '208', '153', '135.95', 'SL', 'test', 'odi']
['7662', 'Glenn Maxwell', '201', '128', '157.03', 'AFG', 'test', 'odi']
['25', 'Tendulkar', '200', '147', '136.05', 'RSA', 'test', 'odi']
['9149', 'Chamari Athapaththu', '195', '139', '140.29', 'RSAW', 'test', 'odi']
['3703', 'S Anwar', '194', '146', '132.88', 'IND', 'test', 'odi']
['3460', 'C Coventry', '194', '156', '124.36', 'BAN', 'test', 'odi']
['10863', 'Fakhar Zaman', '193', '155', '124.52', 'RSA', 'test', 'odi']
['10103', 'George Munsey', '191', '150', '127.33', 'NED', 'test', 'odi']
['1457', 'Martin Guptill', '189', '155', '121.94', 'ENG', 'test', 'odi']
['102', 'S Jayasuriya', '189', '161', '117.39', 'IND', 'test', 'odi']
['4163', 'Viv Richards', '189', '170', '111.18', 'ENG', 'test', 'odi']
['4601', 'G Kirsten', '188', '159', '118.24', 'UAE', 'test', 'odi']
['11098', 'Deepti Sharma', '188', '160', '117.50', 'IREW', 'test', 'odi']
['25', 'Tendulkar', '186', '150', '124.00', 'NZ', 'test', 'odi']
['158', 'Watson', '185', '96', '192.71', 'BAN', 'test', 'odi']
['7825', 'du Plessis', '185', '141', '131.21', 'SL', 'test', 'odi']
['11374', 'Laura Wolvaardt', '184', '147', '125.17', 'SLW', 'test', 'odi']
['265', 'Dhoni', '183', '145', '126.21', 'SL', 'test', 'odi']
['1413', 'Virat Kohli', '183', '148', '123.65', 'PAK', 'test', 'odi']
['29', 'S Ganguly', '183', '158', '115.82', 'SL', 'test', 'odi']

In [2]:
# Question 7

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats/0"

querystring = {"statsType":"highestScore", "matchType":"3"}

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

t20_data = response.json()

{'filter': {'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'}, {'matchTypeId': '2', 'matchTypeDesc': 'odi'}, {'matchTypeId': '3', 'matchTypeDesc': 't20i'}], 'team': [{'id': '2', 'teamShortName': 'IND'}, {'id': '27', 'teamShortName': 'IRE'}, {'id': '3', 'teamShortName': 'PAK'}, {'id': '4', 'teamShortName': 'AUS'}, {'id': '5', 'teamShortName': 'SL'}, {'id': '6', 'teamShortName': 'BAN'}, {'id': '9', 'teamShortName': 'ENG'}, {'id': '10', 'teamShortName': 'WI'}, {'id': '11', 'teamShortName': 'RSA'}, {'id': '12', 'teamShortName': 'ZIM'}, {'id': '13', 'teamShortName': 'NZ'}, {'id': '96', 'teamShortName': 'AFG'}], 'selectedMatchType': 't20i'}, 'headers': ['Batter', 'HS', 'Balls', 'SR', 'Vs'], 'values': [{'values': ['1643', 'Finch', '172', '76', '226.32', 'ZIM']}, {'values': ['41897', 'Lucia Taylor', '169', '84', '201.19', 'CHLW']}, {'values': ['21193', 'Zeeshan Khan', '164', '84', '195.24', 'HUN']}, {'values': ['12068', 'Hazratullah Zazai', '162', '62', '261.29', 'IRE']}, {'values': ['33878', 'Mohammad Ihsan', '160', '63', '253.97', 'CRT']}, {'values': ['1643', 'Finch', '156', '63', '247.62', 'ENG']}, {'values': ['41855', 'Maria Castineiras', '155', '77', '201.30', 'CHLW']}, {'values': ['21823', 'Sacha De Alwis', '150', '67', '223.88', 'BRAZIL']}, {'values': ['9113', 'Alyssa Healy', '148', '61', '242.62', 'SLW']}, {'values': ['11936', 'Chantam', '148', '69', '214.49', 'SINW']}, {'values': ['7662', 'Glenn Maxwell', '145', '65', '223.08', 'SL']}, {'values': ['41869', 'Albertina Galan', '145', '84', '172.62', 'CHLW']}, {'values': ['50853', 'Sahil Chauhan', '144', '41', '351.22', 'CYP']}, {'values': ['38869', 'Laura Agatha', '144', '71', '202.82', 'MEXW']}, {'values': ['10479', 'Phil Salt', '141', '60', '235.00', 'RSA']}, {'values': ['26246', 'Zeeshan Kukikhel', '137', '49', '279.59', 'AUT']}, {'values': ['15400', 'Kushal Malla', '137', '50', '274.00', 'MGL']}, {'values': ['11172', 'Finn Allen', '137', '62', '220.97', 'PAK']}, {'values': ['12086', 'Abhishek Sharma', '135', '54', '250.00', 'ENG']}, {'values': ['45659', 'Michael Levitt', '135', '62', '217.74', 'NAM']}, {'values': ['33605', 'Rebecca Blake', '135', '76', '177.63', 'MALW']}, {'values': ['8522', 'Jan Frylinck', '134', '65', '206.15', 'NGA']}, {'values': ['32611', 'Lachlan Lake', '134', '68', '197.06', 'CHN']}, {'values': ['9354', 'Sikandar Raza', '133', '43', '309.30', 'GM']}, {'values': ['9114', 'Meg Lanning', '133', '63', '211.11', 'ENGW']}, {'values': ['10424', "Max O'Dowd", '133', '73', '182.19', 'MLY']}, {'values': ['10103', 'George Munsey', '132', '61', '216.39', 'AUT']}, {'values': ['1429586', 'Darius Visser', '132', '62', '212.90', 'VAN']}, {'values': ['11256', 'Hayley Matthews', '132', '64', '206.25', 'AUSW']}, {'values': ['41312', 'Pedro Baron', '132', '122', '108.20', 'BHM']}], 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com', 'webURL': 'www.cricbuzz.com'}}

In [3]:
t20_data

{'filter': {'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'},
   {'matchTypeId': '2', 'matchTypeDesc': 'odi'},
   {'matchTypeId': '3', 'matchTypeDesc': 't20i'}],
  'team': [{'id': '2', 'teamShortName': 'IND'},
   {'id': '27', 'teamShortName': 'IRE'},
   {'id': '3', 'teamShortName': 'PAK'},
   {'id': '4', 'teamShortName': 'AUS'},
   {'id': '5', 'teamShortName': 'SL'},
   {'id': '6', 'teamShortName': 'BAN'},
   {'id': '9', 'teamShortName': 'ENG'},
   {'id': '10', 'teamShortName': 'WI'},
   {'id': '11', 'teamShortName': 'RSA'},
   {'id': '12', 'teamShortName': 'ZIM'},
   {'id': '13', 'teamShortName': 'NZ'},
   {'id': '96', 'teamShortName': 'AFG'}],
  'selectedMatchType': 't20i'},
 'headers': ['Batter', 'HS', 'Balls', 'SR', 'Vs'],
 'values': [{'values': ['1643', 'Finch', '172', '76', '226.32', 'ZIM']},
  {'values': ['41897', 'Lucia Taylor', '169', '84', '201.19', 'CHLW']},
  {'values': ['21193', 'Zeeshan Khan', '164', '84', '195.24', 'HUN']},
  {'values': ['12068', 'Hazratullah Zazai', '162', '62', '261.29', 'IRE']},
  {'values': ['33878', 'Mohammad Ihsan', '160', '63', '253.97', 'CRT']},
  {'values': ['1643', 'Finch', '156', '63', '247.62', 'ENG']},
  {'values': ['41855', 'Maria Castineiras', '155', '77', '201.30', 'CHLW']},
  {'values': ['21823', 'Sacha De Alwis', '150', '67', '223.88', 'BRAZIL']},
  {'values': ['9113', 'Alyssa Healy', '148', '61', '242.62', 'SLW']},
  {'values': ['11936', 'Chantam', '148', '69', '214.49', 'SINW']},
  {'values': ['7662', 'Glenn Maxwell', '145', '65', '223.08', 'SL']},
  {'values': ['41869', 'Albertina Galan', '145', '84', '172.62', 'CHLW']},
  {'values': ['50853', 'Sahil Chauhan', '144', '41', '351.22', 'CYP']},
  {'values': ['38869', 'Laura Agatha', '144', '71', '202.82', 'MEXW']},
  {'values': ['10479', 'Phil Salt', '141', '60', '235.00', 'RSA']},
  {'values': ['26246', 'Zeeshan Kukikhel', '137', '49', '279.59', 'AUT']},
  {'values': ['15400', 'Kushal Malla', '137', '50', '274.00', 'MGL']},
  {'values': ['11172', 'Finn Allen', '137', '62', '220.97', 'PAK']},
  {'values': ['12086', 'Abhishek Sharma', '135', '54', '250.00', 'ENG']},
  {'values': ['45659', 'Michael Levitt', '135', '62', '217.74', 'NAM']},
  {'values': ['33605', 'Rebecca Blake', '135', '76', '177.63', 'MALW']},
  {'values': ['8522', 'Jan Frylinck', '134', '65', '206.15', 'NGA']},
  {'values': ['32611', 'Lachlan Lake', '134', '68', '197.06', 'CHN']},
  {'values': ['9354', 'Sikandar Raza', '133', '43', '309.30', 'GM']},
  {'values': ['9114', 'Meg Lanning', '133', '63', '211.11', 'ENGW']},
  {'values': ['10424', "Max O'Dowd", '133', '73', '182.19', 'MLY']},
  {'values': ['10103', 'George Munsey', '132', '61', '216.39', 'AUT']},
  {'values': ['1429586', 'Darius Visser', '132', '62', '212.90', 'VAN']},
  {'values': ['11256', 'Hayley Matthews', '132', '64', '206.25', 'AUSW']},
  {'values': ['41312', 'Pedro Baron', '132', '122', '108.20', 'BHM']}],
 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com'}}

In [25]:
for values in t20_data.get('values'):
    row = values['values']
    rowt = row.append('t20')
    print(row)

['1643', 'Finch', '172', '76', '226.32', 'ZIM', 't20']
['41897', 'Lucia Taylor', '169', '84', '201.19', 'CHLW', 't20']
['21193', 'Zeeshan Khan', '164', '84', '195.24', 'HUN', 't20']
['12068', 'Hazratullah Zazai', '162', '62', '261.29', 'IRE', 't20']
['33878', 'Mohammad Ihsan', '160', '63', '253.97', 'CRT', 't20']
['1643', 'Finch', '156', '63', '247.62', 'ENG', 't20']
['41855', 'Maria Castineiras', '155', '77', '201.30', 'CHLW', 't20']
['21823', 'Sacha De Alwis', '150', '67', '223.88', 'BRAZIL', 't20']
['9113', 'Alyssa Healy', '148', '61', '242.62', 'SLW', 't20']
['11936', 'Chantam', '148', '69', '214.49', 'SINW', 't20']
['7662', 'Glenn Maxwell', '145', '65', '223.08', 'SL', 't20']
['41869', 'Albertina Galan', '145', '84', '172.62', 'CHLW', 't20']
['50853', 'Sahil Chauhan', '144', '41', '351.22', 'CYP', 't20']
['38869', 'Laura Agatha', '144', '71', '202.82', 'MEXW', 't20']
['10479', 'Phil Salt', '141', '60', '235.00', 'RSA', 't20']
['26246', 'Zeeshan Kukikhel', '137', '49', '279.59', 'AUT', 't20']
['15400', 'Kushal Malla', '137', '50', '274.00', 'MGL', 't20']
['11172', 'Finn Allen', '137', '62', '220.97', 'PAK', 't20']
['12086', 'Abhishek Sharma', '135', '54', '250.00', 'ENG', 't20']
['45659', 'Michael Levitt', '135', '62', '217.74', 'NAM', 't20']
['33605', 'Rebecca Blake', '135', '76', '177.63', 'MALW', 't20']
['8522', 'Jan Frylinck', '134', '65', '206.15', 'NGA', 't20']
['32611', 'Lachlan Lake', '134', '68', '197.06', 'CHN', 't20']
['9354', 'Sikandar Raza', '133', '43', '309.30', 'GM', 't20']
['9114', 'Meg Lanning', '133', '63', '211.11', 'ENGW', 't20']
['10424', "Max O'Dowd", '133', '73', '182.19', 'MLY', 't20']
['10103', 'George Munsey', '132', '61', '216.39', 'AUT', 't20']
['1429586', 'Darius Visser', '132', '62', '212.90', 'VAN', 't20']
['11256', 'Hayley Matthews', '132', '64', '206.25', 'AUSW', 't20']
['41312', 'Pedro Baron', '132', '122', '108.20', 'BHM', 't20']

In [ ]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/teams/v1/international"

headers = {
	"x-rapidapi-key": "cfc139f9acmsh9c243115962adf0p162b35jsn49345f34cdca",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

team_list = response.json()

In [ ]:
a = 5